# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddSkillPoints_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(679, 488)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 80, 54, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 54, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 54, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 54, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 31, 16))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(10, 220, 54, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(10, 240, 54, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(10, 260, 54, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(10, 280, 54, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(10, 300, 54, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(10, 320, 54, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(10, 340, 54, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(10, 360, 54, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(10, 380, 54, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(10, 400, 54, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(10, 420, 54, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(10, 440, 54, 16))
        self.label_19.setObjectName("label_19")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(230, 400, 54, 16))
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(230, 420, 54, 16))
        self.label_24.setObjectName("label_24")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(230, 220, 54, 16))
        self.label_26.setObjectName("label_26")
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setGeometry(QtCore.QRect(230, 360, 54, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setGeometry(QtCore.QRect(230, 340, 54, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setGeometry(QtCore.QRect(230, 180, 54, 16))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setGeometry(QtCore.QRect(230, 160, 54, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(Form)
        self.label_32.setGeometry(QtCore.QRect(230, 100, 54, 16))
        self.label_32.setObjectName("label_32")
        self.label_34 = QtWidgets.QLabel(Form)
        self.label_34.setGeometry(QtCore.QRect(230, 380, 54, 16))
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(Form)
        self.label_36.setGeometry(QtCore.QRect(230, 460, 54, 16))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(Form)
        self.label_37.setGeometry(QtCore.QRect(230, 440, 54, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(Form)
        self.label_38.setGeometry(QtCore.QRect(230, 320, 54, 16))
        self.label_38.setObjectName("label_38")
        self.label_40 = QtWidgets.QLabel(Form)
        self.label_40.setGeometry(QtCore.QRect(230, 200, 54, 16))
        self.label_40.setObjectName("label_40")
        self.label_42 = QtWidgets.QLabel(Form)
        self.label_42.setGeometry(QtCore.QRect(460, 380, 54, 16))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(Form)
        self.label_43.setGeometry(QtCore.QRect(460, 260, 54, 16))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(Form)
        self.label_44.setGeometry(QtCore.QRect(460, 400, 54, 16))
        self.label_44.setObjectName("label_44")
        self.label_47 = QtWidgets.QLabel(Form)
        self.label_47.setGeometry(QtCore.QRect(460, 280, 54, 16))
        self.label_47.setObjectName("label_47")
        self.label_50 = QtWidgets.QLabel(Form)
        self.label_50.setGeometry(QtCore.QRect(460, 160, 54, 16))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(Form)
        self.label_51.setGeometry(QtCore.QRect(460, 140, 54, 16))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(Form)
        self.label_52.setGeometry(QtCore.QRect(460, 80, 54, 16))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(Form)
        self.label_53.setGeometry(QtCore.QRect(460, 100, 54, 16))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(Form)
        self.label_54.setGeometry(QtCore.QRect(460, 360, 54, 16))
        self.label_54.setObjectName("label_54")
        self.label_58 = QtWidgets.QLabel(Form)
        self.label_58.setGeometry(QtCore.QRect(460, 300, 54, 16))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(Form)
        self.label_59.setGeometry(QtCore.QRect(460, 60, 54, 16))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(Form)
        self.label_60.setGeometry(QtCore.QRect(460, 180, 54, 16))
        self.label_60.setObjectName("label_60")
        self.pr1 = QtWidgets.QSpinBox(Form)
        self.pr1.setGeometry(QtCore.QRect(140, 80, 42, 16))
        self.pr1.setObjectName("pr1")
        self.in1 = QtWidgets.QSpinBox(Form)
        self.in1.setGeometry(QtCore.QRect(180, 80, 42, 16))
        self.in1.setObjectName("in1")
        self.pr2 = QtWidgets.QSpinBox(Form)
        self.pr2.setGeometry(QtCore.QRect(140, 100, 42, 16))
        self.pr2.setObjectName("pr2")
        self.in2 = QtWidgets.QSpinBox(Form)
        self.in2.setGeometry(QtCore.QRect(180, 100, 42, 16))
        self.in2.setObjectName("in2")
        self.pr3 = QtWidgets.QSpinBox(Form)
        self.pr3.setGeometry(QtCore.QRect(140, 120, 42, 16))
        self.pr3.setObjectName("pr3")
        self.in3 = QtWidgets.QSpinBox(Form)
        self.in3.setGeometry(QtCore.QRect(180, 120, 42, 16))
        self.in3.setObjectName("in3")
        self.pr4 = QtWidgets.QSpinBox(Form)
        self.pr4.setGeometry(QtCore.QRect(140, 140, 42, 16))
        self.pr4.setObjectName("pr4")
        self.in4 = QtWidgets.QSpinBox(Form)
        self.in4.setGeometry(QtCore.QRect(180, 140, 42, 16))
        self.in4.setObjectName("in4")
        self.pr5 = QtWidgets.QSpinBox(Form)
        self.pr5.setGeometry(QtCore.QRect(140, 160, 42, 16))
        self.pr5.setObjectName("pr5")
        self.in5 = QtWidgets.QSpinBox(Form)
        self.in5.setGeometry(QtCore.QRect(180, 160, 42, 16))
        self.in5.setObjectName("in5")
        self.pr6 = QtWidgets.QSpinBox(Form)
        self.pr6.setGeometry(QtCore.QRect(140, 180, 42, 16))
        self.pr6.setObjectName("pr6")
        self.in6 = QtWidgets.QSpinBox(Form)
        self.in6.setGeometry(QtCore.QRect(180, 180, 42, 16))
        self.in6.setObjectName("in6")
        self.pr7 = QtWidgets.QSpinBox(Form)
        self.pr7.setGeometry(QtCore.QRect(140, 200, 42, 16))
        self.pr7.setObjectName("pr7")
        self.in7 = QtWidgets.QSpinBox(Form)
        self.in7.setGeometry(QtCore.QRect(180, 200, 42, 16))
        self.in7.setObjectName("in7")
        self.pr8 = QtWidgets.QSpinBox(Form)
        self.pr8.setGeometry(QtCore.QRect(140, 220, 42, 16))
        self.pr8.setObjectName("pr8")
        self.in8 = QtWidgets.QSpinBox(Form)
        self.in8.setGeometry(QtCore.QRect(180, 220, 42, 16))
        self.in8.setObjectName("in8")
        self.pr9 = QtWidgets.QSpinBox(Form)
        self.pr9.setGeometry(QtCore.QRect(140, 240, 42, 16))
        self.pr9.setObjectName("pr9")
        self.in9 = QtWidgets.QSpinBox(Form)
        self.in9.setGeometry(QtCore.QRect(180, 240, 42, 16))
        self.in9.setObjectName("in9")
        self.pr10 = QtWidgets.QSpinBox(Form)
        self.pr10.setGeometry(QtCore.QRect(140, 260, 42, 16))
        self.pr10.setObjectName("pr10")
        self.in10 = QtWidgets.QSpinBox(Form)
        self.in10.setGeometry(QtCore.QRect(180, 260, 42, 16))
        self.in10.setObjectName("in10")
        self.pr11 = QtWidgets.QSpinBox(Form)
        self.pr11.setGeometry(QtCore.QRect(140, 280, 42, 16))
        self.pr11.setObjectName("pr11")
        self.in11 = QtWidgets.QSpinBox(Form)
        self.in11.setGeometry(QtCore.QRect(180, 280, 42, 16))
        self.in11.setObjectName("in11")
        self.pr12 = QtWidgets.QSpinBox(Form)
        self.pr12.setGeometry(QtCore.QRect(140, 300, 42, 16))
        self.pr12.setObjectName("pr12")
        self.in12 = QtWidgets.QSpinBox(Form)
        self.in12.setGeometry(QtCore.QRect(180, 300, 42, 16))
        self.in12.setObjectName("in12")
        self.pr13 = QtWidgets.QSpinBox(Form)
        self.pr13.setGeometry(QtCore.QRect(140, 320, 42, 16))
        self.pr13.setObjectName("pr13")
        self.in13 = QtWidgets.QSpinBox(Form)
        self.in13.setGeometry(QtCore.QRect(180, 320, 42, 16))
        self.in13.setObjectName("in13")
        self.pr14 = QtWidgets.QSpinBox(Form)
        self.pr14.setGeometry(QtCore.QRect(140, 340, 42, 16))
        self.pr14.setObjectName("pr14")
        self.in14 = QtWidgets.QSpinBox(Form)
        self.in14.setGeometry(QtCore.QRect(180, 340, 42, 16))
        self.in14.setObjectName("in14")
        self.pr15 = QtWidgets.QSpinBox(Form)
        self.pr15.setGeometry(QtCore.QRect(140, 360, 42, 16))
        self.pr15.setObjectName("pr15")
        self.in15 = QtWidgets.QSpinBox(Form)
        self.in15.setGeometry(QtCore.QRect(180, 360, 42, 16))
        self.in15.setObjectName("in15")
        self.pr16 = QtWidgets.QSpinBox(Form)
        self.pr16.setGeometry(QtCore.QRect(140, 380, 42, 16))
        self.pr16.setObjectName("pr16")
        self.in16 = QtWidgets.QSpinBox(Form)
        self.in16.setGeometry(QtCore.QRect(180, 380, 42, 16))
        self.in16.setObjectName("in16")
        self.pr17 = QtWidgets.QSpinBox(Form)
        self.pr17.setGeometry(QtCore.QRect(140, 400, 42, 16))
        self.pr17.setObjectName("pr17")
        self.in17 = QtWidgets.QSpinBox(Form)
        self.in17.setGeometry(QtCore.QRect(180, 400, 42, 16))
        self.in17.setObjectName("in17")
        self.pr18 = QtWidgets.QSpinBox(Form)
        self.pr18.setGeometry(QtCore.QRect(140, 420, 42, 16))
        self.pr18.setObjectName("pr18")
        self.in18 = QtWidgets.QSpinBox(Form)
        self.in18.setGeometry(QtCore.QRect(180, 420, 42, 16))
        self.in18.setObjectName("in18")
        self.pr19 = QtWidgets.QSpinBox(Form)
        self.pr19.setGeometry(QtCore.QRect(140, 440, 42, 16))
        self.pr19.setObjectName("pr19")
        self.in19 = QtWidgets.QSpinBox(Form)
        self.in19.setGeometry(QtCore.QRect(180, 440, 42, 16))
        self.in19.setObjectName("in19")
        self.pr20 = QtWidgets.QSpinBox(Form)
        self.pr20.setGeometry(QtCore.QRect(140, 460, 42, 16))
        self.pr20.setObjectName("pr20")
        self.in20 = QtWidgets.QSpinBox(Form)
        self.in20.setGeometry(QtCore.QRect(180, 460, 42, 16))
        self.in20.setObjectName("in20")
        self.pr39 = QtWidgets.QSpinBox(Form)
        self.pr39.setGeometry(QtCore.QRect(370, 440, 42, 16))
        self.pr39.setObjectName("pr39")
        self.pr35 = QtWidgets.QSpinBox(Form)
        self.pr35.setGeometry(QtCore.QRect(370, 360, 42, 16))
        self.pr35.setObjectName("pr35")
        self.in39 = QtWidgets.QSpinBox(Form)
        self.in39.setGeometry(QtCore.QRect(410, 440, 42, 16))
        self.in39.setObjectName("in39")
        self.in22 = QtWidgets.QSpinBox(Form)
        self.in22.setGeometry(QtCore.QRect(410, 100, 42, 16))
        self.in22.setObjectName("in22")
        self.pr29 = QtWidgets.QSpinBox(Form)
        self.pr29.setGeometry(QtCore.QRect(370, 240, 42, 16))
        self.pr29.setObjectName("pr29")
        self.pr32 = QtWidgets.QSpinBox(Form)
        self.pr32.setGeometry(QtCore.QRect(370, 300, 42, 16))
        self.pr32.setObjectName("pr32")
        self.pr31 = QtWidgets.QSpinBox(Form)
        self.pr31.setGeometry(QtCore.QRect(370, 280, 42, 16))
        self.pr31.setObjectName("pr31")
        self.in37 = QtWidgets.QSpinBox(Form)
        self.in37.setGeometry(QtCore.QRect(410, 400, 42, 16))
        self.in37.setObjectName("in37")
        self.pr27 = QtWidgets.QSpinBox(Form)
        self.pr27.setGeometry(QtCore.QRect(370, 200, 42, 16))
        self.pr27.setObjectName("pr27")
        self.pr28 = QtWidgets.QSpinBox(Form)
        self.pr28.setGeometry(QtCore.QRect(370, 220, 42, 16))
        self.pr28.setObjectName("pr28")
        self.pr21 = QtWidgets.QSpinBox(Form)
        self.pr21.setGeometry(QtCore.QRect(370, 80, 42, 16))
        self.pr21.setObjectName("pr21")
        self.pr36 = QtWidgets.QSpinBox(Form)
        self.pr36.setGeometry(QtCore.QRect(370, 380, 42, 16))
        self.pr36.setObjectName("pr36")
        self.in36 = QtWidgets.QSpinBox(Form)
        self.in36.setGeometry(QtCore.QRect(410, 380, 42, 16))
        self.in36.setObjectName("in36")
        self.in29 = QtWidgets.QSpinBox(Form)
        self.in29.setGeometry(QtCore.QRect(410, 240, 42, 16))
        self.in29.setObjectName("in29")
        self.pr24 = QtWidgets.QSpinBox(Form)
        self.pr24.setGeometry(QtCore.QRect(370, 140, 42, 16))
        self.pr24.setObjectName("pr24")
        self.pr37 = QtWidgets.QSpinBox(Form)
        self.pr37.setGeometry(QtCore.QRect(370, 400, 42, 16))
        self.pr37.setObjectName("pr37")
        self.in40 = QtWidgets.QSpinBox(Form)
        self.in40.setGeometry(QtCore.QRect(410, 460, 42, 16))
        self.in40.setObjectName("in40")
        self.in27 = QtWidgets.QSpinBox(Form)
        self.in27.setGeometry(QtCore.QRect(410, 200, 42, 16))
        self.in27.setObjectName("in27")
        self.in23 = QtWidgets.QSpinBox(Form)
        self.in23.setGeometry(QtCore.QRect(410, 120, 42, 16))
        self.in23.setObjectName("in23")
        self.pr26 = QtWidgets.QSpinBox(Form)
        self.pr26.setGeometry(QtCore.QRect(370, 180, 42, 16))
        self.pr26.setObjectName("pr26")
        self.in38 = QtWidgets.QSpinBox(Form)
        self.in38.setGeometry(QtCore.QRect(410, 420, 42, 16))
        self.in38.setObjectName("in38")
        self.in21 = QtWidgets.QSpinBox(Form)
        self.in21.setGeometry(QtCore.QRect(410, 80, 42, 16))
        self.in21.setObjectName("in21")
        self.pr34 = QtWidgets.QSpinBox(Form)
        self.pr34.setGeometry(QtCore.QRect(370, 340, 42, 16))
        self.pr34.setObjectName("pr34")
        self.pr38 = QtWidgets.QSpinBox(Form)
        self.pr38.setGeometry(QtCore.QRect(370, 420, 42, 16))
        self.pr38.setObjectName("pr38")
        self.pr33 = QtWidgets.QSpinBox(Form)
        self.pr33.setGeometry(QtCore.QRect(370, 320, 42, 16))
        self.pr33.setObjectName("pr33")
        self.in35 = QtWidgets.QSpinBox(Form)
        self.in35.setGeometry(QtCore.QRect(410, 360, 42, 16))
        self.in35.setObjectName("in35")
        self.in25 = QtWidgets.QSpinBox(Form)
        self.in25.setGeometry(QtCore.QRect(410, 160, 42, 16))
        self.in25.setObjectName("in25")
        self.pr22 = QtWidgets.QSpinBox(Form)
        self.pr22.setGeometry(QtCore.QRect(370, 100, 42, 16))
        self.pr22.setObjectName("pr22")
        self.in28 = QtWidgets.QSpinBox(Form)
        self.in28.setGeometry(QtCore.QRect(410, 220, 42, 16))
        self.in28.setObjectName("in28")
        self.in32 = QtWidgets.QSpinBox(Form)
        self.in32.setGeometry(QtCore.QRect(410, 300, 42, 16))
        self.in32.setObjectName("in32")
        self.in31 = QtWidgets.QSpinBox(Form)
        self.in31.setGeometry(QtCore.QRect(410, 280, 42, 16))
        self.in31.setObjectName("in31")
        self.pr40 = QtWidgets.QSpinBox(Form)
        self.pr40.setGeometry(QtCore.QRect(370, 460, 42, 16))
        self.pr40.setObjectName("pr40")
        self.pr25 = QtWidgets.QSpinBox(Form)
        self.pr25.setGeometry(QtCore.QRect(370, 160, 42, 16))
        self.pr25.setObjectName("pr25")
        self.pr23 = QtWidgets.QSpinBox(Form)
        self.pr23.setGeometry(QtCore.QRect(370, 120, 42, 16))
        self.pr23.setObjectName("pr23")
        self.in34 = QtWidgets.QSpinBox(Form)
        self.in34.setGeometry(QtCore.QRect(410, 340, 42, 16))
        self.in34.setObjectName("in34")
        self.in24 = QtWidgets.QSpinBox(Form)
        self.in24.setGeometry(QtCore.QRect(410, 140, 42, 16))
        self.in24.setObjectName("in24")
        self.in30 = QtWidgets.QSpinBox(Form)
        self.in30.setGeometry(QtCore.QRect(410, 260, 42, 16))
        self.in30.setObjectName("in30")
        self.pr30 = QtWidgets.QSpinBox(Form)
        self.pr30.setGeometry(QtCore.QRect(370, 260, 42, 16))
        self.pr30.setObjectName("pr30")
        self.in26 = QtWidgets.QSpinBox(Form)
        self.in26.setGeometry(QtCore.QRect(410, 180, 42, 16))
        self.in26.setObjectName("in26")
        self.in33 = QtWidgets.QSpinBox(Form)
        self.in33.setGeometry(QtCore.QRect(410, 320, 42, 16))
        self.in33.setObjectName("in33")
        self.pr59 = QtWidgets.QSpinBox(Form)
        self.pr59.setGeometry(QtCore.QRect(590, 420, 42, 16))
        self.pr59.setObjectName("pr59")
        self.pr55 = QtWidgets.QSpinBox(Form)
        self.pr55.setGeometry(QtCore.QRect(590, 340, 42, 16))
        self.pr55.setObjectName("pr55")
        self.in59 = QtWidgets.QSpinBox(Form)
        self.in59.setGeometry(QtCore.QRect(630, 420, 42, 16))
        self.in59.setObjectName("in59")
        self.in42 = QtWidgets.QSpinBox(Form)
        self.in42.setGeometry(QtCore.QRect(630, 80, 42, 16))
        self.in42.setObjectName("in42")
        self.pr49 = QtWidgets.QSpinBox(Form)
        self.pr49.setGeometry(QtCore.QRect(590, 220, 42, 16))
        self.pr49.setObjectName("pr49")
        self.pr52 = QtWidgets.QSpinBox(Form)
        self.pr52.setGeometry(QtCore.QRect(590, 280, 42, 16))
        self.pr52.setObjectName("pr52")
        self.pr51 = QtWidgets.QSpinBox(Form)
        self.pr51.setGeometry(QtCore.QRect(590, 260, 42, 16))
        self.pr51.setObjectName("pr51")
        self.in57 = QtWidgets.QSpinBox(Form)
        self.in57.setGeometry(QtCore.QRect(630, 380, 42, 16))
        self.in57.setObjectName("in57")
        self.pr47 = QtWidgets.QSpinBox(Form)
        self.pr47.setGeometry(QtCore.QRect(590, 180, 42, 16))
        self.pr47.setObjectName("pr47")
        self.pr48 = QtWidgets.QSpinBox(Form)
        self.pr48.setGeometry(QtCore.QRect(590, 200, 42, 16))
        self.pr48.setObjectName("pr48")
        self.pr41 = QtWidgets.QSpinBox(Form)
        self.pr41.setGeometry(QtCore.QRect(590, 60, 42, 16))
        self.pr41.setObjectName("pr41")
        self.pr56 = QtWidgets.QSpinBox(Form)
        self.pr56.setGeometry(QtCore.QRect(590, 360, 42, 16))
        self.pr56.setObjectName("pr56")
        self.in56 = QtWidgets.QSpinBox(Form)
        self.in56.setGeometry(QtCore.QRect(630, 360, 42, 16))
        self.in56.setObjectName("in56")
        self.in49 = QtWidgets.QSpinBox(Form)
        self.in49.setGeometry(QtCore.QRect(630, 220, 42, 16))
        self.in49.setObjectName("in49")
        self.pr44 = QtWidgets.QSpinBox(Form)
        self.pr44.setGeometry(QtCore.QRect(590, 120, 42, 16))
        self.pr44.setObjectName("pr44")
        self.pr57 = QtWidgets.QSpinBox(Form)
        self.pr57.setGeometry(QtCore.QRect(590, 380, 42, 16))
        self.pr57.setObjectName("pr57")
        self.in60 = QtWidgets.QSpinBox(Form)
        self.in60.setGeometry(QtCore.QRect(630, 440, 42, 16))
        self.in60.setObjectName("in60")
        self.in47 = QtWidgets.QSpinBox(Form)
        self.in47.setGeometry(QtCore.QRect(630, 180, 42, 16))
        self.in47.setObjectName("in47")
        self.in43 = QtWidgets.QSpinBox(Form)
        self.in43.setGeometry(QtCore.QRect(630, 100, 42, 16))
        self.in43.setObjectName("in43")
        self.pr46 = QtWidgets.QSpinBox(Form)
        self.pr46.setGeometry(QtCore.QRect(590, 160, 42, 16))
        self.pr46.setObjectName("pr46")
        self.in58 = QtWidgets.QSpinBox(Form)
        self.in58.setGeometry(QtCore.QRect(630, 400, 42, 16))
        self.in58.setObjectName("in58")
        self.in41 = QtWidgets.QSpinBox(Form)
        self.in41.setGeometry(QtCore.QRect(630, 60, 42, 16))
        self.in41.setObjectName("in41")
        self.pr54 = QtWidgets.QSpinBox(Form)
        self.pr54.setGeometry(QtCore.QRect(590, 320, 42, 16))
        self.pr54.setObjectName("pr54")
        self.pr58 = QtWidgets.QSpinBox(Form)
        self.pr58.setGeometry(QtCore.QRect(590, 400, 42, 16))
        self.pr58.setObjectName("pr58")
        self.pr53 = QtWidgets.QSpinBox(Form)
        self.pr53.setGeometry(QtCore.QRect(590, 300, 42, 16))
        self.pr53.setObjectName("pr53")
        self.in55 = QtWidgets.QSpinBox(Form)
        self.in55.setGeometry(QtCore.QRect(630, 340, 42, 16))
        self.in55.setObjectName("in55")
        self.in45 = QtWidgets.QSpinBox(Form)
        self.in45.setGeometry(QtCore.QRect(630, 140, 42, 16))
        self.in45.setObjectName("in45")
        self.pr42 = QtWidgets.QSpinBox(Form)
        self.pr42.setGeometry(QtCore.QRect(590, 80, 42, 16))
        self.pr42.setObjectName("pr42")
        self.in48 = QtWidgets.QSpinBox(Form)
        self.in48.setGeometry(QtCore.QRect(630, 200, 42, 16))
        self.in48.setObjectName("in48")
        self.in52 = QtWidgets.QSpinBox(Form)
        self.in52.setGeometry(QtCore.QRect(630, 280, 42, 16))
        self.in52.setObjectName("in52")
        self.in51 = QtWidgets.QSpinBox(Form)
        self.in51.setGeometry(QtCore.QRect(630, 260, 42, 16))
        self.in51.setObjectName("in51")
        self.pr60 = QtWidgets.QSpinBox(Form)
        self.pr60.setGeometry(QtCore.QRect(590, 440, 42, 16))
        self.pr60.setObjectName("pr60")
        self.pr45 = QtWidgets.QSpinBox(Form)
        self.pr45.setGeometry(QtCore.QRect(590, 140, 42, 16))
        self.pr45.setObjectName("pr45")
        self.pr43 = QtWidgets.QSpinBox(Form)
        self.pr43.setGeometry(QtCore.QRect(590, 100, 42, 16))
        self.pr43.setObjectName("pr43")
        self.in54 = QtWidgets.QSpinBox(Form)
        self.in54.setGeometry(QtCore.QRect(630, 320, 42, 16))
        self.in54.setObjectName("in54")
        self.in44 = QtWidgets.QSpinBox(Form)
        self.in44.setGeometry(QtCore.QRect(630, 120, 42, 16))
        self.in44.setObjectName("in44")
        self.in50 = QtWidgets.QSpinBox(Form)
        self.in50.setGeometry(QtCore.QRect(630, 240, 42, 16))
        self.in50.setObjectName("in50")
        self.pr50 = QtWidgets.QSpinBox(Form)
        self.pr50.setGeometry(QtCore.QRect(590, 240, 42, 16))
        self.pr50.setObjectName("pr50")
        self.in46 = QtWidgets.QSpinBox(Form)
        self.in46.setGeometry(QtCore.QRect(630, 160, 42, 16))
        self.in46.setObjectName("in46")
        self.in53 = QtWidgets.QSpinBox(Form)
        self.in53.setGeometry(QtCore.QRect(630, 300, 42, 16))
        self.in53.setObjectName("in53")
        self.next_step = QtWidgets.QPushButton(Form)
        self.next_step.setGeometry(QtCore.QRect(590, 460, 75, 23))
        self.next_step.setObjectName("next_step")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 31, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 31, 16))
        self.label_7.setObjectName("label_7")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(10, 460, 31, 16))
        self.label_20.setObjectName("label_20")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(230, 80, 31, 16))
        self.label_25.setObjectName("label_25")
        self.label_33 = QtWidgets.QLabel(Form)
        self.label_33.setGeometry(QtCore.QRect(230, 120, 31, 16))
        self.label_33.setObjectName("label_33")
        self.label_39 = QtWidgets.QLabel(Form)
        self.label_39.setGeometry(QtCore.QRect(230, 140, 31, 16))
        self.label_39.setObjectName("label_39")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(230, 240, 31, 16))
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(230, 260, 31, 16))
        self.label_23.setObjectName("label_23")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(230, 280, 31, 16))
        self.label_27.setObjectName("label_27")
        self.label_35 = QtWidgets.QLabel(Form)
        self.label_35.setGeometry(QtCore.QRect(230, 300, 31, 16))
        self.label_35.setObjectName("label_35")
        self.label_45 = QtWidgets.QLabel(Form)
        self.label_45.setGeometry(QtCore.QRect(460, 120, 31, 16))
        self.label_45.setObjectName("label_45")
        self.label_41 = QtWidgets.QLabel(Form)
        self.label_41.setGeometry(QtCore.QRect(460, 200, 31, 16))
        self.label_41.setObjectName("label_41")
        self.label_46 = QtWidgets.QLabel(Form)
        self.label_46.setGeometry(QtCore.QRect(460, 220, 31, 16))
        self.label_46.setObjectName("label_46")
        self.label_55 = QtWidgets.QLabel(Form)
        self.label_55.setGeometry(QtCore.QRect(460, 240, 31, 16))
        self.label_55.setObjectName("label_55")
        self.label_48 = QtWidgets.QLabel(Form)
        self.label_48.setGeometry(QtCore.QRect(460, 320, 31, 16))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(Form)
        self.label_49.setGeometry(QtCore.QRect(460, 340, 31, 16))
        self.label_49.setObjectName("label_49")
        self.label_56 = QtWidgets.QLabel(Form)
        self.label_56.setGeometry(QtCore.QRect(460, 420, 31, 16))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(Form)
        self.label_57.setGeometry(QtCore.QRect(460, 440, 31, 16))
        self.label_57.setObjectName("label_57")
        self.sub_skill5 = QtWidgets.QLabel(Form)
        self.sub_skill5.setGeometry(QtCore.QRect(40, 160, 91, 16))
        self.sub_skill5.setObjectName("sub_skill5")
        self.sub_skill6 = QtWidgets.QLabel(Form)
        self.sub_skill6.setGeometry(QtCore.QRect(40, 180, 91, 16))
        self.sub_skill6.setObjectName("sub_skill6")
        self.sub_skill7 = QtWidgets.QLabel(Form)
        self.sub_skill7.setGeometry(QtCore.QRect(40, 200, 91, 16))
        self.sub_skill7.setObjectName("sub_skill7")
        self.sub_skill20 = QtWidgets.QLabel(Form)
        self.sub_skill20.setGeometry(QtCore.QRect(40, 460, 91, 16))
        self.sub_skill20.setObjectName("sub_skill20")
        self.sub_skill21 = QtWidgets.QLabel(Form)
        self.sub_skill21.setGeometry(QtCore.QRect(260, 80, 91, 16))
        self.sub_skill21.setObjectName("sub_skill21")
        self.sub_skill23 = QtWidgets.QLabel(Form)
        self.sub_skill23.setGeometry(QtCore.QRect(260, 120, 91, 16))
        self.sub_skill23.setObjectName("sub_skill23")
        self.sub_skill24 = QtWidgets.QLabel(Form)
        self.sub_skill24.setGeometry(QtCore.QRect(260, 140, 81, 16))
        self.sub_skill24.setObjectName("sub_skill24")
        self.sub_skill29 = QtWidgets.QLabel(Form)
        self.sub_skill29.setGeometry(QtCore.QRect(260, 240, 91, 16))
        self.sub_skill29.setObjectName("sub_skill29")
        self.sub_skill30 = QtWidgets.QLabel(Form)
        self.sub_skill30.setGeometry(QtCore.QRect(260, 260, 91, 16))
        self.sub_skill30.setObjectName("sub_skill30")
        self.sub_skill31 = QtWidgets.QLabel(Form)
        self.sub_skill31.setGeometry(QtCore.QRect(260, 280, 91, 16))
        self.sub_skill31.setObjectName("sub_skill31")
        self.sub_skill32 = QtWidgets.QLabel(Form)
        self.sub_skill32.setGeometry(QtCore.QRect(260, 300, 91, 16))
        self.sub_skill32.setObjectName("sub_skill32")
        self.sub_skill44 = QtWidgets.QLabel(Form)
        self.sub_skill44.setGeometry(QtCore.QRect(490, 120, 91, 16))
        self.sub_skill44.setObjectName("sub_skill44")
        self.sub_skill49 = QtWidgets.QLabel(Form)
        self.sub_skill49.setGeometry(QtCore.QRect(490, 220, 91, 16))
        self.sub_skill49.setObjectName("sub_skill49")
        self.sub_skill50 = QtWidgets.QLabel(Form)
        self.sub_skill50.setGeometry(QtCore.QRect(490, 240, 91, 16))
        self.sub_skill50.setObjectName("sub_skill50")
        self.sub_skill54 = QtWidgets.QLabel(Form)
        self.sub_skill54.setGeometry(QtCore.QRect(490, 320, 91, 16))
        self.sub_skill54.setObjectName("sub_skill54")
        self.sub_skill55 = QtWidgets.QLabel(Form)
        self.sub_skill55.setGeometry(QtCore.QRect(490, 340, 91, 16))
        self.sub_skill55.setObjectName("sub_skill55")
        self.sub_skill59 = QtWidgets.QLabel(Form)
        self.sub_skill59.setGeometry(QtCore.QRect(490, 420, 91, 16))
        self.sub_skill59.setObjectName("sub_skill59")
        self.sub_skill60 = QtWidgets.QLabel(Form)
        self.sub_skill60.setGeometry(QtCore.QRect(490, 440, 91, 16))
        self.sub_skill60.setObjectName("sub_skill60")
        self.label_80 = QtWidgets.QLabel(Form)
        self.label_80.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(Form)
        self.label_81.setGeometry(QtCore.QRect(140, 60, 31, 16))
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(Form)
        self.label_82.setGeometry(QtCore.QRect(180, 60, 31, 16))
        self.label_82.setObjectName("label_82")
        self.label_83 = QtWidgets.QLabel(Form)
        self.label_83.setGeometry(QtCore.QRect(370, 60, 31, 16))
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(Form)
        self.label_84.setGeometry(QtCore.QRect(410, 60, 31, 16))
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(Form)
        self.label_85.setGeometry(QtCore.QRect(590, 40, 31, 16))
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(Form)
        self.label_86.setGeometry(QtCore.QRect(630, 40, 31, 16))
        self.label_86.setObjectName("label_86")
        self.label_87 = QtWidgets.QLabel(Form)
        self.label_87.setGeometry(QtCore.QRect(10, 40, 91, 16))
        self.label_87.setObjectName("label_87")
        self.professional_points = QtWidgets.QLabel(Form)
        self.professional_points.setGeometry(QtCore.QRect(100, 40, 21, 16))
        self.professional_points.setObjectName("professional_points")
        self.label_89 = QtWidgets.QLabel(Form)
        self.label_89.setGeometry(QtCore.QRect(140, 40, 91, 16))
        self.label_89.setObjectName("label_89")
        self.interest_points = QtWidgets.QLabel(Form)
        self.interest_points.setGeometry(QtCore.QRect(230, 40, 21, 16))
        self.interest_points.setObjectName("interest_points")
        self.professional_skills = QtWidgets.QTextBrowser(Form)
        self.professional_skills.setGeometry(QtCore.QRect(260, 10, 256, 51))
        self.professional_skills.setObjectName("professional_skills")
        self.label_88 = QtWidgets.QLabel(Form)
        self.label_88.setGeometry(QtCore.QRect(200, 10, 54, 12))
        self.label_88.setObjectName("label_88")
        self.sub_skill48 = QtWidgets.QLabel(Form)
        self.sub_skill48.setGeometry(QtCore.QRect(490, 200, 91, 16))
        self.sub_skill48.setObjectName("sub_skill48")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.label_3.setText(_translate("Form", "TextLabel"))
        self.label_4.setText(_translate("Form", "TextLabel"))
        self.label_5.setText(_translate("Form", "技艺:"))
        self.label_8.setText(_translate("Form", "TextLabel"))
        self.label_9.setText(_translate("Form", "TextLabel"))
        self.label_10.setText(_translate("Form", "TextLabel"))
        self.label_11.setText(_translate("Form", "TextLabel"))
        self.label_12.setText(_translate("Form", "TextLabel"))
        self.label_13.setText(_translate("Form", "TextLabel"))
        self.label_14.setText(_translate("Form", "TextLabel"))
        self.label_15.setText(_translate("Form", "TextLabel"))
        self.label_16.setText(_translate("Form", "TextLabel"))
        self.label_17.setText(_translate("Form", "TextLabel"))
        self.label_18.setText(_translate("Form", "TextLabel"))
        self.label_19.setText(_translate("Form", "TextLabel"))
        self.label_22.setText(_translate("Form", "TextLabel"))
        self.label_24.setText(_translate("Form", "TextLabel"))
        self.label_26.setText(_translate("Form", "TextLabel"))
        self.label_28.setText(_translate("Form", "TextLabel"))
        self.label_29.setText(_translate("Form", "TextLabel"))
        self.label_30.setText(_translate("Form", "TextLabel"))
        self.label_31.setText(_translate("Form", "TextLabel"))
        self.label_32.setText(_translate("Form", "TextLabel"))
        self.label_34.setText(_translate("Form", "TextLabel"))
        self.label_36.setText(_translate("Form", "TextLabel"))
        self.label_37.setText(_translate("Form", "TextLabel"))
        self.label_38.setText(_translate("Form", "TextLabel"))
        self.label_40.setText(_translate("Form", "TextLabel"))
        self.label_42.setText(_translate("Form", "TextLabel"))
        self.label_43.setText(_translate("Form", "TextLabel"))
        self.label_44.setText(_translate("Form", "TextLabel"))
        self.label_47.setText(_translate("Form", "TextLabel"))
        self.label_50.setText(_translate("Form", "TextLabel"))
        self.label_51.setText(_translate("Form", "TextLabel"))
        self.label_52.setText(_translate("Form", "TextLabel"))
        self.label_53.setText(_translate("Form", "TextLabel"))
        self.label_54.setText(_translate("Form", "TextLabel"))
        self.label_58.setText(_translate("Form", "TextLabel"))
        self.label_59.setText(_translate("Form", "TextLabel"))
        self.label_60.setText(_translate("Form", "TextLabel"))
        self.next_step.setText(_translate("Form", "下一步"))
        self.label_6.setText(_translate("Form", "技艺:"))
        self.label_7.setText(_translate("Form", "技艺:"))
        self.label_20.setText(_translate("Form", "技艺:"))
        self.label_25.setText(_translate("Form", "技艺:"))
        self.label_33.setText(_translate("Form", "技艺:"))
        self.label_39.setText(_translate("Form", "技艺:"))
        self.label_21.setText(_translate("Form", "技艺:"))
        self.label_23.setText(_translate("Form", "技艺:"))
        self.label_27.setText(_translate("Form", "技艺:"))
        self.label_35.setText(_translate("Form", "技艺:"))
        self.label_45.setText(_translate("Form", "技艺:"))
        self.label_41.setText(_translate("Form", "技艺:"))
        self.label_46.setText(_translate("Form", "技艺:"))
        self.label_55.setText(_translate("Form", "技艺:"))
        self.label_48.setText(_translate("Form", "技艺:"))
        self.label_49.setText(_translate("Form", "技艺:"))
        self.label_56.setText(_translate("Form", "技艺:"))
        self.label_57.setText(_translate("Form", "技艺:"))
        self.sub_skill5.setText(_translate("Form", "TextLabel"))
        self.sub_skill6.setText(_translate("Form", "TextLabel"))
        self.sub_skill7.setText(_translate("Form", "TextLabel"))
        self.sub_skill20.setText(_translate("Form", "TextLabel"))
        self.sub_skill21.setText(_translate("Form", "TextLabel"))
        self.sub_skill23.setText(_translate("Form", "TextLabel"))
        self.sub_skill24.setText(_translate("Form", "TextLabel"))
        self.sub_skill29.setText(_translate("Form", "TextLabel"))
        self.sub_skill30.setText(_translate("Form", "TextLabel"))
        self.sub_skill31.setText(_translate("Form", "TextLabel"))
        self.sub_skill32.setText(_translate("Form", "TextLabel"))
        self.sub_skill44.setText(_translate("Form", "TextLabel"))
        self.sub_skill49.setText(_translate("Form", "TextLabel"))
        self.sub_skill50.setText(_translate("Form", "TextLabel"))
        self.sub_skill54.setText(_translate("Form", "TextLabel"))
        self.sub_skill55.setText(_translate("Form", "TextLabel"))
        self.sub_skill59.setText(_translate("Form", "TextLabel"))
        self.sub_skill60.setText(_translate("Form", "TextLabel"))
        self.label_80.setText(_translate("Form", "请分配技能点"))
        self.label_81.setText(_translate("Form", "职业"))
        self.label_82.setText(_translate("Form", "兴趣"))
        self.label_83.setText(_translate("Form", "职业"))
        self.label_84.setText(_translate("Form", "兴趣"))
        self.label_85.setText(_translate("Form", "职业"))
        self.label_86.setText(_translate("Form", "兴趣"))
        self.label_87.setText(_translate("Form", "剩余职业技能点："))
        self.professional_points.setText(_translate("Form", "###"))
        self.label_89.setText(_translate("Form", "剩余兴趣技能点："))
        self.interest_points.setText(_translate("Form", "###"))
        self.label_88.setText(_translate("Form", "本职技能："))
        self.sub_skill48.setText(_translate("Form", "TextLabel"))
