# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddSkillPoints_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(893, 488)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 80, 54, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 54, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 54, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 54, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 31, 16))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(10, 220, 54, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(10, 240, 54, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(10, 260, 81, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(10, 280, 54, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(10, 300, 71, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(10, 320, 54, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(10, 340, 54, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(10, 360, 54, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(10, 380, 54, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(10, 400, 54, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(10, 420, 54, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(10, 440, 54, 16))
        self.label_19.setObjectName("label_19")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(300, 400, 54, 16))
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(300, 420, 54, 16))
        self.label_24.setObjectName("label_24")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(300, 220, 54, 16))
        self.label_26.setObjectName("label_26")
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setGeometry(QtCore.QRect(300, 360, 54, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setGeometry(QtCore.QRect(300, 340, 61, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setGeometry(QtCore.QRect(300, 180, 54, 16))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setGeometry(QtCore.QRect(300, 160, 54, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(Form)
        self.label_32.setGeometry(QtCore.QRect(300, 100, 54, 16))
        self.label_32.setObjectName("label_32")
        self.label_34 = QtWidgets.QLabel(Form)
        self.label_34.setGeometry(QtCore.QRect(300, 380, 54, 16))
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(Form)
        self.label_36.setGeometry(QtCore.QRect(300, 460, 54, 16))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(Form)
        self.label_37.setGeometry(QtCore.QRect(300, 440, 54, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(Form)
        self.label_38.setGeometry(QtCore.QRect(300, 320, 54, 16))
        self.label_38.setObjectName("label_38")
        self.label_40 = QtWidgets.QLabel(Form)
        self.label_40.setGeometry(QtCore.QRect(300, 200, 54, 16))
        self.label_40.setObjectName("label_40")
        self.label_42 = QtWidgets.QLabel(Form)
        self.label_42.setGeometry(QtCore.QRect(600, 380, 54, 16))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(Form)
        self.label_43.setGeometry(QtCore.QRect(600, 260, 54, 16))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(Form)
        self.label_44.setGeometry(QtCore.QRect(600, 400, 54, 16))
        self.label_44.setObjectName("label_44")
        self.label_47 = QtWidgets.QLabel(Form)
        self.label_47.setGeometry(QtCore.QRect(600, 280, 54, 16))
        self.label_47.setObjectName("label_47")
        self.label_50 = QtWidgets.QLabel(Form)
        self.label_50.setGeometry(QtCore.QRect(600, 160, 54, 16))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(Form)
        self.label_51.setGeometry(QtCore.QRect(600, 140, 54, 16))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(Form)
        self.label_52.setGeometry(QtCore.QRect(600, 80, 81, 16))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(Form)
        self.label_53.setGeometry(QtCore.QRect(600, 100, 54, 16))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(Form)
        self.label_54.setGeometry(QtCore.QRect(600, 360, 54, 16))
        self.label_54.setObjectName("label_54")
        self.label_58 = QtWidgets.QLabel(Form)
        self.label_58.setGeometry(QtCore.QRect(600, 300, 54, 16))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(Form)
        self.label_59.setGeometry(QtCore.QRect(600, 60, 54, 16))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(Form)
        self.label_60.setGeometry(QtCore.QRect(600, 180, 54, 16))
        self.label_60.setObjectName("label_60")
        self.pr1 = QtWidgets.QSpinBox(Form)
        self.pr1.setEnabled(True)
        self.pr1.setGeometry(QtCore.QRect(140, 80, 42, 16))
        self.pr1.setObjectName("pr1")
        self.in1 = QtWidgets.QSpinBox(Form)
        self.in1.setGeometry(QtCore.QRect(180, 80, 42, 16))
        self.in1.setObjectName("in1")
        self.pr2 = QtWidgets.QSpinBox(Form)
        self.pr2.setGeometry(QtCore.QRect(140, 100, 42, 16))
        self.pr2.setObjectName("pr2")
        self.in2 = QtWidgets.QSpinBox(Form)
        self.in2.setGeometry(QtCore.QRect(180, 100, 42, 16))
        self.in2.setObjectName("in2")
        self.pr3 = QtWidgets.QSpinBox(Form)
        self.pr3.setGeometry(QtCore.QRect(140, 120, 42, 16))
        self.pr3.setObjectName("pr3")
        self.in3 = QtWidgets.QSpinBox(Form)
        self.in3.setGeometry(QtCore.QRect(180, 120, 42, 16))
        self.in3.setObjectName("in3")
        self.pr4 = QtWidgets.QSpinBox(Form)
        self.pr4.setGeometry(QtCore.QRect(140, 140, 42, 16))
        self.pr4.setObjectName("pr4")
        self.in4 = QtWidgets.QSpinBox(Form)
        self.in4.setGeometry(QtCore.QRect(180, 140, 42, 16))
        self.in4.setObjectName("in4")
        self.pr5 = QtWidgets.QSpinBox(Form)
        self.pr5.setGeometry(QtCore.QRect(140, 160, 42, 16))
        self.pr5.setObjectName("pr5")
        self.in5 = QtWidgets.QSpinBox(Form)
        self.in5.setGeometry(QtCore.QRect(180, 160, 42, 16))
        self.in5.setObjectName("in5")
        self.pr6 = QtWidgets.QSpinBox(Form)
        self.pr6.setGeometry(QtCore.QRect(140, 180, 42, 16))
        self.pr6.setObjectName("pr6")
        self.in6 = QtWidgets.QSpinBox(Form)
        self.in6.setGeometry(QtCore.QRect(180, 180, 42, 16))
        self.in6.setObjectName("in6")
        self.pr7 = QtWidgets.QSpinBox(Form)
        self.pr7.setGeometry(QtCore.QRect(140, 200, 42, 16))
        self.pr7.setObjectName("pr7")
        self.in7 = QtWidgets.QSpinBox(Form)
        self.in7.setGeometry(QtCore.QRect(180, 200, 42, 16))
        self.in7.setObjectName("in7")
        self.pr8 = QtWidgets.QSpinBox(Form)
        self.pr8.setGeometry(QtCore.QRect(140, 220, 42, 16))
        self.pr8.setObjectName("pr8")
        self.in8 = QtWidgets.QSpinBox(Form)
        self.in8.setGeometry(QtCore.QRect(180, 220, 42, 16))
        self.in8.setObjectName("in8")
        self.pr9 = QtWidgets.QSpinBox(Form)
        self.pr9.setGeometry(QtCore.QRect(140, 240, 42, 16))
        self.pr9.setObjectName("pr9")
        self.in9 = QtWidgets.QSpinBox(Form)
        self.in9.setGeometry(QtCore.QRect(180, 240, 42, 16))
        self.in9.setObjectName("in9")
        self.pr10 = QtWidgets.QSpinBox(Form)
        self.pr10.setGeometry(QtCore.QRect(140, 260, 42, 16))
        self.pr10.setObjectName("pr10")
        self.in10 = QtWidgets.QSpinBox(Form)
        self.in10.setGeometry(QtCore.QRect(180, 260, 42, 16))
        self.in10.setObjectName("in10")
        self.pr11 = QtWidgets.QSpinBox(Form)
        self.pr11.setGeometry(QtCore.QRect(140, 280, 42, 16))
        self.pr11.setObjectName("pr11")
        self.in11 = QtWidgets.QSpinBox(Form)
        self.in11.setEnabled(False)
        self.in11.setGeometry(QtCore.QRect(180, 280, 42, 16))
        self.in11.setObjectName("in11")
        self.pr13 = QtWidgets.QSpinBox(Form)
        self.pr13.setGeometry(QtCore.QRect(140, 320, 42, 16))
        self.pr13.setObjectName("pr13")
        self.in13 = QtWidgets.QSpinBox(Form)
        self.in13.setGeometry(QtCore.QRect(180, 320, 42, 16))
        self.in13.setObjectName("in13")
        self.pr14 = QtWidgets.QSpinBox(Form)
        self.pr14.setGeometry(QtCore.QRect(140, 340, 42, 16))
        self.pr14.setObjectName("pr14")
        self.in14 = QtWidgets.QSpinBox(Form)
        self.in14.setGeometry(QtCore.QRect(180, 340, 42, 16))
        self.in14.setObjectName("in14")
        self.pr15 = QtWidgets.QSpinBox(Form)
        self.pr15.setGeometry(QtCore.QRect(140, 360, 42, 16))
        self.pr15.setObjectName("pr15")
        self.in15 = QtWidgets.QSpinBox(Form)
        self.in15.setGeometry(QtCore.QRect(180, 360, 42, 16))
        self.in15.setObjectName("in15")
        self.pr16 = QtWidgets.QSpinBox(Form)
        self.pr16.setGeometry(QtCore.QRect(140, 380, 42, 16))
        self.pr16.setObjectName("pr16")
        self.in16 = QtWidgets.QSpinBox(Form)
        self.in16.setGeometry(QtCore.QRect(180, 380, 42, 16))
        self.in16.setObjectName("in16")
        self.pr17 = QtWidgets.QSpinBox(Form)
        self.pr17.setGeometry(QtCore.QRect(140, 400, 42, 16))
        self.pr17.setObjectName("pr17")
        self.in17 = QtWidgets.QSpinBox(Form)
        self.in17.setGeometry(QtCore.QRect(180, 400, 42, 16))
        self.in17.setObjectName("in17")
        self.pr18 = QtWidgets.QSpinBox(Form)
        self.pr18.setGeometry(QtCore.QRect(140, 420, 42, 16))
        self.pr18.setObjectName("pr18")
        self.in18 = QtWidgets.QSpinBox(Form)
        self.in18.setGeometry(QtCore.QRect(180, 420, 42, 16))
        self.in18.setObjectName("in18")
        self.pr19 = QtWidgets.QSpinBox(Form)
        self.pr19.setGeometry(QtCore.QRect(140, 440, 42, 16))
        self.pr19.setObjectName("pr19")
        self.in19 = QtWidgets.QSpinBox(Form)
        self.in19.setGeometry(QtCore.QRect(180, 440, 42, 16))
        self.in19.setObjectName("in19")
        self.pr20 = QtWidgets.QSpinBox(Form)
        self.pr20.setGeometry(QtCore.QRect(140, 460, 42, 16))
        self.pr20.setObjectName("pr20")
        self.in20 = QtWidgets.QSpinBox(Form)
        self.in20.setGeometry(QtCore.QRect(180, 460, 42, 16))
        self.in20.setObjectName("in20")
        self.pr39 = QtWidgets.QSpinBox(Form)
        self.pr39.setGeometry(QtCore.QRect(430, 440, 42, 16))
        self.pr39.setObjectName("pr39")
        self.pr35 = QtWidgets.QSpinBox(Form)
        self.pr35.setGeometry(QtCore.QRect(430, 360, 42, 16))
        self.pr35.setObjectName("pr35")
        self.in39 = QtWidgets.QSpinBox(Form)
        self.in39.setGeometry(QtCore.QRect(470, 440, 42, 16))
        self.in39.setObjectName("in39")
        self.in22 = QtWidgets.QSpinBox(Form)
        self.in22.setGeometry(QtCore.QRect(470, 100, 42, 16))
        self.in22.setObjectName("in22")
        self.pr29 = QtWidgets.QSpinBox(Form)
        self.pr29.setGeometry(QtCore.QRect(430, 240, 42, 16))
        self.pr29.setObjectName("pr29")
        self.pr32 = QtWidgets.QSpinBox(Form)
        self.pr32.setGeometry(QtCore.QRect(430, 300, 42, 16))
        self.pr32.setObjectName("pr32")
        self.pr31 = QtWidgets.QSpinBox(Form)
        self.pr31.setGeometry(QtCore.QRect(430, 280, 42, 16))
        self.pr31.setObjectName("pr31")
        self.in37 = QtWidgets.QSpinBox(Form)
        self.in37.setGeometry(QtCore.QRect(470, 400, 42, 16))
        self.in37.setObjectName("in37")
        self.pr27 = QtWidgets.QSpinBox(Form)
        self.pr27.setGeometry(QtCore.QRect(430, 200, 42, 16))
        self.pr27.setObjectName("pr27")
        self.pr28 = QtWidgets.QSpinBox(Form)
        self.pr28.setGeometry(QtCore.QRect(430, 220, 42, 16))
        self.pr28.setObjectName("pr28")
        self.pr21 = QtWidgets.QSpinBox(Form)
        self.pr21.setGeometry(QtCore.QRect(430, 80, 42, 16))
        self.pr21.setObjectName("pr21")
        self.pr36 = QtWidgets.QSpinBox(Form)
        self.pr36.setGeometry(QtCore.QRect(430, 380, 42, 16))
        self.pr36.setObjectName("pr36")
        self.in36 = QtWidgets.QSpinBox(Form)
        self.in36.setGeometry(QtCore.QRect(470, 380, 42, 16))
        self.in36.setObjectName("in36")
        self.in29 = QtWidgets.QSpinBox(Form)
        self.in29.setGeometry(QtCore.QRect(470, 240, 42, 16))
        self.in29.setObjectName("in29")
        self.pr24 = QtWidgets.QSpinBox(Form)
        self.pr24.setGeometry(QtCore.QRect(430, 140, 42, 16))
        self.pr24.setObjectName("pr24")
        self.pr37 = QtWidgets.QSpinBox(Form)
        self.pr37.setGeometry(QtCore.QRect(430, 400, 42, 16))
        self.pr37.setObjectName("pr37")
        self.in40 = QtWidgets.QSpinBox(Form)
        self.in40.setGeometry(QtCore.QRect(470, 460, 42, 16))
        self.in40.setObjectName("in40")
        self.in27 = QtWidgets.QSpinBox(Form)
        self.in27.setGeometry(QtCore.QRect(470, 200, 42, 16))
        self.in27.setObjectName("in27")
        self.in23 = QtWidgets.QSpinBox(Form)
        self.in23.setGeometry(QtCore.QRect(470, 120, 42, 16))
        self.in23.setObjectName("in23")
        self.pr26 = QtWidgets.QSpinBox(Form)
        self.pr26.setGeometry(QtCore.QRect(430, 180, 42, 16))
        self.pr26.setObjectName("pr26")
        self.in38 = QtWidgets.QSpinBox(Form)
        self.in38.setGeometry(QtCore.QRect(470, 420, 42, 16))
        self.in38.setObjectName("in38")
        self.in21 = QtWidgets.QSpinBox(Form)
        self.in21.setGeometry(QtCore.QRect(470, 80, 42, 16))
        self.in21.setObjectName("in21")
        self.pr34 = QtWidgets.QSpinBox(Form)
        self.pr34.setGeometry(QtCore.QRect(430, 340, 42, 16))
        self.pr34.setObjectName("pr34")
        self.pr38 = QtWidgets.QSpinBox(Form)
        self.pr38.setGeometry(QtCore.QRect(430, 420, 42, 16))
        self.pr38.setObjectName("pr38")
        self.pr33 = QtWidgets.QSpinBox(Form)
        self.pr33.setGeometry(QtCore.QRect(430, 320, 42, 16))
        self.pr33.setObjectName("pr33")
        self.in35 = QtWidgets.QSpinBox(Form)
        self.in35.setGeometry(QtCore.QRect(470, 360, 42, 16))
        self.in35.setObjectName("in35")
        self.in25 = QtWidgets.QSpinBox(Form)
        self.in25.setGeometry(QtCore.QRect(470, 160, 42, 16))
        self.in25.setObjectName("in25")
        self.pr22 = QtWidgets.QSpinBox(Form)
        self.pr22.setGeometry(QtCore.QRect(430, 100, 42, 16))
        self.pr22.setObjectName("pr22")
        self.in28 = QtWidgets.QSpinBox(Form)
        self.in28.setGeometry(QtCore.QRect(470, 220, 42, 16))
        self.in28.setObjectName("in28")
        self.in32 = QtWidgets.QSpinBox(Form)
        self.in32.setGeometry(QtCore.QRect(470, 300, 42, 16))
        self.in32.setObjectName("in32")
        self.in31 = QtWidgets.QSpinBox(Form)
        self.in31.setGeometry(QtCore.QRect(470, 280, 42, 16))
        self.in31.setObjectName("in31")
        self.pr40 = QtWidgets.QSpinBox(Form)
        self.pr40.setGeometry(QtCore.QRect(430, 460, 42, 16))
        self.pr40.setObjectName("pr40")
        self.pr25 = QtWidgets.QSpinBox(Form)
        self.pr25.setGeometry(QtCore.QRect(430, 160, 42, 16))
        self.pr25.setObjectName("pr25")
        self.pr23 = QtWidgets.QSpinBox(Form)
        self.pr23.setGeometry(QtCore.QRect(430, 120, 42, 16))
        self.pr23.setObjectName("pr23")
        self.in34 = QtWidgets.QSpinBox(Form)
        self.in34.setGeometry(QtCore.QRect(470, 340, 42, 16))
        self.in34.setObjectName("in34")
        self.in24 = QtWidgets.QSpinBox(Form)
        self.in24.setGeometry(QtCore.QRect(470, 140, 42, 16))
        self.in24.setObjectName("in24")
        self.in30 = QtWidgets.QSpinBox(Form)
        self.in30.setGeometry(QtCore.QRect(470, 260, 42, 16))
        self.in30.setObjectName("in30")
        self.pr30 = QtWidgets.QSpinBox(Form)
        self.pr30.setGeometry(QtCore.QRect(430, 260, 42, 16))
        self.pr30.setObjectName("pr30")
        self.in26 = QtWidgets.QSpinBox(Form)
        self.in26.setGeometry(QtCore.QRect(470, 180, 42, 16))
        self.in26.setObjectName("in26")
        self.in33 = QtWidgets.QSpinBox(Form)
        self.in33.setGeometry(QtCore.QRect(470, 320, 42, 16))
        self.in33.setObjectName("in33")
        self.pr59 = QtWidgets.QSpinBox(Form)
        self.pr59.setGeometry(QtCore.QRect(720, 420, 42, 16))
        self.pr59.setObjectName("pr59")
        self.pr55 = QtWidgets.QSpinBox(Form)
        self.pr55.setGeometry(QtCore.QRect(720, 340, 42, 16))
        self.pr55.setObjectName("pr55")
        self.in59 = QtWidgets.QSpinBox(Form)
        self.in59.setGeometry(QtCore.QRect(760, 420, 42, 16))
        self.in59.setObjectName("in59")
        self.in42 = QtWidgets.QSpinBox(Form)
        self.in42.setGeometry(QtCore.QRect(760, 80, 42, 16))
        self.in42.setObjectName("in42")
        self.pr49 = QtWidgets.QSpinBox(Form)
        self.pr49.setGeometry(QtCore.QRect(720, 220, 42, 16))
        self.pr49.setObjectName("pr49")
        self.pr52 = QtWidgets.QSpinBox(Form)
        self.pr52.setGeometry(QtCore.QRect(720, 280, 42, 16))
        self.pr52.setObjectName("pr52")
        self.pr51 = QtWidgets.QSpinBox(Form)
        self.pr51.setGeometry(QtCore.QRect(720, 260, 42, 16))
        self.pr51.setObjectName("pr51")
        self.in57 = QtWidgets.QSpinBox(Form)
        self.in57.setGeometry(QtCore.QRect(760, 380, 42, 16))
        self.in57.setObjectName("in57")
        self.pr47 = QtWidgets.QSpinBox(Form)
        self.pr47.setGeometry(QtCore.QRect(720, 180, 42, 16))
        self.pr47.setObjectName("pr47")
        self.pr48 = QtWidgets.QSpinBox(Form)
        self.pr48.setGeometry(QtCore.QRect(720, 200, 42, 16))
        self.pr48.setObjectName("pr48")
        self.pr41 = QtWidgets.QSpinBox(Form)
        self.pr41.setGeometry(QtCore.QRect(720, 60, 42, 16))
        self.pr41.setObjectName("pr41")
        self.pr56 = QtWidgets.QSpinBox(Form)
        self.pr56.setGeometry(QtCore.QRect(720, 360, 42, 16))
        self.pr56.setObjectName("pr56")
        self.in56 = QtWidgets.QSpinBox(Form)
        self.in56.setGeometry(QtCore.QRect(760, 360, 42, 16))
        self.in56.setObjectName("in56")
        self.in49 = QtWidgets.QSpinBox(Form)
        self.in49.setGeometry(QtCore.QRect(760, 220, 42, 16))
        self.in49.setObjectName("in49")
        self.pr44 = QtWidgets.QSpinBox(Form)
        self.pr44.setGeometry(QtCore.QRect(720, 120, 42, 16))
        self.pr44.setObjectName("pr44")
        self.pr57 = QtWidgets.QSpinBox(Form)
        self.pr57.setGeometry(QtCore.QRect(720, 380, 42, 16))
        self.pr57.setObjectName("pr57")
        self.in60 = QtWidgets.QSpinBox(Form)
        self.in60.setGeometry(QtCore.QRect(760, 440, 42, 16))
        self.in60.setObjectName("in60")
        self.in47 = QtWidgets.QSpinBox(Form)
        self.in47.setGeometry(QtCore.QRect(760, 180, 42, 16))
        self.in47.setObjectName("in47")
        self.in43 = QtWidgets.QSpinBox(Form)
        self.in43.setGeometry(QtCore.QRect(760, 100, 42, 16))
        self.in43.setObjectName("in43")
        self.pr46 = QtWidgets.QSpinBox(Form)
        self.pr46.setGeometry(QtCore.QRect(720, 160, 42, 16))
        self.pr46.setObjectName("pr46")
        self.in58 = QtWidgets.QSpinBox(Form)
        self.in58.setGeometry(QtCore.QRect(760, 400, 42, 16))
        self.in58.setObjectName("in58")
        self.in41 = QtWidgets.QSpinBox(Form)
        self.in41.setGeometry(QtCore.QRect(760, 60, 42, 16))
        self.in41.setObjectName("in41")
        self.pr54 = QtWidgets.QSpinBox(Form)
        self.pr54.setGeometry(QtCore.QRect(720, 320, 42, 16))
        self.pr54.setObjectName("pr54")
        self.pr58 = QtWidgets.QSpinBox(Form)
        self.pr58.setGeometry(QtCore.QRect(720, 400, 42, 16))
        self.pr58.setObjectName("pr58")
        self.pr53 = QtWidgets.QSpinBox(Form)
        self.pr53.setGeometry(QtCore.QRect(720, 300, 42, 16))
        self.pr53.setObjectName("pr53")
        self.in55 = QtWidgets.QSpinBox(Form)
        self.in55.setGeometry(QtCore.QRect(760, 340, 42, 16))
        self.in55.setObjectName("in55")
        self.in45 = QtWidgets.QSpinBox(Form)
        self.in45.setGeometry(QtCore.QRect(760, 140, 42, 16))
        self.in45.setObjectName("in45")
        self.pr42 = QtWidgets.QSpinBox(Form)
        self.pr42.setGeometry(QtCore.QRect(720, 80, 42, 16))
        self.pr42.setObjectName("pr42")
        self.in48 = QtWidgets.QSpinBox(Form)
        self.in48.setGeometry(QtCore.QRect(760, 200, 42, 16))
        self.in48.setObjectName("in48")
        self.in52 = QtWidgets.QSpinBox(Form)
        self.in52.setGeometry(QtCore.QRect(760, 280, 42, 16))
        self.in52.setObjectName("in52")
        self.in51 = QtWidgets.QSpinBox(Form)
        self.in51.setGeometry(QtCore.QRect(760, 260, 42, 16))
        self.in51.setObjectName("in51")
        self.pr60 = QtWidgets.QSpinBox(Form)
        self.pr60.setGeometry(QtCore.QRect(720, 440, 42, 16))
        self.pr60.setObjectName("pr60")
        self.pr45 = QtWidgets.QSpinBox(Form)
        self.pr45.setGeometry(QtCore.QRect(720, 140, 42, 16))
        self.pr45.setObjectName("pr45")
        self.pr43 = QtWidgets.QSpinBox(Form)
        self.pr43.setGeometry(QtCore.QRect(720, 100, 42, 16))
        self.pr43.setObjectName("pr43")
        self.in54 = QtWidgets.QSpinBox(Form)
        self.in54.setGeometry(QtCore.QRect(760, 320, 42, 16))
        self.in54.setObjectName("in54")
        self.in44 = QtWidgets.QSpinBox(Form)
        self.in44.setGeometry(QtCore.QRect(760, 120, 42, 16))
        self.in44.setObjectName("in44")
        self.in50 = QtWidgets.QSpinBox(Form)
        self.in50.setGeometry(QtCore.QRect(760, 240, 42, 16))
        self.in50.setObjectName("in50")
        self.pr50 = QtWidgets.QSpinBox(Form)
        self.pr50.setGeometry(QtCore.QRect(720, 240, 42, 16))
        self.pr50.setObjectName("pr50")
        self.in46 = QtWidgets.QSpinBox(Form)
        self.in46.setGeometry(QtCore.QRect(760, 160, 42, 16))
        self.in46.setObjectName("in46")
        self.in53 = QtWidgets.QSpinBox(Form)
        self.in53.setGeometry(QtCore.QRect(760, 300, 42, 16))
        self.in53.setObjectName("in53")
        self.next_step = QtWidgets.QPushButton(Form)
        self.next_step.setGeometry(QtCore.QRect(800, 460, 75, 23))
        self.next_step.setObjectName("next_step")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 31, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 31, 16))
        self.label_7.setObjectName("label_7")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(10, 460, 31, 16))
        self.label_20.setObjectName("label_20")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(300, 80, 31, 16))
        self.label_25.setObjectName("label_25")
        self.label_33 = QtWidgets.QLabel(Form)
        self.label_33.setGeometry(QtCore.QRect(300, 120, 31, 16))
        self.label_33.setObjectName("label_33")
        self.label_39 = QtWidgets.QLabel(Form)
        self.label_39.setGeometry(QtCore.QRect(300, 140, 31, 16))
        self.label_39.setObjectName("label_39")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(300, 240, 31, 16))
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(300, 260, 31, 16))
        self.label_23.setObjectName("label_23")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(300, 280, 31, 16))
        self.label_27.setObjectName("label_27")
        self.label_35 = QtWidgets.QLabel(Form)
        self.label_35.setGeometry(QtCore.QRect(300, 300, 31, 16))
        self.label_35.setObjectName("label_35")
        self.label_45 = QtWidgets.QLabel(Form)
        self.label_45.setGeometry(QtCore.QRect(600, 120, 31, 16))
        self.label_45.setObjectName("label_45")
        self.label_41 = QtWidgets.QLabel(Form)
        self.label_41.setGeometry(QtCore.QRect(600, 200, 31, 16))
        self.label_41.setObjectName("label_41")
        self.label_46 = QtWidgets.QLabel(Form)
        self.label_46.setGeometry(QtCore.QRect(600, 220, 31, 16))
        self.label_46.setObjectName("label_46")
        self.label_55 = QtWidgets.QLabel(Form)
        self.label_55.setGeometry(QtCore.QRect(600, 240, 31, 16))
        self.label_55.setObjectName("label_55")
        self.label_48 = QtWidgets.QLabel(Form)
        self.label_48.setGeometry(QtCore.QRect(600, 320, 31, 16))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(Form)
        self.label_49.setGeometry(QtCore.QRect(600, 340, 31, 16))
        self.label_49.setObjectName("label_49")
        self.label_56 = QtWidgets.QLabel(Form)
        self.label_56.setGeometry(QtCore.QRect(600, 420, 31, 16))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(Form)
        self.label_57.setGeometry(QtCore.QRect(600, 440, 31, 16))
        self.label_57.setObjectName("label_57")
        self.sub_skill5 = QtWidgets.QLabel(Form)
        self.sub_skill5.setGeometry(QtCore.QRect(40, 160, 91, 16))
        self.sub_skill5.setObjectName("sub_skill5")
        self.sub_skill6 = QtWidgets.QLabel(Form)
        self.sub_skill6.setGeometry(QtCore.QRect(40, 180, 91, 16))
        self.sub_skill6.setObjectName("sub_skill6")
        self.sub_skill7 = QtWidgets.QLabel(Form)
        self.sub_skill7.setGeometry(QtCore.QRect(40, 200, 91, 16))
        self.sub_skill7.setObjectName("sub_skill7")
        self.sub_skill20 = QtWidgets.QLabel(Form)
        self.sub_skill20.setGeometry(QtCore.QRect(40, 460, 91, 16))
        self.sub_skill20.setObjectName("sub_skill20")
        self.sub_skill21 = QtWidgets.QLabel(Form)
        self.sub_skill21.setGeometry(QtCore.QRect(330, 80, 91, 16))
        self.sub_skill21.setObjectName("sub_skill21")
        self.sub_skill23 = QtWidgets.QLabel(Form)
        self.sub_skill23.setGeometry(QtCore.QRect(330, 120, 91, 16))
        self.sub_skill23.setObjectName("sub_skill23")
        self.sub_skill24 = QtWidgets.QLabel(Form)
        self.sub_skill24.setGeometry(QtCore.QRect(330, 140, 81, 16))
        self.sub_skill24.setObjectName("sub_skill24")
        self.sub_skill29 = QtWidgets.QLabel(Form)
        self.sub_skill29.setGeometry(QtCore.QRect(330, 240, 91, 16))
        self.sub_skill29.setObjectName("sub_skill29")
        self.sub_skill30 = QtWidgets.QLabel(Form)
        self.sub_skill30.setGeometry(QtCore.QRect(330, 260, 91, 16))
        self.sub_skill30.setObjectName("sub_skill30")
        self.sub_skill31 = QtWidgets.QLabel(Form)
        self.sub_skill31.setGeometry(QtCore.QRect(330, 280, 91, 16))
        self.sub_skill31.setObjectName("sub_skill31")
        self.sub_skill32 = QtWidgets.QLabel(Form)
        self.sub_skill32.setGeometry(QtCore.QRect(330, 300, 91, 16))
        self.sub_skill32.setObjectName("sub_skill32")
        self.sub_skill44 = QtWidgets.QLabel(Form)
        self.sub_skill44.setGeometry(QtCore.QRect(630, 120, 91, 16))
        self.sub_skill44.setObjectName("sub_skill44")
        self.sub_skill49 = QtWidgets.QLabel(Form)
        self.sub_skill49.setGeometry(QtCore.QRect(630, 220, 91, 16))
        self.sub_skill49.setObjectName("sub_skill49")
        self.sub_skill50 = QtWidgets.QLabel(Form)
        self.sub_skill50.setGeometry(QtCore.QRect(630, 240, 91, 16))
        self.sub_skill50.setObjectName("sub_skill50")
        self.sub_skill54 = QtWidgets.QLabel(Form)
        self.sub_skill54.setGeometry(QtCore.QRect(630, 320, 91, 16))
        self.sub_skill54.setObjectName("sub_skill54")
        self.sub_skill55 = QtWidgets.QLabel(Form)
        self.sub_skill55.setGeometry(QtCore.QRect(630, 340, 91, 16))
        self.sub_skill55.setObjectName("sub_skill55")
        self.sub_skill59 = QtWidgets.QLabel(Form)
        self.sub_skill59.setGeometry(QtCore.QRect(630, 420, 91, 16))
        self.sub_skill59.setObjectName("sub_skill59")
        self.sub_skill60 = QtWidgets.QLabel(Form)
        self.sub_skill60.setGeometry(QtCore.QRect(630, 440, 91, 16))
        self.sub_skill60.setObjectName("sub_skill60")
        self.label_80 = QtWidgets.QLabel(Form)
        self.label_80.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(Form)
        self.label_81.setGeometry(QtCore.QRect(140, 60, 31, 16))
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(Form)
        self.label_82.setGeometry(QtCore.QRect(180, 60, 31, 16))
        self.label_82.setObjectName("label_82")
        self.label_83 = QtWidgets.QLabel(Form)
        self.label_83.setGeometry(QtCore.QRect(430, 60, 31, 16))
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(Form)
        self.label_84.setGeometry(QtCore.QRect(470, 60, 31, 16))
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(Form)
        self.label_85.setGeometry(QtCore.QRect(720, 40, 31, 16))
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(Form)
        self.label_86.setGeometry(QtCore.QRect(760, 40, 31, 16))
        self.label_86.setObjectName("label_86")
        self.label_87 = QtWidgets.QLabel(Form)
        self.label_87.setGeometry(QtCore.QRect(280, 20, 91, 16))
        self.label_87.setObjectName("label_87")
        self.professional_points = QtWidgets.QLabel(Form)
        self.professional_points.setGeometry(QtCore.QRect(370, 20, 21, 16))
        self.professional_points.setObjectName("professional_points")
        self.label_89 = QtWidgets.QLabel(Form)
        self.label_89.setGeometry(QtCore.QRect(410, 20, 91, 16))
        self.label_89.setObjectName("label_89")
        self.interest_points = QtWidgets.QLabel(Form)
        self.interest_points.setGeometry(QtCore.QRect(500, 20, 21, 16))
        self.interest_points.setObjectName("interest_points")
        self.sub_skill48 = QtWidgets.QLabel(Form)
        self.sub_skill48.setGeometry(QtCore.QRect(630, 200, 91, 16))
        self.sub_skill48.setObjectName("sub_skill48")
        self.pr12 = QtWidgets.QSpinBox(Form)
        self.pr12.setEnabled(False)
        self.pr12.setGeometry(QtCore.QRect(140, 300, 42, 16))
        self.pr12.setObjectName("pr12")
        self.in12 = QtWidgets.QSpinBox(Form)
        self.in12.setEnabled(False)
        self.in12.setGeometry(QtCore.QRect(180, 300, 42, 16))
        self.in12.setObjectName("in12")
        self.label_88 = QtWidgets.QLabel(Form)
        self.label_88.setGeometry(QtCore.QRect(100, 20, 81, 16))
        self.label_88.setObjectName("label_88")
        self.min_credit = QtWidgets.QLabel(Form)
        self.min_credit.setGeometry(QtCore.QRect(180, 20, 21, 16))
        self.min_credit.setObjectName("min_credit")
        self.max_credit = QtWidgets.QLabel(Form)
        self.max_credit.setGeometry(QtCore.QRect(230, 20, 21, 16))
        self.max_credit.setObjectName("max_credit")
        self.professional_points_4 = QtWidgets.QLabel(Form)
        self.professional_points_4.setGeometry(QtCore.QRect(210, 20, 16, 16))
        self.professional_points_4.setObjectName("professional_points_4")
        self.label_90 = QtWidgets.QLabel(Form)
        self.label_90.setGeometry(QtCore.QRect(230, 60, 31, 16))
        self.label_90.setObjectName("label_90")
        self.sum_1 = QtWidgets.QLabel(Form)
        self.sum_1.setGeometry(QtCore.QRect(230, 80, 31, 16))
        self.sum_1.setObjectName("sum_1")
        self.sum_2 = QtWidgets.QLabel(Form)
        self.sum_2.setGeometry(QtCore.QRect(230, 100, 31, 16))
        self.sum_2.setObjectName("sum_2")
        self.sum_3 = QtWidgets.QLabel(Form)
        self.sum_3.setGeometry(QtCore.QRect(230, 120, 31, 16))
        self.sum_3.setObjectName("sum_3")
        self.sum_4 = QtWidgets.QLabel(Form)
        self.sum_4.setGeometry(QtCore.QRect(230, 140, 31, 16))
        self.sum_4.setObjectName("sum_4")
        self.sum_5 = QtWidgets.QLabel(Form)
        self.sum_5.setGeometry(QtCore.QRect(230, 160, 31, 16))
        self.sum_5.setObjectName("sum_5")
        self.sum_6 = QtWidgets.QLabel(Form)
        self.sum_6.setGeometry(QtCore.QRect(230, 180, 31, 16))
        self.sum_6.setObjectName("sum_6")
        self.sum_7 = QtWidgets.QLabel(Form)
        self.sum_7.setGeometry(QtCore.QRect(230, 200, 31, 16))
        self.sum_7.setObjectName("sum_7")
        self.sum_8 = QtWidgets.QLabel(Form)
        self.sum_8.setGeometry(QtCore.QRect(230, 220, 31, 16))
        self.sum_8.setObjectName("sum_8")
        self.sum_9 = QtWidgets.QLabel(Form)
        self.sum_9.setGeometry(QtCore.QRect(230, 240, 31, 16))
        self.sum_9.setObjectName("sum_9")
        self.sum_10 = QtWidgets.QLabel(Form)
        self.sum_10.setGeometry(QtCore.QRect(230, 260, 31, 16))
        self.sum_10.setObjectName("sum_10")
        self.sum_11 = QtWidgets.QLabel(Form)
        self.sum_11.setGeometry(QtCore.QRect(230, 280, 31, 16))
        self.sum_11.setObjectName("sum_11")
        self.sum_12 = QtWidgets.QLabel(Form)
        self.sum_12.setGeometry(QtCore.QRect(230, 300, 31, 16))
        self.sum_12.setObjectName("sum_12")
        self.sum_13 = QtWidgets.QLabel(Form)
        self.sum_13.setGeometry(QtCore.QRect(230, 320, 31, 16))
        self.sum_13.setObjectName("sum_13")
        self.sum_14 = QtWidgets.QLabel(Form)
        self.sum_14.setGeometry(QtCore.QRect(230, 340, 31, 16))
        self.sum_14.setObjectName("sum_14")
        self.sum_15 = QtWidgets.QLabel(Form)
        self.sum_15.setGeometry(QtCore.QRect(230, 360, 31, 16))
        self.sum_15.setObjectName("sum_15")
        self.sum_16 = QtWidgets.QLabel(Form)
        self.sum_16.setGeometry(QtCore.QRect(230, 380, 31, 16))
        self.sum_16.setObjectName("sum_16")
        self.sum_17 = QtWidgets.QLabel(Form)
        self.sum_17.setGeometry(QtCore.QRect(230, 400, 31, 16))
        self.sum_17.setObjectName("sum_17")
        self.sum_18 = QtWidgets.QLabel(Form)
        self.sum_18.setGeometry(QtCore.QRect(230, 420, 31, 16))
        self.sum_18.setObjectName("sum_18")
        self.sum_19 = QtWidgets.QLabel(Form)
        self.sum_19.setGeometry(QtCore.QRect(230, 440, 31, 16))
        self.sum_19.setObjectName("sum_19")
        self.sum_20 = QtWidgets.QLabel(Form)
        self.sum_20.setGeometry(QtCore.QRect(230, 460, 31, 16))
        self.sum_20.setObjectName("sum_20")
        self.sum_21 = QtWidgets.QLabel(Form)
        self.sum_21.setGeometry(QtCore.QRect(520, 80, 31, 16))
        self.sum_21.setObjectName("sum_21")
        self.sum_22 = QtWidgets.QLabel(Form)
        self.sum_22.setGeometry(QtCore.QRect(520, 100, 31, 16))
        self.sum_22.setObjectName("sum_22")
        self.sum_23 = QtWidgets.QLabel(Form)
        self.sum_23.setGeometry(QtCore.QRect(520, 120, 31, 16))
        self.sum_23.setObjectName("sum_23")
        self.sum_24 = QtWidgets.QLabel(Form)
        self.sum_24.setGeometry(QtCore.QRect(520, 140, 31, 16))
        self.sum_24.setObjectName("sum_24")
        self.sum_25 = QtWidgets.QLabel(Form)
        self.sum_25.setGeometry(QtCore.QRect(520, 160, 31, 16))
        self.sum_25.setObjectName("sum_25")
        self.sum_26 = QtWidgets.QLabel(Form)
        self.sum_26.setGeometry(QtCore.QRect(520, 180, 31, 16))
        self.sum_26.setObjectName("sum_26")
        self.sum_27 = QtWidgets.QLabel(Form)
        self.sum_27.setGeometry(QtCore.QRect(520, 200, 31, 16))
        self.sum_27.setObjectName("sum_27")
        self.sum_28 = QtWidgets.QLabel(Form)
        self.sum_28.setGeometry(QtCore.QRect(520, 220, 31, 16))
        self.sum_28.setObjectName("sum_28")
        self.sum_29 = QtWidgets.QLabel(Form)
        self.sum_29.setGeometry(QtCore.QRect(520, 240, 31, 16))
        self.sum_29.setObjectName("sum_29")
        self.sum_30 = QtWidgets.QLabel(Form)
        self.sum_30.setGeometry(QtCore.QRect(520, 260, 31, 16))
        self.sum_30.setObjectName("sum_30")
        self.sum_31 = QtWidgets.QLabel(Form)
        self.sum_31.setGeometry(QtCore.QRect(520, 280, 31, 16))
        self.sum_31.setObjectName("sum_31")
        self.sum_32 = QtWidgets.QLabel(Form)
        self.sum_32.setGeometry(QtCore.QRect(520, 300, 31, 16))
        self.sum_32.setObjectName("sum_32")
        self.sum_33 = QtWidgets.QLabel(Form)
        self.sum_33.setGeometry(QtCore.QRect(520, 320, 31, 16))
        self.sum_33.setObjectName("sum_33")
        self.sum_34 = QtWidgets.QLabel(Form)
        self.sum_34.setGeometry(QtCore.QRect(520, 340, 31, 16))
        self.sum_34.setObjectName("sum_34")
        self.sum_35 = QtWidgets.QLabel(Form)
        self.sum_35.setGeometry(QtCore.QRect(520, 360, 31, 16))
        self.sum_35.setObjectName("sum_35")
        self.sum_36 = QtWidgets.QLabel(Form)
        self.sum_36.setGeometry(QtCore.QRect(520, 380, 31, 16))
        self.sum_36.setObjectName("sum_36")
        self.sum_37 = QtWidgets.QLabel(Form)
        self.sum_37.setGeometry(QtCore.QRect(520, 400, 31, 16))
        self.sum_37.setObjectName("sum_37")
        self.sum_38 = QtWidgets.QLabel(Form)
        self.sum_38.setGeometry(QtCore.QRect(520, 420, 31, 16))
        self.sum_38.setObjectName("sum_38")
        self.sum_39 = QtWidgets.QLabel(Form)
        self.sum_39.setGeometry(QtCore.QRect(520, 440, 31, 16))
        self.sum_39.setObjectName("sum_39")
        self.sum_40 = QtWidgets.QLabel(Form)
        self.sum_40.setGeometry(QtCore.QRect(520, 460, 31, 16))
        self.sum_40.setObjectName("sum_40")
        self.sum_41 = QtWidgets.QLabel(Form)
        self.sum_41.setGeometry(QtCore.QRect(810, 60, 31, 16))
        self.sum_41.setObjectName("sum_41")
        self.sum_42 = QtWidgets.QLabel(Form)
        self.sum_42.setGeometry(QtCore.QRect(810, 80, 31, 16))
        self.sum_42.setObjectName("sum_42")
        self.sum_43 = QtWidgets.QLabel(Form)
        self.sum_43.setGeometry(QtCore.QRect(810, 100, 31, 16))
        self.sum_43.setObjectName("sum_43")
        self.sum_44 = QtWidgets.QLabel(Form)
        self.sum_44.setGeometry(QtCore.QRect(810, 120, 31, 16))
        self.sum_44.setObjectName("sum_44")
        self.sum_45 = QtWidgets.QLabel(Form)
        self.sum_45.setGeometry(QtCore.QRect(810, 140, 31, 16))
        self.sum_45.setObjectName("sum_45")
        self.sum_46 = QtWidgets.QLabel(Form)
        self.sum_46.setGeometry(QtCore.QRect(810, 160, 31, 16))
        self.sum_46.setObjectName("sum_46")
        self.sum_47 = QtWidgets.QLabel(Form)
        self.sum_47.setGeometry(QtCore.QRect(810, 180, 31, 16))
        self.sum_47.setObjectName("sum_47")
        self.sum_48 = QtWidgets.QLabel(Form)
        self.sum_48.setGeometry(QtCore.QRect(810, 200, 31, 16))
        self.sum_48.setObjectName("sum_48")
        self.sum_49 = QtWidgets.QLabel(Form)
        self.sum_49.setGeometry(QtCore.QRect(810, 220, 31, 16))
        self.sum_49.setObjectName("sum_49")
        self.sum_50 = QtWidgets.QLabel(Form)
        self.sum_50.setGeometry(QtCore.QRect(810, 240, 31, 16))
        self.sum_50.setObjectName("sum_50")
        self.sum_51 = QtWidgets.QLabel(Form)
        self.sum_51.setGeometry(QtCore.QRect(810, 260, 31, 16))
        self.sum_51.setObjectName("sum_51")
        self.sum_52 = QtWidgets.QLabel(Form)
        self.sum_52.setGeometry(QtCore.QRect(810, 280, 31, 16))
        self.sum_52.setObjectName("sum_52")
        self.sum_53 = QtWidgets.QLabel(Form)
        self.sum_53.setGeometry(QtCore.QRect(810, 300, 31, 16))
        self.sum_53.setObjectName("sum_53")
        self.sum_54 = QtWidgets.QLabel(Form)
        self.sum_54.setGeometry(QtCore.QRect(810, 320, 31, 16))
        self.sum_54.setObjectName("sum_54")
        self.sum_55 = QtWidgets.QLabel(Form)
        self.sum_55.setGeometry(QtCore.QRect(810, 340, 31, 16))
        self.sum_55.setObjectName("sum_55")
        self.sum_56 = QtWidgets.QLabel(Form)
        self.sum_56.setGeometry(QtCore.QRect(810, 360, 31, 16))
        self.sum_56.setObjectName("sum_56")
        self.sum_57 = QtWidgets.QLabel(Form)
        self.sum_57.setGeometry(QtCore.QRect(810, 380, 31, 16))
        self.sum_57.setObjectName("sum_57")
        self.sum_58 = QtWidgets.QLabel(Form)
        self.sum_58.setGeometry(QtCore.QRect(810, 400, 31, 16))
        self.sum_58.setObjectName("sum_58")
        self.sum_59 = QtWidgets.QLabel(Form)
        self.sum_59.setGeometry(QtCore.QRect(810, 420, 31, 16))
        self.sum_59.setObjectName("sum_59")
        self.sum_60 = QtWidgets.QLabel(Form)
        self.sum_60.setGeometry(QtCore.QRect(810, 440, 31, 16))
        self.sum_60.setObjectName("sum_60")
        self.label_91 = QtWidgets.QLabel(Form)
        self.label_91.setGeometry(QtCore.QRect(520, 60, 31, 16))
        self.label_91.setObjectName("label_91")
        self.label_92 = QtWidgets.QLabel(Form)
        self.label_92.setGeometry(QtCore.QRect(810, 40, 31, 16))
        self.label_92.setObjectName("label_92")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setToolTip(_translate("Form", "<html><head/><body><p>Accounting (05%)</p><p>使你理解会计工作的流程以及一个企业或者个人 的金融职务。通过检查账簿，你可以发现做假账的员工，对资金的偷偷挪用，对行贿或者敲诈的款项支付，以及经济状况是否比表面陈述的更好或者更差。 通过仔细检查旧账户，你可以了解过去的资金的得与失（谷物，奴隶贸易，威士忌酒的运营等）以及这些资金是付给了谁以及为了什么款项而支付。</p></body></html>"))
        self.label.setText(_translate("Form", "会计"))
        self.label_2.setToolTip(_translate("Form", "<html><head/><body><p>Anthropology (01%)</p><p>使使用者能够通过观察来辨认和理解一个人的生活方式。如果技能使用者持续观察一个其他的文化一段时间，或者在有着关于某种已消失文化的正确资料环境下工作，那么他可以对文化方式以及道德习惯进行简单的预测，即使证据可能并不完整。通过学习文化一个月或者更久，人类学家开始理解这种文化是如何运作的以及，如果结合心理学，可以预测那些研究文化的行为和信仰。</p></body></html>"))
        self.label_2.setText(_translate("Form", "人类学"))
        self.label_3.setToolTip(_translate("Form", "<html><head/><body><p>Appraise (05%)</p><p>用来估计某种物品的价值，包括质量，使用的材料以及工艺。相关的，技能使用者可以准确地辨认出物品的年龄，评估它的历史关联性以及发现赝品。</p></body></html>"))
        self.label_3.setText(_translate("Form", "估价"))
        self.label_4.setToolTip(_translate("Form", "<html><head/><body><p>Archaeology (01%)</p><p>允许辨别以及鉴定一件古董，以及用来发现赝品。使调查员获得建立以及开掘一个挖掘遗址的专业知识。推断留下遗址的生物的目的和生活方式。人类学可能对此会有所帮助。考古学还有助于辨认已消失的人类语言的书面形式。</p></body></html>"))
        self.label_4.setText(_translate("Form", "考古学"))
        self.label_5.setToolTip(_translate("Form", "<html><head/><body><p>Art and Craft (05%)</p><p>该技能可能能使你制作/修理一样东西，或者制造一个复制品/赝品。 对一个物品进行一次成功的鉴定可能可以提供关于该物品的相关信息</p></body></html>"))
        self.label_5.setText(_translate("Form", "技艺:"))
        self.label_8.setToolTip(_translate("Form", "<html><head/><body><p>Charm (15%)</p><p>魅惑允许通过许多形式来使用，包括肉体魅力、诱惑、奉承或是单纯的人格魅力。魅惑可能可以被用于迫使某人进行特定的行动。 魅惑或是心理学技能可以用于对抗魅惑技能。 魅惑技能可以被用于讨价还价。</p></body></html>"))
        self.label_8.setText(_translate("Form", "魅惑"))
        self.label_9.setToolTip(_translate("Form", "<html><head/><body><p>Climb (20%)</p><p>这技能允许一名角色借助或者不借助绳索或者登山工具进行爬树、墙以及其他垂直表面。这技能也同样包括用绳索下降。许多因素将会影响难度等级。</p></body></html>"))
        self.label_9.setText(_translate("Form", "攀爬"))
        self.label_10.setToolTip(_translate("Form", "<html><head/><body><p>Computer Use (05%)</p><p>这技能允许调查员用各种不同的电脑语言进行编程；恢复或者分析隐藏的数据；解除被加了保护的系统；探索一个复杂的网络；或者发现别人的骇入、后门程序、病毒。对电脑系统的特殊操作可能会需要这个检定。 仅在现代可用。</p></body></html>"))
        self.label_10.setText(_translate("Form", "计算机使用 Ω"))
        self.label_11.setToolTip(_translate("Form", "<html><head/><body><p>Credit Rating (00%)</p><p>衡量了调查员表现出来的富裕程度以及经济上的自信度。如果调查员尝试用他的经济地位来达成某个目标，那么也许使用信用评级技能会比较合适。信用评级可以被用来取代APP来评估第一印象。 （请将技能提升至调查员职业信用范围之内）</p></body></html>"))
        self.label_11.setText(_translate("Form", "信用评级"))
        self.label_12.setToolTip(_translate("Form", "<html><head/><body><p>Cthulhu Mythos (00%)</p><p>“我认为，人的思维缺乏将已知事物联系起来的能力，这是世上最仁慈的事了。人类居住在幽暗的海洋中一个名为无知的小岛上，这海洋浩淼无垠、蕴藏无穷秘密，但我们并不应该航行过远，探究太深。” ——H·P·爱手艺</p></body></html>"))
        self.label_12.setText(_translate("Form", "克苏鲁神话"))
        self.label_13.setToolTip(_translate("Form", "<html><head/><body><p>Disguise (05%)</p><p>使用在当调查员想要演出自己外的其它人时。使用者改变了态度，习惯，以及/或声音来进行一个乔装，以另一个人或者另一类人的形象出现。戏剧化妆品可能会有所帮助，还有伪造的身份证件。</p></body></html>"))
        self.label_13.setText(_translate("Form", "乔装"))
        self.label_14.setToolTip(_translate("Form", "<html><head/><body><p>Dodge (DEX/2) [无法孤注一骰]</p><p>允许调查员本能地闪避攻击，投掷过来的投射物以及诸如此类的。闪避可以通过经验来提升，就像其他的技能一样。如果一次攻击可以被看见，调查员可以尝试闪避开它。 无法躲避子弹。</p></body></html>"))
        self.label_14.setText(_translate("Form", "闪避"))
        self.label_15.setToolTip(_translate("Form", "<html><head/><body><p>Drive Auto (20%)</p><p>任何有着这技能的人都可以驾驶一辆汽车或者轻型卡车，进行常规的移动，并且处理机动车的一般毛病。如果调查员想要甩掉一名追踪者或者追踪某人，则需要一个汽车驾驶检定。</p></body></html>"))
        self.label_15.setText(_translate("Form", "汽车驾驶"))
        self.label_16.setToolTip(_translate("Form", "<html><head/><body><p>Electrical Repair (10%)</p><p>使调查员能够修理或者改装电气设备。在现代，这技能对现代电子器件几乎做不到什么。为了维修电气设备，可能需要特殊的部件或者工具。也可用于现代的爆破作业。</p></body></html>"))
        self.label_16.setText(_translate("Form", "电气维修"))
        self.label_17.setToolTip(_translate("Form", "<html><head/><body><p>Electronics (01%)</p><p>用来发现并对电子设备的故障进行维修。允许制作简单的电子设备。这是个现代技能—在1920年代则是使用物理学以及电气维修来应对电子设备。 仅在现代可用。</p></body></html>"))
        self.label_17.setText(_translate("Form", "电子学 Ω"))
        self.label_18.setToolTip(_translate("Form", "<html><head/><body><p>Fast Talk (05%) 也译作“快速交谈”</p><p>话术特别限定于言语上的哄骗，欺骗以及误导。这技能的对立技能为心理学或者话术。经过一段时间的相信期后，对方会意识到自己被欺骗了，话术的效果总是暂时性的。也可用于砍价。</p></body></html>"))
        self.label_18.setText(_translate("Form", "话术"))
        self.label_19.setToolTip(_translate("Form", "<html><head/><body><p>Fighting (不定) [无法孤注一骰]</p><p>格斗技能指的是一名角色在近距离战斗上的技能。你可以花费一定的点数来获得任何的专业化技能。</p></body></html>"))
        self.label_19.setText(_translate("Form", "格斗:斗殴"))
        self.label_22.setToolTip(_translate("Form", "<html><head/><body><p>Mechanical Repair (10%)</p><p>这技能允许调查员修理破损的机器或制造一个新的。基础的木工手艺，管道项目，制作物品也同样可以。这技能可以用来打开普通的锁，但更加专业的就不能。机械维修通常与电气维修相伴，修理一个复杂的设备往往两者皆需。</p></body></html>"))
        self.label_22.setText(_translate("Form", "机械维修"))
        self.label_24.setToolTip(_translate("Form", "<html><head/><body><p>Medicine (01%)</p><p>使用者可以诊断并治疗事故创伤，疾病，毒药。提供相关药品的信息。用本技能进行治疗最少要花费1小时，可在造成了伤害后的任何时间进行，但若未在当天进行难度将会上升。成功的医学技能可唤醒一名昏迷的角色。</p></body></html>"))
        self.label_24.setText(_translate("Form", "医学"))
        self.label_26.setToolTip(_translate("Form", "<html><head/><body><p>Jump (20%)</p><p>如果成功，调查员可以在垂直方向上跳起或跳下，或者从一个站立点或起步点水平向外跳。当从高处跌落时，一次成功的跳跃鉴定可以将跌落伤害减半。</p></body></html>"))
        self.label_26.setText(_translate("Form", "跳跃"))
        self.label_28.setToolTip(_translate("Form", "<html><head/><body><p>Listen (20%)</p><p>衡量一名调查员理解声音的能力，包括偶然听到的对话，一扇关着的门后的轻声嘀咕，以及咖啡厅里的私语。 KP可以用这来决定一场即将发生的遭遇的形式。甚至此外，一个较高的聆听技能可以指一名角色有着高度的泛察觉能力</p></body></html>"))
        self.label_28.setText(_translate("Form", "聆听"))
        self.label_29.setToolTip(_translate("Form", "<html><head/><body><p>Library Use (20%)</p><p>图书馆使用使一名调查员能在图书馆找到一些信息，例如特定的一本书，新闻，文件或资料库，但是需要数小时的连续调查。这个技能可以定位寻找一件隐藏案例或一本稀有书籍，但是首先需要获得阅读的许可。</p></body></html>"))
        self.label_29.setText(_translate("Form", "图书馆使用"))
        self.label_30.setToolTip(_translate("Form", "<html><head/><body><p>History (05%)</p><p>让一名调查员能够记住一个国家，城市，区域或者个人及其相关的重要情报。一个成功的检定可以用来帮助辨认先祖所熟悉的工具，科技，或者想法，但是对当下的所知甚少。</p></body></html>"))
        self.label_30.setText(_translate("Form", "历史"))
        self.label_31.setToolTip(_translate("Form", "<html><head/><body><p>First Aid (30%)</p><p>使用者有能力可以提供紧急的医疗处理，唤醒昏迷者。急救不能用于治疗疾病，但是只有急救技能可以拯救一名濒死角色的生命。急救可以由多人共同实施，只需一人成功即可。</p></body></html>"))
        self.label_31.setText(_translate("Form", "急救"))
        self.label_32.setToolTip(_translate("Form", "<html><head/><body><p>Firearms (不定) [无法孤注一骰]</p><p>包括了各种形式的火器，也包括了弓箭和弩。</p></body></html>"))
        self.label_32.setText(_translate("Form", "射击:手枪"))
        self.label_34.setToolTip(_translate("Form", "<html><head/><body><p>Locksmith (01%)</p><p>锁匠技能可以打开车门，热线自动装置，用铁撬撬开窗子，解决中国机关箱，以及穿过常规的商用警报系统。使用者可能会修锁，制作钥匙，或者在其他工具的帮助下打开锁。特别困难的锁可能会需要一个更高的难度等级。</p></body></html>"))
        self.label_34.setText(_translate("Form", "锁匠"))
        self.label_36.setToolTip(_translate("Form", "<html><head/><body><p>Navigate (10%)</p><p>允许使用者认清自己的路。有着更高技能的人将熟悉各种定位装置。一名角色可以用这技能来测量并对某区域进行绘图（制图学），使用工具可以降低甚至取消难度等级。若角色对某区域十分熟悉，那么在检定上可以得到奖励。</p></body></html>"))
        self.label_36.setText(_translate("Form", "导航"))
        self.label_37.setToolTip(_translate("Form", "<html><head/><body><p>Natural World (10%)</p><p>指对于自然环境中的植物和动物生命的研究。它可以对物种，栖息地进行辨认，并能辨认踪迹、足迹和叫声，也允许对什么事物可能对某种特定物种来说很重要进行猜测。自然学可能准确也可能不准确。</p></body></html>"))
        self.label_37.setText(_translate("Form", "自然学"))
        self.label_38.setToolTip(_translate("Form", "<html><head/><body><p>Law (05%)</p><p>代表你对法律、早期事件、法庭辩术或法院程序的了解。一个法律专家可能会获得奖励以及事务所，但这可能需要几年的申请和一个较高的信用评级。在国外时，技能的难度等级相应上升，除非该角色花费时间学习该国的法律。</p></body></html>"))
        self.label_38.setText(_translate("Form", "法律"))
        self.label_40.setToolTip(_translate("Form", "<html><head/><body><p>Intimidate (15%)</p><p>恐吓可以以许多形式使用，包括武力威慑，心理操控，以及威胁。这通常被用来使某人害怕，并迫使其进行某种特定的行为。恐吓的对抗技能为恐吓或者心理学。同样也能拿来砍价。</p></body></html>"))
        self.label_40.setText(_translate("Form", "恐吓"))
        self.label_42.setToolTip(_translate("Form", "<html><head/><body><p>Throw (20%)</p><p>当需要用物体击中目标或者用物件的正确部分击中目标（例如小刀或者短柄小斧的刃）时，使用投掷技能。一件有着合理平衡构架的可以藏于手中大小的物品可以被投掷至多等同于 STR码的距离。</p></body></html>"))
        self.label_42.setText(_translate("Form", "投掷"))
        self.label_43.setToolTip(_translate("Form", "<html><head/><body><p>Sleight of Hand (10%)</p><p>允许对物体进行视觉上的遮住，藏匿，或者掩盖，也许通过残害，衣服或者其他的干涉或促成错觉的材料。任何种类的巨大物件应当增加藏匿的难度。妙手包括偷窃，卡牌魔术，以及秘密使用手机。</p></body></html>"))
        self.label_43.setText(_translate("Form", "妙手"))
        self.label_44.setToolTip(_translate("Form", "<html><head/><body><p>Track (10%)</p><p>使调查员可以凭借追踪技能来通过土壤上的脚印，或是物体通过植被时留下的印记来追踪别人，或者是交通工具以及地球上的动物。时间的经过，雨，以及土地的种类都可能会影响追踪的难度等级。</p></body></html>"))
        self.label_44.setText(_translate("Form", "追踪"))
        self.label_47.setToolTip(_translate("Form", "<html><head/><body><p>Spot Hidden (25%)</p><p>这技能允许使用者发现密门或者秘密隔间，注意到隐藏的闯入者，发现并不明显的线索，发现重新涂过漆的汽车，意识到埋伏，注意到鼓出的口袋，或者任何类似的事情。对于调查员来说，这是一个很重要的技能。</p></body></html>"))
        self.label_47.setText(_translate("Form", "侦察"))
        self.label_50.setToolTip(_translate("Form", "<html><head/><body><p>Psychology (10%)</p><p>对所有人来说都很通用的察觉方面的技能，允许使用者研究个人并且形成对于其他某人动机和人格的了解。在玩家的支持下，KP可能会选择进行一个心理学技能检定的暗骰，仅仅对使用这个技能的玩家声明获得的信息，真或假。</p></body></html>"))
        self.label_50.setText(_translate("Form", "心理学"))
        self.label_51.setToolTip(_translate("Form", "<html><head/><body><p>Psychoanalysis (01%)</p><p>这技能指广泛的情感上的治疗。精神分析可以恢复一名调查员的理智。单独的精神分析并不能加速不定时疯狂的恢复，但允许一名角色处理他人短期内的恐惧症状。心理治疗专家的治疗可以在不定式疯狂期间内回复理智。</p></body></html>"))
        self.label_51.setText(_translate("Form", "精神分析"))
        self.label_52.setToolTip(_translate("Form", "<html><head/><body><p>Operate Heavy Machinery (01%)</p><p>当驾驶以及操纵一辆坦克，挖土机或者其他巨型建造机械时需要这个技能。对于种类非常不同的机械，KP可以决定难度等级。</p></body></html>"))
        self.label_52.setText(_translate("Form", "操作重型机械"))
        self.label_53.setToolTip(_translate("Form", "<html><head/><body><p>Persuade (10%)</p><p>使用说服来通过一场论述、争辩以及讨论让目标相信一个确切的想法，概念，或者信仰。说服并不一定需要涉及真实的内容。成功的说服技能的运用将花费不少的时间：至少半小时。另外说服还可以被用于讨价还价。</p></body></html>"))
        self.label_53.setText(_translate("Form", "说服"))
        self.label_54.setToolTip(_translate("Form", "<html><head/><body><p>Swim (20%)</p><p>有能力在水或者其他液体中漂浮以及移动。只有在遭遇危险时需要进行游泳技能检定，或当 KP认为合适的时候。当游泳的孤注一骰失败时，可能会导致生命值损失。也可能导致人物顺着水流向下冲走，被水半淹或完全淹没。</p></body></html>"))
        self.label_54.setText(_translate("Form", "游泳"))
        self.label_58.setToolTip(_translate("Form", "<html><head/><body><p>Stealth (20%)</p><p>安静地移动或躲藏的技巧，不惊扰那些可能在听或看的人们。与这项技能相关的能力意味着角色能够安静地移动或在伪装技巧上有所长。潜行也同样意味着角色可以长时间维持一定程度的谨慎冷静来使自己保持静止和隐秘。</p></body></html>"))
        self.label_58.setText(_translate("Form", "潜行"))
        self.label_59.setToolTip(_translate("Form", "<html><head/><body><p>Occult (05%)</p><p>使用者可以识别神秘学道具，用语和概念，以及民间传统，并且可以辨认魔法书以及神秘学记号。理解特定的书籍可能可以增加神秘学技能的百分比。这技能不能运用于与克苏鲁神话相关的咒术，书本，以及魔法。</p></body></html>"))
        self.label_59.setText(_translate("Form", "神秘学"))
        self.label_60.setToolTip(_translate("Form", "<html><head/><body><p>Ride (05%)</p><p>这技能被用于驾驭马，驴子或者骡子，以及获得对这些骑乘动物的基础照料知识，如何在疾驰中或困难地形上操纵坐骑。当坐骑意外地抬起身子或失足时，骑手保持自己在坐骑上不摔落的几率等同于他的骑术技能。</p></body></html>"))
        self.label_60.setText(_translate("Form", "骑术"))
        self.next_step.setText(_translate("Form", "下一步"))
        self.label_6.setToolTip(_translate("Form", "<html><head/><body><p>Art and Craft (05%)</p><p>该技能可能能使你制作/修理一样东西，或者制造一个复制品/赝品。 对一个物品进行一次成功的鉴定可能可以提供关于该物品的相关信息</p></body></html>"))
        self.label_6.setText(_translate("Form", "技艺:"))
        self.label_7.setToolTip(_translate("Form", "<html><head/><body><p>Art and Craft (05%)</p><p>该技能可能能使你制作/修理一样东西，或者制造一个复制品/赝品。 对一个物品进行一次成功的鉴定可能可以提供关于该物品的相关信息</p></body></html>"))
        self.label_7.setText(_translate("Form", "技艺:"))
        self.label_20.setToolTip(_translate("Form", "<html><head/><body><p>Fighting (不定) [无法孤注一骰]</p><p>格斗技能指的是一名角色在近距离战斗上的技能。你可以花费一定的点数来获得任何的专业化技能。</p></body></html>"))
        self.label_20.setText(_translate("Form", "格斗:"))
        self.label_25.setToolTip(_translate("Form", "<html><head/><body><p>Fighting (不定) [无法孤注一骰]</p><p>格斗技能指的是一名角色在近距离战斗上的技能。你可以花费一定的点数来获得任何的专业化技能。</p></body></html>"))
        self.label_25.setText(_translate("Form", "格斗:"))
        self.label_33.setToolTip(_translate("Form", "<html><head/><body><p>Firearms (不定) [无法孤注一骰]</p><p>包括了各种形式的火器，也包括了弓箭和弩。</p></body></html>"))
        self.label_33.setText(_translate("Form", "射击:"))
        self.label_39.setToolTip(_translate("Form", "<html><head/><body><p>Firearms (不定) [无法孤注一骰]</p><p>包括了各种形式的火器，也包括了弓箭和弩。</p></body></html>"))
        self.label_39.setText(_translate("Form", "射击:"))
        self.label_21.setToolTip(_translate("Form", "<html><head/><body><p>Language (Other)[01%]</p><p>当选择这项技能时，必须明确一个具体的语言并且写在技能后面。一个人可以了解任何数量的语言。这技能代表使用者可以了解，说，读以及写一门不是他母语的语言的可能性。</p></body></html>"))
        self.label_21.setText(_translate("Form", "语言:"))
        self.label_23.setToolTip(_translate("Form", "<html><head/><body><p>Language (Other)[01%]</p><p>当选择这项技能时，必须明确一个具体的语言并且写在技能后面。一个人可以了解任何数量的语言。这技能代表使用者可以了解，说，读以及写一门不是他母语的语言的可能性。</p></body></html>"))
        self.label_23.setText(_translate("Form", "语言:"))
        self.label_27.setToolTip(_translate("Form", "<html><head/><body><p>Language (Other)[01%]</p><p>当选择这项技能时，必须明确一个具体的语言并且写在技能后面。一个人可以了解任何数量的语言。这技能代表使用者可以了解，说，读以及写一门不是他母语的语言的可能性。</p></body></html>"))
        self.label_27.setText(_translate("Form", "语言:"))
        self.label_35.setToolTip(_translate("Form", "<html><head/><body><p>Language (Own) (EDU)</p><p>当选择这项技能时，必须明确一门具体的语言并且写在技能的后面。在婴儿期或者童年早期，大多数人使用单一一门语言。</p></body></html>"))
        self.label_35.setText(_translate("Form", "母语:"))
        self.label_45.setToolTip(_translate("Form", "<html><head/><body><p>Pilot (01%)</p><p>这是操控飞行器或船只的技能，汽车驾驶在左侧躲闪和电器维修之间。 驾驶（飞行器）：了解并能够日益掌握下方指出的一类飞行器。着陆时，就算在最佳的状况，也必须进行驾驶掷骰。失败的结果视情况而定。 驾驶（船）：了解小型马达船和帆船在风中、暴风雨中、海潮中的各种行为，并可以从波浪与风的表现中读出暗礁及迫近的暴风雨。在风中，新水手连停艘小船都是困难的。</p></body></html>"))
        self.label_45.setText(_translate("Form", "驾驶:"))
        self.label_41.setToolTip(_translate("Form", "<html><head/><body><p>Science (01%)</p><p>科学专业上的理论和实践的能力，拥有这个技能的人接受过一定程度的正式的教育或者训练。对于知识的理解和认识受到时代的限制。你可以花费点数来获得任何你想要的专业技能，每个专业化技能包括了一门专门的学科。</p></body></html>"))
        self.label_41.setText(_translate("Form", "科学:"))
        self.label_46.setToolTip(_translate("Form", "<html><head/><body><p>Science (01%)</p><p>科学专业上的理论和实践的能力，拥有这个技能的人接受过一定程度的正式的教育或者训练。对于知识的理解和认识受到时代的限制。你可以花费点数来获得任何你想要的专业技能，每个专业化技能包括了一门专门的学科。</p></body></html>"))
        self.label_46.setText(_translate("Form", "科学:"))
        self.label_55.setToolTip(_translate("Form", "<html><head/><body><p>Science (01%)</p><p>科学专业上的理论和实践的能力，拥有这个技能的人接受过一定程度的正式的教育或者训练。对于知识的理解和认识受到时代的限制。你可以花费点数来获得任何你想要的专业技能，每个专业化技能包括了一门专门的学科。</p></body></html>"))
        self.label_55.setText(_translate("Form", "科学:"))
        self.label_48.setToolTip(_translate("Form", "<html><head/><body><p>Survival (10%)</p><p>提供专业的如何在极端环境下生存的知识和技巧。内容包括狩猎的知识，搭建住所，可能遇到的危险的知识（例如如何避开有毒性的植物）等等，取决于所处的环境。你可以花费技能点来获得任何的专业化技能。</p></body></html>"))
        self.label_48.setText(_translate("Form", "生存:"))
        self.label_49.setToolTip(_translate("Form", "<html><head/><body><p>Survival (10%)</p><p>提供专业的如何在极端环境下生存的知识和技巧。内容包括狩猎的知识，搭建住所，可能遇到的危险的知识（例如如何避开有毒性的植物）等等，取决于所处的环境。你可以花费技能点来获得任何的专业化技能。</p></body></html>"))
        self.label_49.setText(_translate("Form", "生存:"))
        self.label_56.setToolTip(_translate("Form", "<html><head/><body><p>爆破:</p><p>Demolitions (01%)</p><p>调查员可以使用此技能安全的设置/拆除爆破装置。给予足够的时间和资源，调查员可以装设炸药来摧毁一幢建筑，清除一个被堵住的隧道，以及赋予炸药不同用处。</p><p>催眠:</p><p>Hypnosis (01%)</p><p>调查员可以在一名自愿并经历过高度暗示、放松的目标身上引出出神似的状态，并且可能回忆起忘却的记忆。对那些遭受了精神创伤的人，这技能可以当做催眠疗法来使用，减轻一名病人的恐惧或者躁狂。</p><p>读唇:</p><p>Read Lips (01%)</p><p>这个技能允许调查员不需要听到说话者的声音，就能知道他们的对话内容。必须保持视线，如果只看到一个说话者的嘴唇，对话的另外一半就听不到。 读唇也可以用于与另一个人进行安静沟通（如果两人都有此技能），允许相对复杂的语意传达。</p><p>炮术:</p><p>Artillery (01%)</p><p>这技能呈现出对一些形式的军事训练和经历。使用者具有在战争中操作战地武器的经验。这些武器通常过于巨大以至于无法单人进行操作，并且个人无法再没有工作队支援的情况下使用这武器，或者应当提高难度等级。</p><p>潜水:</p><p>Diving (01%)</p><p>使用者接受过在深海游泳的使用以及维持潜水设备的训练，水下导航，合适的下潜配重，以及应对紧急情况的方法。</p><p>驯兽:</p><p>Animal Handling (05%)</p><p>命令以及训练已驯化动物去完成一些简单任务的技能。这个技能最常用于狗上，但也包括鸟、猫、猴子以及其他（取决于KP的判断）。至于对动物的骑乘，例如马或者骆驼，则要用骑术技能来进行行动以及操控这些坐骑。</p></body></html>"))
        self.label_56.setText(_translate("Form", "罕见:"))
        self.label_57.setToolTip(_translate("Form", "<html><head/><body><p>学问(01%)(专业化)[非常规]</p><p>这项技能代表对一个超出人类常规知识范畴的事物的专业理解。 当KP想要测试某位调查员归属于这些领域学问其中之一的某物的知识时，但是调查员缺少相关的专业学问，KP可以允许一个其他更通用技能的使用，但是需要一个更高难度等级的成功。</p></body></html>"))
        self.label_57.setText(_translate("Form", "学问:"))
        self.sub_skill5.setText(_translate("Form", "TextLabel"))
        self.sub_skill6.setText(_translate("Form", "TextLabel"))
        self.sub_skill7.setText(_translate("Form", "TextLabel"))
        self.sub_skill20.setText(_translate("Form", "TextLabel"))
        self.sub_skill21.setText(_translate("Form", "TextLabel"))
        self.sub_skill23.setText(_translate("Form", "TextLabel"))
        self.sub_skill24.setText(_translate("Form", "TextLabel"))
        self.sub_skill29.setText(_translate("Form", "TextLabel"))
        self.sub_skill30.setText(_translate("Form", "TextLabel"))
        self.sub_skill31.setText(_translate("Form", "TextLabel"))
        self.sub_skill32.setText(_translate("Form", "TextLabel"))
        self.sub_skill44.setText(_translate("Form", "TextLabel"))
        self.sub_skill49.setText(_translate("Form", "TextLabel"))
        self.sub_skill50.setText(_translate("Form", "TextLabel"))
        self.sub_skill54.setText(_translate("Form", "TextLabel"))
        self.sub_skill55.setText(_translate("Form", "TextLabel"))
        self.sub_skill59.setText(_translate("Form", "TextLabel"))
        self.sub_skill60.setText(_translate("Form", "TextLabel"))
        self.label_80.setText(_translate("Form", "请分配技能点"))
        self.label_81.setText(_translate("Form", "职业"))
        self.label_82.setText(_translate("Form", "兴趣"))
        self.label_83.setText(_translate("Form", "职业"))
        self.label_84.setText(_translate("Form", "兴趣"))
        self.label_85.setText(_translate("Form", "职业"))
        self.label_86.setText(_translate("Form", "兴趣"))
        self.label_87.setText(_translate("Form", "剩余职业技能点："))
        self.professional_points.setText(_translate("Form", "###"))
        self.label_89.setText(_translate("Form", "剩余兴趣技能点："))
        self.interest_points.setText(_translate("Form", "###"))
        self.sub_skill48.setText(_translate("Form", "TextLabel"))
        self.label_88.setText(_translate("Form", "职业信用范围："))
        self.min_credit.setText(_translate("Form", "###"))
        self.max_credit.setText(_translate("Form", "###"))
        self.professional_points_4.setText(_translate("Form", "-"))
        self.label_90.setText(_translate("Form", "总和"))
        self.sum_1.setText(_translate("Form", "###"))
        self.sum_2.setText(_translate("Form", "###"))
        self.sum_3.setText(_translate("Form", "###"))
        self.sum_4.setText(_translate("Form", "###"))
        self.sum_5.setText(_translate("Form", "###"))
        self.sum_6.setText(_translate("Form", "###"))
        self.sum_7.setText(_translate("Form", "###"))
        self.sum_8.setText(_translate("Form", "###"))
        self.sum_9.setText(_translate("Form", "###"))
        self.sum_10.setText(_translate("Form", "###"))
        self.sum_11.setText(_translate("Form", "###"))
        self.sum_12.setText(_translate("Form", "###"))
        self.sum_13.setText(_translate("Form", "###"))
        self.sum_14.setText(_translate("Form", "###"))
        self.sum_15.setText(_translate("Form", "###"))
        self.sum_16.setText(_translate("Form", "###"))
        self.sum_17.setText(_translate("Form", "###"))
        self.sum_18.setText(_translate("Form", "###"))
        self.sum_19.setText(_translate("Form", "###"))
        self.sum_20.setText(_translate("Form", "###"))
        self.sum_21.setText(_translate("Form", "###"))
        self.sum_22.setText(_translate("Form", "###"))
        self.sum_23.setText(_translate("Form", "###"))
        self.sum_24.setText(_translate("Form", "###"))
        self.sum_25.setText(_translate("Form", "###"))
        self.sum_26.setText(_translate("Form", "###"))
        self.sum_27.setText(_translate("Form", "###"))
        self.sum_28.setText(_translate("Form", "###"))
        self.sum_29.setText(_translate("Form", "###"))
        self.sum_30.setText(_translate("Form", "###"))
        self.sum_31.setText(_translate("Form", "###"))
        self.sum_32.setText(_translate("Form", "###"))
        self.sum_33.setText(_translate("Form", "###"))
        self.sum_34.setText(_translate("Form", "###"))
        self.sum_35.setText(_translate("Form", "###"))
        self.sum_36.setText(_translate("Form", "###"))
        self.sum_37.setText(_translate("Form", "###"))
        self.sum_38.setText(_translate("Form", "###"))
        self.sum_39.setText(_translate("Form", "###"))
        self.sum_40.setText(_translate("Form", "###"))
        self.sum_41.setText(_translate("Form", "###"))
        self.sum_42.setText(_translate("Form", "###"))
        self.sum_43.setText(_translate("Form", "###"))
        self.sum_44.setText(_translate("Form", "###"))
        self.sum_45.setText(_translate("Form", "###"))
        self.sum_46.setText(_translate("Form", "###"))
        self.sum_47.setText(_translate("Form", "###"))
        self.sum_48.setText(_translate("Form", "###"))
        self.sum_49.setText(_translate("Form", "###"))
        self.sum_50.setText(_translate("Form", "###"))
        self.sum_51.setText(_translate("Form", "###"))
        self.sum_52.setText(_translate("Form", "###"))
        self.sum_53.setText(_translate("Form", "###"))
        self.sum_54.setText(_translate("Form", "###"))
        self.sum_55.setText(_translate("Form", "###"))
        self.sum_56.setText(_translate("Form", "###"))
        self.sum_57.setText(_translate("Form", "###"))
        self.sum_58.setText(_translate("Form", "###"))
        self.sum_59.setText(_translate("Form", "###"))
        self.sum_60.setText(_translate("Form", "###"))
        self.label_91.setText(_translate("Form", "总和"))
        self.label_92.setText(_translate("Form", "总和"))
