# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddSkillPoints_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(679, 455)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 50, 54, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 54, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 54, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 54, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 31, 16))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(10, 190, 54, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(10, 210, 54, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(10, 230, 54, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(10, 250, 54, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(10, 270, 54, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(10, 290, 54, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(10, 310, 54, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(10, 330, 54, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(10, 350, 54, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(10, 370, 54, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(10, 390, 54, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(10, 410, 54, 16))
        self.label_19.setObjectName("label_19")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(230, 370, 54, 16))
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(230, 390, 54, 16))
        self.label_24.setObjectName("label_24")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(230, 190, 54, 16))
        self.label_26.setObjectName("label_26")
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setGeometry(QtCore.QRect(230, 330, 54, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setGeometry(QtCore.QRect(230, 310, 54, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setGeometry(QtCore.QRect(230, 150, 54, 16))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setGeometry(QtCore.QRect(230, 130, 54, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(Form)
        self.label_32.setGeometry(QtCore.QRect(230, 70, 54, 16))
        self.label_32.setObjectName("label_32")
        self.label_34 = QtWidgets.QLabel(Form)
        self.label_34.setGeometry(QtCore.QRect(230, 350, 54, 16))
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(Form)
        self.label_36.setGeometry(QtCore.QRect(230, 430, 54, 16))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(Form)
        self.label_37.setGeometry(QtCore.QRect(230, 410, 54, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(Form)
        self.label_38.setGeometry(QtCore.QRect(230, 290, 54, 16))
        self.label_38.setObjectName("label_38")
        self.label_40 = QtWidgets.QLabel(Form)
        self.label_40.setGeometry(QtCore.QRect(230, 170, 54, 16))
        self.label_40.setObjectName("label_40")
        self.label_42 = QtWidgets.QLabel(Form)
        self.label_42.setGeometry(QtCore.QRect(460, 350, 54, 16))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(Form)
        self.label_43.setGeometry(QtCore.QRect(460, 230, 54, 16))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(Form)
        self.label_44.setGeometry(QtCore.QRect(460, 370, 54, 16))
        self.label_44.setObjectName("label_44")
        self.label_47 = QtWidgets.QLabel(Form)
        self.label_47.setGeometry(QtCore.QRect(460, 250, 54, 16))
        self.label_47.setObjectName("label_47")
        self.label_50 = QtWidgets.QLabel(Form)
        self.label_50.setGeometry(QtCore.QRect(460, 130, 54, 16))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(Form)
        self.label_51.setGeometry(QtCore.QRect(460, 110, 54, 16))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(Form)
        self.label_52.setGeometry(QtCore.QRect(460, 50, 54, 16))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(Form)
        self.label_53.setGeometry(QtCore.QRect(460, 70, 54, 16))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(Form)
        self.label_54.setGeometry(QtCore.QRect(460, 330, 54, 16))
        self.label_54.setObjectName("label_54")
        self.label_58 = QtWidgets.QLabel(Form)
        self.label_58.setGeometry(QtCore.QRect(460, 270, 54, 16))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(Form)
        self.label_59.setGeometry(QtCore.QRect(460, 30, 54, 16))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(Form)
        self.label_60.setGeometry(QtCore.QRect(460, 150, 54, 16))
        self.label_60.setObjectName("label_60")
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(140, 50, 42, 16))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(Form)
        self.spinBox_2.setGeometry(QtCore.QRect(180, 50, 42, 16))
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(Form)
        self.spinBox_3.setGeometry(QtCore.QRect(140, 70, 42, 16))
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_4 = QtWidgets.QSpinBox(Form)
        self.spinBox_4.setGeometry(QtCore.QRect(180, 70, 42, 16))
        self.spinBox_4.setObjectName("spinBox_4")
        self.spinBox_5 = QtWidgets.QSpinBox(Form)
        self.spinBox_5.setGeometry(QtCore.QRect(140, 90, 42, 16))
        self.spinBox_5.setObjectName("spinBox_5")
        self.spinBox_6 = QtWidgets.QSpinBox(Form)
        self.spinBox_6.setGeometry(QtCore.QRect(180, 90, 42, 16))
        self.spinBox_6.setObjectName("spinBox_6")
        self.spinBox_7 = QtWidgets.QSpinBox(Form)
        self.spinBox_7.setGeometry(QtCore.QRect(140, 110, 42, 16))
        self.spinBox_7.setObjectName("spinBox_7")
        self.spinBox_8 = QtWidgets.QSpinBox(Form)
        self.spinBox_8.setGeometry(QtCore.QRect(180, 110, 42, 16))
        self.spinBox_8.setObjectName("spinBox_8")
        self.spinBox_9 = QtWidgets.QSpinBox(Form)
        self.spinBox_9.setGeometry(QtCore.QRect(140, 130, 42, 16))
        self.spinBox_9.setObjectName("spinBox_9")
        self.spinBox_10 = QtWidgets.QSpinBox(Form)
        self.spinBox_10.setGeometry(QtCore.QRect(180, 130, 42, 16))
        self.spinBox_10.setObjectName("spinBox_10")
        self.spinBox_11 = QtWidgets.QSpinBox(Form)
        self.spinBox_11.setGeometry(QtCore.QRect(140, 150, 42, 16))
        self.spinBox_11.setObjectName("spinBox_11")
        self.spinBox_12 = QtWidgets.QSpinBox(Form)
        self.spinBox_12.setGeometry(QtCore.QRect(180, 150, 42, 16))
        self.spinBox_12.setObjectName("spinBox_12")
        self.spinBox_13 = QtWidgets.QSpinBox(Form)
        self.spinBox_13.setGeometry(QtCore.QRect(140, 170, 42, 16))
        self.spinBox_13.setObjectName("spinBox_13")
        self.spinBox_14 = QtWidgets.QSpinBox(Form)
        self.spinBox_14.setGeometry(QtCore.QRect(180, 170, 42, 16))
        self.spinBox_14.setObjectName("spinBox_14")
        self.spinBox_15 = QtWidgets.QSpinBox(Form)
        self.spinBox_15.setGeometry(QtCore.QRect(140, 190, 42, 16))
        self.spinBox_15.setObjectName("spinBox_15")
        self.spinBox_16 = QtWidgets.QSpinBox(Form)
        self.spinBox_16.setGeometry(QtCore.QRect(180, 190, 42, 16))
        self.spinBox_16.setObjectName("spinBox_16")
        self.spinBox_17 = QtWidgets.QSpinBox(Form)
        self.spinBox_17.setGeometry(QtCore.QRect(140, 210, 42, 16))
        self.spinBox_17.setObjectName("spinBox_17")
        self.spinBox_18 = QtWidgets.QSpinBox(Form)
        self.spinBox_18.setGeometry(QtCore.QRect(180, 210, 42, 16))
        self.spinBox_18.setObjectName("spinBox_18")
        self.spinBox_19 = QtWidgets.QSpinBox(Form)
        self.spinBox_19.setGeometry(QtCore.QRect(140, 230, 42, 16))
        self.spinBox_19.setObjectName("spinBox_19")
        self.spinBox_20 = QtWidgets.QSpinBox(Form)
        self.spinBox_20.setGeometry(QtCore.QRect(180, 230, 42, 16))
        self.spinBox_20.setObjectName("spinBox_20")
        self.spinBox_21 = QtWidgets.QSpinBox(Form)
        self.spinBox_21.setGeometry(QtCore.QRect(140, 250, 42, 16))
        self.spinBox_21.setObjectName("spinBox_21")
        self.spinBox_22 = QtWidgets.QSpinBox(Form)
        self.spinBox_22.setGeometry(QtCore.QRect(180, 250, 42, 16))
        self.spinBox_22.setObjectName("spinBox_22")
        self.spinBox_23 = QtWidgets.QSpinBox(Form)
        self.spinBox_23.setGeometry(QtCore.QRect(140, 270, 42, 16))
        self.spinBox_23.setObjectName("spinBox_23")
        self.spinBox_24 = QtWidgets.QSpinBox(Form)
        self.spinBox_24.setGeometry(QtCore.QRect(180, 270, 42, 16))
        self.spinBox_24.setObjectName("spinBox_24")
        self.spinBox_25 = QtWidgets.QSpinBox(Form)
        self.spinBox_25.setGeometry(QtCore.QRect(140, 290, 42, 16))
        self.spinBox_25.setObjectName("spinBox_25")
        self.spinBox_26 = QtWidgets.QSpinBox(Form)
        self.spinBox_26.setGeometry(QtCore.QRect(180, 290, 42, 16))
        self.spinBox_26.setObjectName("spinBox_26")
        self.spinBox_27 = QtWidgets.QSpinBox(Form)
        self.spinBox_27.setGeometry(QtCore.QRect(140, 310, 42, 16))
        self.spinBox_27.setObjectName("spinBox_27")
        self.spinBox_28 = QtWidgets.QSpinBox(Form)
        self.spinBox_28.setGeometry(QtCore.QRect(180, 310, 42, 16))
        self.spinBox_28.setObjectName("spinBox_28")
        self.spinBox_29 = QtWidgets.QSpinBox(Form)
        self.spinBox_29.setGeometry(QtCore.QRect(140, 330, 42, 16))
        self.spinBox_29.setObjectName("spinBox_29")
        self.spinBox_30 = QtWidgets.QSpinBox(Form)
        self.spinBox_30.setGeometry(QtCore.QRect(180, 330, 42, 16))
        self.spinBox_30.setObjectName("spinBox_30")
        self.spinBox_31 = QtWidgets.QSpinBox(Form)
        self.spinBox_31.setGeometry(QtCore.QRect(140, 350, 42, 16))
        self.spinBox_31.setObjectName("spinBox_31")
        self.spinBox_32 = QtWidgets.QSpinBox(Form)
        self.spinBox_32.setGeometry(QtCore.QRect(180, 350, 42, 16))
        self.spinBox_32.setObjectName("spinBox_32")
        self.spinBox_33 = QtWidgets.QSpinBox(Form)
        self.spinBox_33.setGeometry(QtCore.QRect(140, 370, 42, 16))
        self.spinBox_33.setObjectName("spinBox_33")
        self.spinBox_34 = QtWidgets.QSpinBox(Form)
        self.spinBox_34.setGeometry(QtCore.QRect(180, 370, 42, 16))
        self.spinBox_34.setObjectName("spinBox_34")
        self.spinBox_35 = QtWidgets.QSpinBox(Form)
        self.spinBox_35.setGeometry(QtCore.QRect(140, 390, 42, 16))
        self.spinBox_35.setObjectName("spinBox_35")
        self.spinBox_36 = QtWidgets.QSpinBox(Form)
        self.spinBox_36.setGeometry(QtCore.QRect(180, 390, 42, 16))
        self.spinBox_36.setObjectName("spinBox_36")
        self.spinBox_37 = QtWidgets.QSpinBox(Form)
        self.spinBox_37.setGeometry(QtCore.QRect(140, 410, 42, 16))
        self.spinBox_37.setObjectName("spinBox_37")
        self.spinBox_38 = QtWidgets.QSpinBox(Form)
        self.spinBox_38.setGeometry(QtCore.QRect(180, 410, 42, 16))
        self.spinBox_38.setObjectName("spinBox_38")
        self.spinBox_39 = QtWidgets.QSpinBox(Form)
        self.spinBox_39.setGeometry(QtCore.QRect(140, 430, 42, 16))
        self.spinBox_39.setObjectName("spinBox_39")
        self.spinBox_40 = QtWidgets.QSpinBox(Form)
        self.spinBox_40.setGeometry(QtCore.QRect(180, 430, 42, 16))
        self.spinBox_40.setObjectName("spinBox_40")
        self.spinBox_41 = QtWidgets.QSpinBox(Form)
        self.spinBox_41.setGeometry(QtCore.QRect(370, 410, 42, 16))
        self.spinBox_41.setObjectName("spinBox_41")
        self.spinBox_42 = QtWidgets.QSpinBox(Form)
        self.spinBox_42.setGeometry(QtCore.QRect(370, 330, 42, 16))
        self.spinBox_42.setObjectName("spinBox_42")
        self.spinBox_43 = QtWidgets.QSpinBox(Form)
        self.spinBox_43.setGeometry(QtCore.QRect(410, 410, 42, 16))
        self.spinBox_43.setObjectName("spinBox_43")
        self.spinBox_44 = QtWidgets.QSpinBox(Form)
        self.spinBox_44.setGeometry(QtCore.QRect(410, 70, 42, 16))
        self.spinBox_44.setObjectName("spinBox_44")
        self.spinBox_45 = QtWidgets.QSpinBox(Form)
        self.spinBox_45.setGeometry(QtCore.QRect(370, 210, 42, 16))
        self.spinBox_45.setObjectName("spinBox_45")
        self.spinBox_46 = QtWidgets.QSpinBox(Form)
        self.spinBox_46.setGeometry(QtCore.QRect(370, 270, 42, 16))
        self.spinBox_46.setObjectName("spinBox_46")
        self.spinBox_47 = QtWidgets.QSpinBox(Form)
        self.spinBox_47.setGeometry(QtCore.QRect(370, 250, 42, 16))
        self.spinBox_47.setObjectName("spinBox_47")
        self.spinBox_48 = QtWidgets.QSpinBox(Form)
        self.spinBox_48.setGeometry(QtCore.QRect(410, 370, 42, 16))
        self.spinBox_48.setObjectName("spinBox_48")
        self.spinBox_49 = QtWidgets.QSpinBox(Form)
        self.spinBox_49.setGeometry(QtCore.QRect(370, 170, 42, 16))
        self.spinBox_49.setObjectName("spinBox_49")
        self.spinBox_50 = QtWidgets.QSpinBox(Form)
        self.spinBox_50.setGeometry(QtCore.QRect(370, 190, 42, 16))
        self.spinBox_50.setObjectName("spinBox_50")
        self.spinBox_51 = QtWidgets.QSpinBox(Form)
        self.spinBox_51.setGeometry(QtCore.QRect(370, 50, 42, 16))
        self.spinBox_51.setObjectName("spinBox_51")
        self.spinBox_52 = QtWidgets.QSpinBox(Form)
        self.spinBox_52.setGeometry(QtCore.QRect(370, 350, 42, 16))
        self.spinBox_52.setObjectName("spinBox_52")
        self.spinBox_53 = QtWidgets.QSpinBox(Form)
        self.spinBox_53.setGeometry(QtCore.QRect(410, 350, 42, 16))
        self.spinBox_53.setObjectName("spinBox_53")
        self.spinBox_54 = QtWidgets.QSpinBox(Form)
        self.spinBox_54.setGeometry(QtCore.QRect(410, 210, 42, 16))
        self.spinBox_54.setObjectName("spinBox_54")
        self.spinBox_55 = QtWidgets.QSpinBox(Form)
        self.spinBox_55.setGeometry(QtCore.QRect(370, 110, 42, 16))
        self.spinBox_55.setObjectName("spinBox_55")
        self.spinBox_56 = QtWidgets.QSpinBox(Form)
        self.spinBox_56.setGeometry(QtCore.QRect(370, 370, 42, 16))
        self.spinBox_56.setObjectName("spinBox_56")
        self.spinBox_57 = QtWidgets.QSpinBox(Form)
        self.spinBox_57.setGeometry(QtCore.QRect(410, 430, 42, 16))
        self.spinBox_57.setObjectName("spinBox_57")
        self.spinBox_58 = QtWidgets.QSpinBox(Form)
        self.spinBox_58.setGeometry(QtCore.QRect(410, 170, 42, 16))
        self.spinBox_58.setObjectName("spinBox_58")
        self.spinBox_59 = QtWidgets.QSpinBox(Form)
        self.spinBox_59.setGeometry(QtCore.QRect(410, 90, 42, 16))
        self.spinBox_59.setObjectName("spinBox_59")
        self.spinBox_60 = QtWidgets.QSpinBox(Form)
        self.spinBox_60.setGeometry(QtCore.QRect(370, 150, 42, 16))
        self.spinBox_60.setObjectName("spinBox_60")
        self.spinBox_61 = QtWidgets.QSpinBox(Form)
        self.spinBox_61.setGeometry(QtCore.QRect(410, 390, 42, 16))
        self.spinBox_61.setObjectName("spinBox_61")
        self.spinBox_62 = QtWidgets.QSpinBox(Form)
        self.spinBox_62.setGeometry(QtCore.QRect(410, 50, 42, 16))
        self.spinBox_62.setObjectName("spinBox_62")
        self.spinBox_63 = QtWidgets.QSpinBox(Form)
        self.spinBox_63.setGeometry(QtCore.QRect(370, 310, 42, 16))
        self.spinBox_63.setObjectName("spinBox_63")
        self.spinBox_64 = QtWidgets.QSpinBox(Form)
        self.spinBox_64.setGeometry(QtCore.QRect(370, 390, 42, 16))
        self.spinBox_64.setObjectName("spinBox_64")
        self.spinBox_65 = QtWidgets.QSpinBox(Form)
        self.spinBox_65.setGeometry(QtCore.QRect(370, 290, 42, 16))
        self.spinBox_65.setObjectName("spinBox_65")
        self.spinBox_66 = QtWidgets.QSpinBox(Form)
        self.spinBox_66.setGeometry(QtCore.QRect(410, 330, 42, 16))
        self.spinBox_66.setObjectName("spinBox_66")
        self.spinBox_67 = QtWidgets.QSpinBox(Form)
        self.spinBox_67.setGeometry(QtCore.QRect(410, 130, 42, 16))
        self.spinBox_67.setObjectName("spinBox_67")
        self.spinBox_68 = QtWidgets.QSpinBox(Form)
        self.spinBox_68.setGeometry(QtCore.QRect(370, 70, 42, 16))
        self.spinBox_68.setObjectName("spinBox_68")
        self.spinBox_69 = QtWidgets.QSpinBox(Form)
        self.spinBox_69.setGeometry(QtCore.QRect(410, 190, 42, 16))
        self.spinBox_69.setObjectName("spinBox_69")
        self.spinBox_70 = QtWidgets.QSpinBox(Form)
        self.spinBox_70.setGeometry(QtCore.QRect(410, 270, 42, 16))
        self.spinBox_70.setObjectName("spinBox_70")
        self.spinBox_71 = QtWidgets.QSpinBox(Form)
        self.spinBox_71.setGeometry(QtCore.QRect(410, 250, 42, 16))
        self.spinBox_71.setObjectName("spinBox_71")
        self.spinBox_72 = QtWidgets.QSpinBox(Form)
        self.spinBox_72.setGeometry(QtCore.QRect(370, 430, 42, 16))
        self.spinBox_72.setObjectName("spinBox_72")
        self.spinBox_73 = QtWidgets.QSpinBox(Form)
        self.spinBox_73.setGeometry(QtCore.QRect(370, 130, 42, 16))
        self.spinBox_73.setObjectName("spinBox_73")
        self.spinBox_74 = QtWidgets.QSpinBox(Form)
        self.spinBox_74.setGeometry(QtCore.QRect(370, 90, 42, 16))
        self.spinBox_74.setObjectName("spinBox_74")
        self.spinBox_75 = QtWidgets.QSpinBox(Form)
        self.spinBox_75.setGeometry(QtCore.QRect(410, 310, 42, 16))
        self.spinBox_75.setObjectName("spinBox_75")
        self.spinBox_76 = QtWidgets.QSpinBox(Form)
        self.spinBox_76.setGeometry(QtCore.QRect(410, 110, 42, 16))
        self.spinBox_76.setObjectName("spinBox_76")
        self.spinBox_77 = QtWidgets.QSpinBox(Form)
        self.spinBox_77.setGeometry(QtCore.QRect(410, 230, 42, 16))
        self.spinBox_77.setObjectName("spinBox_77")
        self.spinBox_78 = QtWidgets.QSpinBox(Form)
        self.spinBox_78.setGeometry(QtCore.QRect(370, 230, 42, 16))
        self.spinBox_78.setObjectName("spinBox_78")
        self.spinBox_79 = QtWidgets.QSpinBox(Form)
        self.spinBox_79.setGeometry(QtCore.QRect(410, 150, 42, 16))
        self.spinBox_79.setObjectName("spinBox_79")
        self.spinBox_80 = QtWidgets.QSpinBox(Form)
        self.spinBox_80.setGeometry(QtCore.QRect(410, 290, 42, 16))
        self.spinBox_80.setObjectName("spinBox_80")
        self.spinBox_81 = QtWidgets.QSpinBox(Form)
        self.spinBox_81.setGeometry(QtCore.QRect(590, 390, 42, 16))
        self.spinBox_81.setObjectName("spinBox_81")
        self.spinBox_82 = QtWidgets.QSpinBox(Form)
        self.spinBox_82.setGeometry(QtCore.QRect(590, 310, 42, 16))
        self.spinBox_82.setObjectName("spinBox_82")
        self.spinBox_83 = QtWidgets.QSpinBox(Form)
        self.spinBox_83.setGeometry(QtCore.QRect(630, 390, 42, 16))
        self.spinBox_83.setObjectName("spinBox_83")
        self.spinBox_84 = QtWidgets.QSpinBox(Form)
        self.spinBox_84.setGeometry(QtCore.QRect(630, 50, 42, 16))
        self.spinBox_84.setObjectName("spinBox_84")
        self.spinBox_85 = QtWidgets.QSpinBox(Form)
        self.spinBox_85.setGeometry(QtCore.QRect(590, 190, 42, 16))
        self.spinBox_85.setObjectName("spinBox_85")
        self.spinBox_86 = QtWidgets.QSpinBox(Form)
        self.spinBox_86.setGeometry(QtCore.QRect(590, 250, 42, 16))
        self.spinBox_86.setObjectName("spinBox_86")
        self.spinBox_87 = QtWidgets.QSpinBox(Form)
        self.spinBox_87.setGeometry(QtCore.QRect(590, 230, 42, 16))
        self.spinBox_87.setObjectName("spinBox_87")
        self.spinBox_88 = QtWidgets.QSpinBox(Form)
        self.spinBox_88.setGeometry(QtCore.QRect(630, 350, 42, 16))
        self.spinBox_88.setObjectName("spinBox_88")
        self.spinBox_89 = QtWidgets.QSpinBox(Form)
        self.spinBox_89.setGeometry(QtCore.QRect(590, 150, 42, 16))
        self.spinBox_89.setObjectName("spinBox_89")
        self.spinBox_90 = QtWidgets.QSpinBox(Form)
        self.spinBox_90.setGeometry(QtCore.QRect(590, 170, 42, 16))
        self.spinBox_90.setObjectName("spinBox_90")
        self.spinBox_91 = QtWidgets.QSpinBox(Form)
        self.spinBox_91.setGeometry(QtCore.QRect(590, 30, 42, 16))
        self.spinBox_91.setObjectName("spinBox_91")
        self.spinBox_92 = QtWidgets.QSpinBox(Form)
        self.spinBox_92.setGeometry(QtCore.QRect(590, 330, 42, 16))
        self.spinBox_92.setObjectName("spinBox_92")
        self.spinBox_93 = QtWidgets.QSpinBox(Form)
        self.spinBox_93.setGeometry(QtCore.QRect(630, 330, 42, 16))
        self.spinBox_93.setObjectName("spinBox_93")
        self.spinBox_94 = QtWidgets.QSpinBox(Form)
        self.spinBox_94.setGeometry(QtCore.QRect(630, 190, 42, 16))
        self.spinBox_94.setObjectName("spinBox_94")
        self.spinBox_95 = QtWidgets.QSpinBox(Form)
        self.spinBox_95.setGeometry(QtCore.QRect(590, 90, 42, 16))
        self.spinBox_95.setObjectName("spinBox_95")
        self.spinBox_96 = QtWidgets.QSpinBox(Form)
        self.spinBox_96.setGeometry(QtCore.QRect(590, 350, 42, 16))
        self.spinBox_96.setObjectName("spinBox_96")
        self.spinBox_97 = QtWidgets.QSpinBox(Form)
        self.spinBox_97.setGeometry(QtCore.QRect(630, 410, 42, 16))
        self.spinBox_97.setObjectName("spinBox_97")
        self.spinBox_98 = QtWidgets.QSpinBox(Form)
        self.spinBox_98.setGeometry(QtCore.QRect(630, 150, 42, 16))
        self.spinBox_98.setObjectName("spinBox_98")
        self.spinBox_99 = QtWidgets.QSpinBox(Form)
        self.spinBox_99.setGeometry(QtCore.QRect(630, 70, 42, 16))
        self.spinBox_99.setObjectName("spinBox_99")
        self.spinBox_100 = QtWidgets.QSpinBox(Form)
        self.spinBox_100.setGeometry(QtCore.QRect(590, 130, 42, 16))
        self.spinBox_100.setObjectName("spinBox_100")
        self.spinBox_101 = QtWidgets.QSpinBox(Form)
        self.spinBox_101.setGeometry(QtCore.QRect(630, 370, 42, 16))
        self.spinBox_101.setObjectName("spinBox_101")
        self.spinBox_102 = QtWidgets.QSpinBox(Form)
        self.spinBox_102.setGeometry(QtCore.QRect(630, 30, 42, 16))
        self.spinBox_102.setObjectName("spinBox_102")
        self.spinBox_103 = QtWidgets.QSpinBox(Form)
        self.spinBox_103.setGeometry(QtCore.QRect(590, 290, 42, 16))
        self.spinBox_103.setObjectName("spinBox_103")
        self.spinBox_104 = QtWidgets.QSpinBox(Form)
        self.spinBox_104.setGeometry(QtCore.QRect(590, 370, 42, 16))
        self.spinBox_104.setObjectName("spinBox_104")
        self.spinBox_105 = QtWidgets.QSpinBox(Form)
        self.spinBox_105.setGeometry(QtCore.QRect(590, 270, 42, 16))
        self.spinBox_105.setObjectName("spinBox_105")
        self.spinBox_106 = QtWidgets.QSpinBox(Form)
        self.spinBox_106.setGeometry(QtCore.QRect(630, 310, 42, 16))
        self.spinBox_106.setObjectName("spinBox_106")
        self.spinBox_107 = QtWidgets.QSpinBox(Form)
        self.spinBox_107.setGeometry(QtCore.QRect(630, 110, 42, 16))
        self.spinBox_107.setObjectName("spinBox_107")
        self.spinBox_108 = QtWidgets.QSpinBox(Form)
        self.spinBox_108.setGeometry(QtCore.QRect(590, 50, 42, 16))
        self.spinBox_108.setObjectName("spinBox_108")
        self.spinBox_109 = QtWidgets.QSpinBox(Form)
        self.spinBox_109.setGeometry(QtCore.QRect(630, 170, 42, 16))
        self.spinBox_109.setObjectName("spinBox_109")
        self.spinBox_110 = QtWidgets.QSpinBox(Form)
        self.spinBox_110.setGeometry(QtCore.QRect(630, 250, 42, 16))
        self.spinBox_110.setObjectName("spinBox_110")
        self.spinBox_111 = QtWidgets.QSpinBox(Form)
        self.spinBox_111.setGeometry(QtCore.QRect(630, 230, 42, 16))
        self.spinBox_111.setObjectName("spinBox_111")
        self.spinBox_112 = QtWidgets.QSpinBox(Form)
        self.spinBox_112.setGeometry(QtCore.QRect(590, 410, 42, 16))
        self.spinBox_112.setObjectName("spinBox_112")
        self.spinBox_113 = QtWidgets.QSpinBox(Form)
        self.spinBox_113.setGeometry(QtCore.QRect(590, 110, 42, 16))
        self.spinBox_113.setObjectName("spinBox_113")
        self.spinBox_114 = QtWidgets.QSpinBox(Form)
        self.spinBox_114.setGeometry(QtCore.QRect(590, 70, 42, 16))
        self.spinBox_114.setObjectName("spinBox_114")
        self.spinBox_115 = QtWidgets.QSpinBox(Form)
        self.spinBox_115.setGeometry(QtCore.QRect(630, 290, 42, 16))
        self.spinBox_115.setObjectName("spinBox_115")
        self.spinBox_116 = QtWidgets.QSpinBox(Form)
        self.spinBox_116.setGeometry(QtCore.QRect(630, 90, 42, 16))
        self.spinBox_116.setObjectName("spinBox_116")
        self.spinBox_117 = QtWidgets.QSpinBox(Form)
        self.spinBox_117.setGeometry(QtCore.QRect(630, 210, 42, 16))
        self.spinBox_117.setObjectName("spinBox_117")
        self.spinBox_118 = QtWidgets.QSpinBox(Form)
        self.spinBox_118.setGeometry(QtCore.QRect(590, 210, 42, 16))
        self.spinBox_118.setObjectName("spinBox_118")
        self.spinBox_119 = QtWidgets.QSpinBox(Form)
        self.spinBox_119.setGeometry(QtCore.QRect(630, 130, 42, 16))
        self.spinBox_119.setObjectName("spinBox_119")
        self.spinBox_120 = QtWidgets.QSpinBox(Form)
        self.spinBox_120.setGeometry(QtCore.QRect(630, 270, 42, 16))
        self.spinBox_120.setObjectName("spinBox_120")
        self.next_step = QtWidgets.QPushButton(Form)
        self.next_step.setGeometry(QtCore.QRect(590, 430, 75, 23))
        self.next_step.setObjectName("next_step")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 31, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 170, 31, 16))
        self.label_7.setObjectName("label_7")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(10, 430, 31, 16))
        self.label_20.setObjectName("label_20")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(230, 50, 31, 16))
        self.label_25.setObjectName("label_25")
        self.label_33 = QtWidgets.QLabel(Form)
        self.label_33.setGeometry(QtCore.QRect(230, 90, 31, 16))
        self.label_33.setObjectName("label_33")
        self.label_39 = QtWidgets.QLabel(Form)
        self.label_39.setGeometry(QtCore.QRect(230, 110, 31, 16))
        self.label_39.setObjectName("label_39")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(230, 210, 31, 16))
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(230, 230, 31, 16))
        self.label_23.setObjectName("label_23")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(230, 250, 31, 16))
        self.label_27.setObjectName("label_27")
        self.label_35 = QtWidgets.QLabel(Form)
        self.label_35.setGeometry(QtCore.QRect(230, 270, 31, 16))
        self.label_35.setObjectName("label_35")
        self.label_45 = QtWidgets.QLabel(Form)
        self.label_45.setGeometry(QtCore.QRect(460, 90, 31, 16))
        self.label_45.setObjectName("label_45")
        self.label_41 = QtWidgets.QLabel(Form)
        self.label_41.setGeometry(QtCore.QRect(460, 170, 31, 16))
        self.label_41.setObjectName("label_41")
        self.label_46 = QtWidgets.QLabel(Form)
        self.label_46.setGeometry(QtCore.QRect(460, 190, 31, 16))
        self.label_46.setObjectName("label_46")
        self.label_55 = QtWidgets.QLabel(Form)
        self.label_55.setGeometry(QtCore.QRect(460, 210, 31, 16))
        self.label_55.setObjectName("label_55")
        self.label_48 = QtWidgets.QLabel(Form)
        self.label_48.setGeometry(QtCore.QRect(460, 290, 31, 16))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(Form)
        self.label_49.setGeometry(QtCore.QRect(460, 310, 31, 16))
        self.label_49.setObjectName("label_49")
        self.label_56 = QtWidgets.QLabel(Form)
        self.label_56.setGeometry(QtCore.QRect(460, 390, 31, 16))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(Form)
        self.label_57.setGeometry(QtCore.QRect(460, 410, 31, 16))
        self.label_57.setObjectName("label_57")
        self.label_61 = QtWidgets.QLabel(Form)
        self.label_61.setGeometry(QtCore.QRect(40, 130, 91, 16))
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(Form)
        self.label_62.setGeometry(QtCore.QRect(40, 150, 91, 16))
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(Form)
        self.label_63.setGeometry(QtCore.QRect(40, 170, 91, 16))
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(Form)
        self.label_64.setGeometry(QtCore.QRect(40, 430, 91, 16))
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(Form)
        self.label_65.setGeometry(QtCore.QRect(260, 50, 91, 16))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(Form)
        self.label_66.setGeometry(QtCore.QRect(260, 90, 91, 16))
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(Form)
        self.label_67.setGeometry(QtCore.QRect(260, 110, 81, 16))
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(Form)
        self.label_68.setGeometry(QtCore.QRect(260, 210, 91, 16))
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(Form)
        self.label_69.setGeometry(QtCore.QRect(260, 230, 91, 16))
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(Form)
        self.label_70.setGeometry(QtCore.QRect(260, 250, 91, 16))
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(Form)
        self.label_71.setGeometry(QtCore.QRect(260, 270, 91, 16))
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(Form)
        self.label_72.setGeometry(QtCore.QRect(490, 90, 91, 16))
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(Form)
        self.label_73.setGeometry(QtCore.QRect(490, 170, 91, 16))
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(Form)
        self.label_74.setGeometry(QtCore.QRect(490, 190, 91, 16))
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(Form)
        self.label_75.setGeometry(QtCore.QRect(490, 210, 91, 16))
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(Form)
        self.label_76.setGeometry(QtCore.QRect(490, 290, 91, 16))
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(Form)
        self.label_77.setGeometry(QtCore.QRect(490, 310, 91, 16))
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(Form)
        self.label_78.setGeometry(QtCore.QRect(490, 390, 91, 16))
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(Form)
        self.label_79.setGeometry(QtCore.QRect(490, 410, 91, 16))
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(Form)
        self.label_80.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(Form)
        self.label_81.setGeometry(QtCore.QRect(140, 30, 31, 16))
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(Form)
        self.label_82.setGeometry(QtCore.QRect(180, 30, 31, 16))
        self.label_82.setObjectName("label_82")
        self.label_83 = QtWidgets.QLabel(Form)
        self.label_83.setGeometry(QtCore.QRect(370, 30, 31, 16))
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(Form)
        self.label_84.setGeometry(QtCore.QRect(410, 30, 31, 16))
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(Form)
        self.label_85.setGeometry(QtCore.QRect(590, 10, 31, 16))
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(Form)
        self.label_86.setGeometry(QtCore.QRect(630, 10, 31, 16))
        self.label_86.setObjectName("label_86")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.label_3.setText(_translate("Form", "TextLabel"))
        self.label_4.setText(_translate("Form", "TextLabel"))
        self.label_5.setText(_translate("Form", "技艺:"))
        self.label_8.setText(_translate("Form", "TextLabel"))
        self.label_9.setText(_translate("Form", "TextLabel"))
        self.label_10.setText(_translate("Form", "TextLabel"))
        self.label_11.setText(_translate("Form", "TextLabel"))
        self.label_12.setText(_translate("Form", "TextLabel"))
        self.label_13.setText(_translate("Form", "TextLabel"))
        self.label_14.setText(_translate("Form", "TextLabel"))
        self.label_15.setText(_translate("Form", "TextLabel"))
        self.label_16.setText(_translate("Form", "TextLabel"))
        self.label_17.setText(_translate("Form", "TextLabel"))
        self.label_18.setText(_translate("Form", "TextLabel"))
        self.label_19.setText(_translate("Form", "TextLabel"))
        self.label_22.setText(_translate("Form", "TextLabel"))
        self.label_24.setText(_translate("Form", "TextLabel"))
        self.label_26.setText(_translate("Form", "TextLabel"))
        self.label_28.setText(_translate("Form", "TextLabel"))
        self.label_29.setText(_translate("Form", "TextLabel"))
        self.label_30.setText(_translate("Form", "TextLabel"))
        self.label_31.setText(_translate("Form", "TextLabel"))
        self.label_32.setText(_translate("Form", "TextLabel"))
        self.label_34.setText(_translate("Form", "TextLabel"))
        self.label_36.setText(_translate("Form", "TextLabel"))
        self.label_37.setText(_translate("Form", "TextLabel"))
        self.label_38.setText(_translate("Form", "TextLabel"))
        self.label_40.setText(_translate("Form", "TextLabel"))
        self.label_42.setText(_translate("Form", "TextLabel"))
        self.label_43.setText(_translate("Form", "TextLabel"))
        self.label_44.setText(_translate("Form", "TextLabel"))
        self.label_47.setText(_translate("Form", "TextLabel"))
        self.label_50.setText(_translate("Form", "TextLabel"))
        self.label_51.setText(_translate("Form", "TextLabel"))
        self.label_52.setText(_translate("Form", "TextLabel"))
        self.label_53.setText(_translate("Form", "TextLabel"))
        self.label_54.setText(_translate("Form", "TextLabel"))
        self.label_58.setText(_translate("Form", "TextLabel"))
        self.label_59.setText(_translate("Form", "TextLabel"))
        self.label_60.setText(_translate("Form", "TextLabel"))
        self.next_step.setText(_translate("Form", "下一步"))
        self.label_6.setText(_translate("Form", "技艺:"))
        self.label_7.setText(_translate("Form", "技艺:"))
        self.label_20.setText(_translate("Form", "技艺:"))
        self.label_25.setText(_translate("Form", "技艺:"))
        self.label_33.setText(_translate("Form", "技艺:"))
        self.label_39.setText(_translate("Form", "技艺:"))
        self.label_21.setText(_translate("Form", "技艺:"))
        self.label_23.setText(_translate("Form", "技艺:"))
        self.label_27.setText(_translate("Form", "技艺:"))
        self.label_35.setText(_translate("Form", "技艺:"))
        self.label_45.setText(_translate("Form", "技艺:"))
        self.label_41.setText(_translate("Form", "技艺:"))
        self.label_46.setText(_translate("Form", "技艺:"))
        self.label_55.setText(_translate("Form", "技艺:"))
        self.label_48.setText(_translate("Form", "技艺:"))
        self.label_49.setText(_translate("Form", "技艺:"))
        self.label_56.setText(_translate("Form", "技艺:"))
        self.label_57.setText(_translate("Form", "技艺:"))
        self.label_61.setText(_translate("Form", "TextLabel"))
        self.label_62.setText(_translate("Form", "TextLabel"))
        self.label_63.setText(_translate("Form", "TextLabel"))
        self.label_64.setText(_translate("Form", "TextLabel"))
        self.label_65.setText(_translate("Form", "TextLabel"))
        self.label_66.setText(_translate("Form", "TextLabel"))
        self.label_67.setText(_translate("Form", "TextLabel"))
        self.label_68.setText(_translate("Form", "TextLabel"))
        self.label_69.setText(_translate("Form", "TextLabel"))
        self.label_70.setText(_translate("Form", "TextLabel"))
        self.label_71.setText(_translate("Form", "TextLabel"))
        self.label_72.setText(_translate("Form", "TextLabel"))
        self.label_73.setText(_translate("Form", "TextLabel"))
        self.label_74.setText(_translate("Form", "TextLabel"))
        self.label_75.setText(_translate("Form", "TextLabel"))
        self.label_76.setText(_translate("Form", "TextLabel"))
        self.label_77.setText(_translate("Form", "TextLabel"))
        self.label_78.setText(_translate("Form", "TextLabel"))
        self.label_79.setText(_translate("Form", "TextLabel"))
        self.label_80.setText(_translate("Form", "TextLabel"))
        self.label_81.setText(_translate("Form", "TextLabel"))
        self.label_82.setText(_translate("Form", "TextLabel"))
        self.label_83.setText(_translate("Form", "TextLabel"))
        self.label_84.setText(_translate("Form", "TextLabel"))
        self.label_85.setText(_translate("Form", "TextLabel"))
        self.label_86.setText(_translate("Form", "TextLabel"))
