# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdjustBasics_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(306, 240)
        self.next_step = QtWidgets.QPushButton(Form)
        self.next_step.setGeometry(QtCore.QRect(220, 210, 75, 23))
        self.next_step.setObjectName("next_step")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label.setObjectName("label")
        self.age = QtWidgets.QLabel(Form)
        self.age.setGeometry(QtCore.QRect(70, 10, 21, 16))
        self.age.setObjectName("age")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.label_3.setObjectName("label_3")
        self.tip = QtWidgets.QLabel(Form)
        self.tip.setGeometry(QtCore.QRect(20, 50, 271, 31))
        self.tip.setObjectName("tip")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(160, 150, 61, 21))
        self.label_10.setObjectName("label_10")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 61, 21))
        self.label_7.setObjectName("label_7")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(10, 150, 61, 21))
        self.label_13.setObjectName("label_13")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(160, 120, 61, 21))
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(10, 180, 61, 21))
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(160, 180, 61, 21))
        self.label_11.setObjectName("label_11")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(10, 120, 61, 21))
        self.label_14.setObjectName("label_14")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(160, 90, 61, 21))
        self.label_8.setObjectName("label_8")
        self.STR = QtWidgets.QSpinBox(Form)
        self.STR.setGeometry(QtCore.QRect(70, 90, 42, 22))
        self.STR.setObjectName("STR")
        self.CON = QtWidgets.QSpinBox(Form)
        self.CON.setGeometry(QtCore.QRect(70, 120, 42, 22))
        self.CON.setObjectName("CON")
        self.SIZ = QtWidgets.QSpinBox(Form)
        self.SIZ.setGeometry(QtCore.QRect(70, 150, 42, 22))
        self.SIZ.setObjectName("SIZ")
        self.DEX = QtWidgets.QSpinBox(Form)
        self.DEX.setGeometry(QtCore.QRect(70, 180, 42, 22))
        self.DEX.setObjectName("DEX")
        self.APP = QtWidgets.QSpinBox(Form)
        self.APP.setGeometry(QtCore.QRect(220, 90, 42, 22))
        self.APP.setObjectName("APP")
        self.INT = QtWidgets.QSpinBox(Form)
        self.INT.setGeometry(QtCore.QRect(220, 120, 42, 22))
        self.INT.setObjectName("INT")
        self.POW = QtWidgets.QSpinBox(Form)
        self.POW.setGeometry(QtCore.QRect(220, 150, 42, 22))
        self.POW.setObjectName("POW")
        self.EDU = QtWidgets.QSpinBox(Form)
        self.EDU.setGeometry(QtCore.QRect(220, 180, 42, 22))
        self.EDU.setObjectName("EDU")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(120, 90, 16, 21))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(120, 120, 16, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(120, 150, 16, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(120, 180, 16, 21))
        self.label_6.setObjectName("label_6")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(270, 90, 16, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(270, 120, 16, 21))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(270, 150, 16, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(270, 180, 16, 21))
        self.label_18.setObjectName("label_18")
        self.old_STR = QtWidgets.QLabel(Form)
        self.old_STR.setGeometry(QtCore.QRect(130, 92, 16, 20))
        self.old_STR.setObjectName("old_STR")
        self.old_CON = QtWidgets.QLabel(Form)
        self.old_CON.setGeometry(QtCore.QRect(130, 120, 16, 20))
        self.old_CON.setObjectName("old_CON")
        self.old_SIZ = QtWidgets.QLabel(Form)
        self.old_SIZ.setGeometry(QtCore.QRect(130, 150, 16, 20))
        self.old_SIZ.setObjectName("old_SIZ")
        self.old_DEX = QtWidgets.QLabel(Form)
        self.old_DEX.setGeometry(QtCore.QRect(130, 180, 16, 20))
        self.old_DEX.setObjectName("old_DEX")
        self.old_APP = QtWidgets.QLabel(Form)
        self.old_APP.setGeometry(QtCore.QRect(280, 90, 16, 20))
        self.old_APP.setObjectName("old_APP")
        self.old_INT = QtWidgets.QLabel(Form)
        self.old_INT.setGeometry(QtCore.QRect(280, 120, 16, 20))
        self.old_INT.setObjectName("old_INT")
        self.old_POW = QtWidgets.QLabel(Form)
        self.old_POW.setGeometry(QtCore.QRect(280, 150, 16, 20))
        self.old_POW.setObjectName("old_POW")
        self.old_EDU = QtWidgets.QLabel(Form)
        self.old_EDU.setGeometry(QtCore.QRect(280, 180, 16, 21))
        self.old_EDU.setObjectName("old_EDU")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.next_step.setText(_translate("Form", "下一步"))
        self.label.setText(_translate("Form", "你的年龄为"))
        self.age.setText(_translate("Form", "##"))
        self.label_3.setText(_translate("Form", "需要调整的属性："))
        self.tip.setText(_translate("Form", "TextLabel"))
        self.label_10.setText(_translate("Form", "意志(POW)："))
        self.label_7.setText(_translate("Form", "力量(STR)："))
        self.label_13.setText(_translate("Form", "体型(SIZ)："))
        self.label_9.setText(_translate("Form", "智力(INT)："))
        self.label_12.setText(_translate("Form", "敏捷(DEX)："))
        self.label_11.setText(_translate("Form", "教育(EDU)："))
        self.label_14.setText(_translate("Form", "体质(CON)："))
        self.label_8.setText(_translate("Form", "外貌(APP)："))
        self.label_2.setText(_translate("Form", "/"))
        self.label_4.setText(_translate("Form", "/"))
        self.label_5.setText(_translate("Form", "/"))
        self.label_6.setText(_translate("Form", "/"))
        self.label_15.setText(_translate("Form", "/"))
        self.label_16.setText(_translate("Form", "/"))
        self.label_17.setText(_translate("Form", "/"))
        self.label_18.setText(_translate("Form", "/"))
        self.old_STR.setText(_translate("Form", "##"))
        self.old_CON.setText(_translate("Form", "##"))
        self.old_SIZ.setText(_translate("Form", "##"))
        self.old_DEX.setText(_translate("Form", "##"))
        self.old_APP.setText(_translate("Form", "##"))
        self.old_INT.setText(_translate("Form", "##"))
        self.old_POW.setText(_translate("Form", "##"))
        self.old_EDU.setText(_translate("Form", "##"))
