# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdjustBasics_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(294, 231)
        self.next_step = QtWidgets.QPushButton(Form)
        self.next_step.setGeometry(QtCore.QRect(210, 200, 75, 23))
        self.next_step.setObjectName("next_step")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label.setObjectName("label")
        self.age = QtWidgets.QLabel(Form)
        self.age.setGeometry(QtCore.QRect(70, 10, 21, 16))
        self.age.setObjectName("age")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.label_3.setObjectName("label_3")
        self.tip = QtWidgets.QLabel(Form)
        self.tip.setGeometry(QtCore.QRect(10, 50, 271, 16))
        self.tip.setObjectName("tip")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(140, 140, 61, 16))
        self.label_10.setObjectName("label_10")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.label_7.setObjectName("label_7")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(10, 140, 61, 16))
        self.label_13.setObjectName("label_13")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(140, 110, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(10, 170, 61, 16))
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(140, 170, 61, 16))
        self.label_11.setObjectName("label_11")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(10, 110, 61, 16))
        self.label_14.setObjectName("label_14")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(140, 80, 61, 16))
        self.label_8.setObjectName("label_8")
        self.STR = QtWidgets.QSpinBox(Form)
        self.STR.setGeometry(QtCore.QRect(70, 80, 42, 22))
        self.STR.setObjectName("STR")
        self.CON = QtWidgets.QSpinBox(Form)
        self.CON.setGeometry(QtCore.QRect(70, 110, 42, 22))
        self.CON.setObjectName("CON")
        self.SIZ = QtWidgets.QSpinBox(Form)
        self.SIZ.setGeometry(QtCore.QRect(70, 140, 42, 22))
        self.SIZ.setObjectName("SIZ")
        self.DEX = QtWidgets.QSpinBox(Form)
        self.DEX.setGeometry(QtCore.QRect(70, 170, 42, 22))
        self.DEX.setObjectName("DEX")
        self.APP = QtWidgets.QSpinBox(Form)
        self.APP.setGeometry(QtCore.QRect(200, 80, 42, 22))
        self.APP.setObjectName("APP")
        self.INT = QtWidgets.QSpinBox(Form)
        self.INT.setGeometry(QtCore.QRect(200, 110, 42, 22))
        self.INT.setObjectName("INT")
        self.POW = QtWidgets.QSpinBox(Form)
        self.POW.setGeometry(QtCore.QRect(200, 140, 42, 22))
        self.POW.setObjectName("POW")
        self.EDU = QtWidgets.QSpinBox(Form)
        self.EDU.setGeometry(QtCore.QRect(200, 170, 42, 22))
        self.EDU.setObjectName("EDU")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.next_step.setText(_translate("Form", "下一步"))
        self.label.setText(_translate("Form", "你的年龄为"))
        self.age.setText(_translate("Form", "##"))
        self.label_3.setText(_translate("Form", "需要调整的属性："))
        self.tip.setText(_translate("Form", "TextLabel"))
        self.label_10.setText(_translate("Form", "意志(POW)："))
        self.label_7.setText(_translate("Form", "力量(STR)："))
        self.label_13.setText(_translate("Form", "体型(SIZ)："))
        self.label_9.setText(_translate("Form", "智力(INT)："))
        self.label_12.setText(_translate("Form", "敏捷(DEX)："))
        self.label_11.setText(_translate("Form", "教育(EDU)："))
        self.label_14.setText(_translate("Form", "体质(CON)："))
        self.label_8.setText(_translate("Form", "外貌(APP)："))
