# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChooseProfessionalSkills_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(684, 455)
        self.skill1 = QtWidgets.QCheckBox(Form)
        self.skill1.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.skill1.setObjectName("skill1")
        self.skill2 = QtWidgets.QCheckBox(Form)
        self.skill2.setGeometry(QtCore.QRect(10, 130, 71, 16))
        self.skill2.setObjectName("skill2")
        self.skill3 = QtWidgets.QCheckBox(Form)
        self.skill3.setGeometry(QtCore.QRect(10, 150, 71, 16))
        self.skill3.setObjectName("skill3")
        self.skill4 = QtWidgets.QCheckBox(Form)
        self.skill4.setGeometry(QtCore.QRect(10, 170, 71, 16))
        self.skill4.setObjectName("skill4")
        self.skill5 = QtWidgets.QCheckBox(Form)
        self.skill5.setGeometry(QtCore.QRect(10, 190, 51, 16))
        self.skill5.setObjectName("skill5")
        self.skill6 = QtWidgets.QCheckBox(Form)
        self.skill6.setGeometry(QtCore.QRect(10, 210, 51, 16))
        self.skill6.setObjectName("skill6")
        self.skill7 = QtWidgets.QCheckBox(Form)
        self.skill7.setGeometry(QtCore.QRect(10, 230, 51, 16))
        self.skill7.setObjectName("skill7")
        self.skill8 = QtWidgets.QCheckBox(Form)
        self.skill8.setGeometry(QtCore.QRect(10, 250, 71, 16))
        self.skill8.setObjectName("skill8")
        self.skill9 = QtWidgets.QCheckBox(Form)
        self.skill9.setGeometry(QtCore.QRect(10, 270, 71, 16))
        self.skill9.setObjectName("skill9")
        self.skill10 = QtWidgets.QCheckBox(Form)
        self.skill10.setGeometry(QtCore.QRect(10, 290, 101, 16))
        self.skill10.setObjectName("skill10")
        self.skill11 = QtWidgets.QCheckBox(Form)
        self.skill11.setGeometry(QtCore.QRect(10, 310, 71, 16))
        self.skill11.setObjectName("skill11")
        self.skill12 = QtWidgets.QCheckBox(Form)
        self.skill12.setGeometry(QtCore.QRect(10, 330, 81, 16))
        self.skill12.setObjectName("skill12")
        self.skill13 = QtWidgets.QCheckBox(Form)
        self.skill13.setGeometry(QtCore.QRect(10, 350, 71, 16))
        self.skill13.setObjectName("skill13")
        self.skill14 = QtWidgets.QCheckBox(Form)
        self.skill14.setGeometry(QtCore.QRect(10, 370, 71, 16))
        self.skill14.setObjectName("skill14")
        self.skill15 = QtWidgets.QCheckBox(Form)
        self.skill15.setGeometry(QtCore.QRect(10, 390, 71, 16))
        self.skill15.setObjectName("skill15")
        self.skill28 = QtWidgets.QCheckBox(Form)
        self.skill28.setGeometry(QtCore.QRect(180, 350, 71, 16))
        self.skill28.setObjectName("skill28")
        self.skill29 = QtWidgets.QCheckBox(Form)
        self.skill29.setGeometry(QtCore.QRect(180, 370, 51, 16))
        self.skill29.setObjectName("skill29")
        self.skill30 = QtWidgets.QCheckBox(Form)
        self.skill30.setGeometry(QtCore.QRect(180, 390, 51, 16))
        self.skill30.setObjectName("skill30")
        self.skill19 = QtWidgets.QCheckBox(Form)
        self.skill19.setGeometry(QtCore.QRect(180, 170, 81, 16))
        self.skill19.setObjectName("skill19")
        self.skill22 = QtWidgets.QCheckBox(Form)
        self.skill22.setGeometry(QtCore.QRect(180, 230, 81, 16))
        self.skill22.setObjectName("skill22")
        self.skill24 = QtWidgets.QCheckBox(Form)
        self.skill24.setGeometry(QtCore.QRect(180, 270, 51, 16))
        self.skill24.setObjectName("skill24")
        self.skill21 = QtWidgets.QCheckBox(Form)
        self.skill21.setGeometry(QtCore.QRect(180, 210, 51, 16))
        self.skill21.setObjectName("skill21")
        self.skill26 = QtWidgets.QCheckBox(Form)
        self.skill26.setGeometry(QtCore.QRect(180, 310, 71, 16))
        self.skill26.setObjectName("skill26")
        self.skill17 = QtWidgets.QCheckBox(Form)
        self.skill17.setGeometry(QtCore.QRect(180, 130, 71, 16))
        self.skill17.setObjectName("skill17")
        self.skill18 = QtWidgets.QCheckBox(Form)
        self.skill18.setGeometry(QtCore.QRect(180, 150, 71, 16))
        self.skill18.setObjectName("skill18")
        self.skill20 = QtWidgets.QCheckBox(Form)
        self.skill20.setGeometry(QtCore.QRect(180, 190, 51, 16))
        self.skill20.setObjectName("skill20")
        self.skill27 = QtWidgets.QCheckBox(Form)
        self.skill27.setGeometry(QtCore.QRect(180, 330, 71, 16))
        self.skill27.setObjectName("skill27")
        self.skill16 = QtWidgets.QCheckBox(Form)
        self.skill16.setGeometry(QtCore.QRect(180, 110, 71, 16))
        self.skill16.setObjectName("skill16")
        self.skill23 = QtWidgets.QCheckBox(Form)
        self.skill23.setGeometry(QtCore.QRect(180, 250, 51, 16))
        self.skill23.setObjectName("skill23")
        self.skill25 = QtWidgets.QCheckBox(Form)
        self.skill25.setGeometry(QtCore.QRect(180, 290, 71, 16))
        self.skill25.setObjectName("skill25")
        self.skill43 = QtWidgets.QCheckBox(Form)
        self.skill43.setGeometry(QtCore.QRect(350, 350, 71, 16))
        self.skill43.setObjectName("skill43")
        self.skill44 = QtWidgets.QCheckBox(Form)
        self.skill44.setGeometry(QtCore.QRect(350, 370, 71, 16))
        self.skill44.setObjectName("skill44")
        self.skill45 = QtWidgets.QCheckBox(Form)
        self.skill45.setGeometry(QtCore.QRect(350, 390, 71, 16))
        self.skill45.setObjectName("skill45")
        self.skill34 = QtWidgets.QCheckBox(Form)
        self.skill34.setGeometry(QtCore.QRect(350, 170, 81, 16))
        self.skill34.setObjectName("skill34")
        self.skill37 = QtWidgets.QCheckBox(Form)
        self.skill37.setGeometry(QtCore.QRect(350, 230, 71, 16))
        self.skill37.setObjectName("skill37")
        self.skill39 = QtWidgets.QCheckBox(Form)
        self.skill39.setGeometry(QtCore.QRect(350, 270, 71, 16))
        self.skill39.setObjectName("skill39")
        self.skill36 = QtWidgets.QCheckBox(Form)
        self.skill36.setGeometry(QtCore.QRect(350, 210, 71, 16))
        self.skill36.setObjectName("skill36")
        self.skill41 = QtWidgets.QCheckBox(Form)
        self.skill41.setGeometry(QtCore.QRect(350, 310, 71, 16))
        self.skill41.setObjectName("skill41")
        self.skill32 = QtWidgets.QCheckBox(Form)
        self.skill32.setGeometry(QtCore.QRect(350, 130, 71, 16))
        self.skill32.setObjectName("skill32")
        self.skill33 = QtWidgets.QCheckBox(Form)
        self.skill33.setGeometry(QtCore.QRect(350, 150, 71, 16))
        self.skill33.setObjectName("skill33")
        self.skill35 = QtWidgets.QCheckBox(Form)
        self.skill35.setGeometry(QtCore.QRect(350, 190, 71, 16))
        self.skill35.setObjectName("skill35")
        self.skill42 = QtWidgets.QCheckBox(Form)
        self.skill42.setGeometry(QtCore.QRect(350, 330, 91, 16))
        self.skill42.setObjectName("skill42")
        self.skill31 = QtWidgets.QCheckBox(Form)
        self.skill31.setGeometry(QtCore.QRect(350, 110, 51, 16))
        self.skill31.setObjectName("skill31")
        self.skill38 = QtWidgets.QCheckBox(Form)
        self.skill38.setGeometry(QtCore.QRect(350, 250, 71, 16))
        self.skill38.setObjectName("skill38")
        self.skill40 = QtWidgets.QCheckBox(Form)
        self.skill40.setGeometry(QtCore.QRect(350, 290, 71, 16))
        self.skill40.setObjectName("skill40")
        self.skill59 = QtWidgets.QCheckBox(Form)
        self.skill59.setGeometry(QtCore.QRect(520, 370, 51, 16))
        self.skill59.setObjectName("skill59")
        self.skill60 = QtWidgets.QCheckBox(Form)
        self.skill60.setGeometry(QtCore.QRect(520, 390, 51, 16))
        self.skill60.setObjectName("skill60")
        self.skill47 = QtWidgets.QCheckBox(Form)
        self.skill47.setGeometry(QtCore.QRect(520, 130, 71, 16))
        self.skill47.setObjectName("skill47")
        self.skill50 = QtWidgets.QCheckBox(Form)
        self.skill50.setGeometry(QtCore.QRect(520, 190, 51, 16))
        self.skill50.setObjectName("skill50")
        self.skill53 = QtWidgets.QCheckBox(Form)
        self.skill53.setGeometry(QtCore.QRect(520, 250, 71, 16))
        self.skill53.setObjectName("skill53")
        self.skill55 = QtWidgets.QCheckBox(Form)
        self.skill55.setGeometry(QtCore.QRect(520, 290, 51, 16))
        self.skill55.setObjectName("skill55")
        self.skill52 = QtWidgets.QCheckBox(Form)
        self.skill52.setGeometry(QtCore.QRect(520, 230, 71, 16))
        self.skill52.setObjectName("skill52")
        self.skill57 = QtWidgets.QCheckBox(Form)
        self.skill57.setGeometry(QtCore.QRect(520, 330, 71, 16))
        self.skill57.setObjectName("skill57")
        self.skill48 = QtWidgets.QCheckBox(Form)
        self.skill48.setGeometry(QtCore.QRect(520, 150, 51, 16))
        self.skill48.setObjectName("skill48")
        self.skill49 = QtWidgets.QCheckBox(Form)
        self.skill49.setGeometry(QtCore.QRect(520, 170, 51, 16))
        self.skill49.setObjectName("skill49")
        self.skill51 = QtWidgets.QCheckBox(Form)
        self.skill51.setGeometry(QtCore.QRect(520, 210, 71, 16))
        self.skill51.setObjectName("skill51")
        self.skill58 = QtWidgets.QCheckBox(Form)
        self.skill58.setGeometry(QtCore.QRect(520, 350, 71, 16))
        self.skill58.setObjectName("skill58")
        self.skill46 = QtWidgets.QCheckBox(Form)
        self.skill46.setGeometry(QtCore.QRect(520, 110, 71, 16))
        self.skill46.setObjectName("skill46")
        self.skill54 = QtWidgets.QCheckBox(Form)
        self.skill54.setGeometry(QtCore.QRect(520, 270, 51, 16))
        self.skill54.setObjectName("skill54")
        self.skill56 = QtWidgets.QCheckBox(Form)
        self.skill56.setGeometry(QtCore.QRect(520, 310, 71, 16))
        self.skill56.setObjectName("skill56")
        self.sub_skill5 = QtWidgets.QComboBox(Form)
        self.sub_skill5.setGeometry(QtCore.QRect(60, 190, 111, 16))
        self.sub_skill5.setObjectName("sub_skill5")
        self.sub_skill6 = QtWidgets.QComboBox(Form)
        self.sub_skill6.setGeometry(QtCore.QRect(60, 210, 111, 16))
        self.sub_skill6.setObjectName("sub_skill6")
        self.sub_skill7 = QtWidgets.QComboBox(Form)
        self.sub_skill7.setGeometry(QtCore.QRect(60, 230, 111, 16))
        self.sub_skill7.setObjectName("sub_skill7")
        self.sub_skill20 = QtWidgets.QComboBox(Form)
        self.sub_skill20.setGeometry(QtCore.QRect(230, 190, 101, 16))
        self.sub_skill20.setObjectName("sub_skill20")
        self.sub_skill21 = QtWidgets.QComboBox(Form)
        self.sub_skill21.setGeometry(QtCore.QRect(230, 210, 101, 16))
        self.sub_skill21.setObjectName("sub_skill21")
        self.sub_skill23 = QtWidgets.QComboBox(Form)
        self.sub_skill23.setGeometry(QtCore.QRect(230, 250, 101, 16))
        self.sub_skill23.setObjectName("sub_skill23")
        self.sub_skill24 = QtWidgets.QComboBox(Form)
        self.sub_skill24.setGeometry(QtCore.QRect(230, 270, 101, 16))
        self.sub_skill24.setObjectName("sub_skill24")
        self.sub_skill29 = QtWidgets.QComboBox(Form)
        self.sub_skill29.setGeometry(QtCore.QRect(230, 370, 101, 16))
        self.sub_skill29.setObjectName("sub_skill29")
        self.sub_skill30 = QtWidgets.QComboBox(Form)
        self.sub_skill30.setGeometry(QtCore.QRect(230, 390, 101, 16))
        self.sub_skill30.setObjectName("sub_skill30")
        self.sub_skill31 = QtWidgets.QComboBox(Form)
        self.sub_skill31.setGeometry(QtCore.QRect(400, 110, 101, 16))
        self.sub_skill31.setObjectName("sub_skill31")
        self.sub_skill32 = QtWidgets.QComboBox(Form)
        self.sub_skill32.setGeometry(QtCore.QRect(400, 130, 101, 16))
        self.sub_skill32.setObjectName("sub_skill32")
        self.sub_skill59 = QtWidgets.QComboBox(Form)
        self.sub_skill59.setGeometry(QtCore.QRect(570, 370, 111, 16))
        self.sub_skill59.setObjectName("sub_skill59")
        self.sub_skill60 = QtWidgets.QComboBox(Form)
        self.sub_skill60.setGeometry(QtCore.QRect(570, 390, 111, 16))
        self.sub_skill60.setObjectName("sub_skill60")
        self.next_step = QtWidgets.QPushButton(Form)
        self.next_step.setGeometry(QtCore.QRect(600, 420, 75, 23))
        self.next_step.setObjectName("next_step")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 101, 21))
        self.label.setObjectName("label")
        self.professional_skills = QtWidgets.QTextBrowser(Form)
        self.professional_skills.setGeometry(QtCore.QRect(140, 10, 531, 91))
        self.professional_skills.setObjectName("professional_skills")
        self.sub_skill48 = QtWidgets.QComboBox(Form)
        self.sub_skill48.setGeometry(QtCore.QRect(570, 150, 111, 16))
        self.sub_skill48.setObjectName("sub_skill48")
        self.sub_skill49 = QtWidgets.QComboBox(Form)
        self.sub_skill49.setGeometry(QtCore.QRect(570, 170, 111, 16))
        self.sub_skill49.setObjectName("sub_skill49")
        self.sub_skill50 = QtWidgets.QComboBox(Form)
        self.sub_skill50.setGeometry(QtCore.QRect(570, 190, 111, 16))
        self.sub_skill50.setObjectName("sub_skill50")
        self.sub_skill54 = QtWidgets.QComboBox(Form)
        self.sub_skill54.setGeometry(QtCore.QRect(570, 270, 111, 16))
        self.sub_skill54.setObjectName("sub_skill54")
        self.sub_skill55 = QtWidgets.QComboBox(Form)
        self.sub_skill55.setGeometry(QtCore.QRect(570, 290, 111, 16))
        self.sub_skill55.setObjectName("sub_skill55")
        self.sub_skill44 = QtWidgets.QComboBox(Form)
        self.sub_skill44.setGeometry(QtCore.QRect(400, 370, 111, 16))
        self.sub_skill44.setObjectName("sub_skill44")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.skill1.setToolTip(_translate("Form", "<html><head/><body><p>使你理解会计工作的流程以及一个企业或者个人 的金融职务。通过检查账簿，你可以发现做假账的员工，对资金的偷偷挪用，对行贿或者敲诈的款项支付，以及经济状况是否比表面陈述的更好或者更差。 通过仔细检查旧账户，你可以了解过去的资金的得与失（谷物，奴隶贸易，威士忌酒的运营等）以及这些资金是付给了谁以及为了什么款项而支付。</p></body></html>"))
        self.skill1.setText(_translate("Form", "会计"))
        self.skill2.setToolTip(_translate("Form", "<html><head/><body><p>使使用者能够通过观察来辨认和理解一个人的生活方式。如果技能使用者持续观察一个其他的文化一段时间，或者在有着关于某种已消失文化的正确资料环境下工作，那么他可以对文化方式以及道德习惯进行简单的预测，即使证据可能并不完整。通过学习文化一个月或者更久，人类学家开始理解这种文化是如何运作的以及，如果结合心理学，可以预测那些研究文化的行为和信仰。</p></body></html>"))
        self.skill2.setText(_translate("Form", "人类学"))
        self.skill3.setToolTip(_translate("Form", "<html><head/><body><p>用来估计某种物品的价值，包括质量，使用的材料以及工艺。相关的，技能使用者可以准确地辨认出物品的年龄，评估它的历史关联性以及发现赝品。</p></body></html>"))
        self.skill3.setText(_translate("Form", "估价"))
        self.skill4.setText(_translate("Form", "考古学"))
        self.skill5.setText(_translate("Form", "技艺:"))
        self.skill6.setText(_translate("Form", "技艺:"))
        self.skill7.setText(_translate("Form", "技艺:"))
        self.skill8.setText(_translate("Form", "魅惑"))
        self.skill9.setText(_translate("Form", "攀爬"))
        self.skill10.setText(_translate("Form", "计算机使用 Ω"))
        self.skill11.setText(_translate("Form", "信用评级"))
        self.skill12.setText(_translate("Form", "克苏鲁神话"))
        self.skill13.setText(_translate("Form", "乔装"))
        self.skill14.setText(_translate("Form", "闪避"))
        self.skill15.setText(_translate("Form", "汽车驾驶"))
        self.skill28.setText(_translate("Form", "跳跃"))
        self.skill29.setText(_translate("Form", "语言:"))
        self.skill30.setText(_translate("Form", "语言:"))
        self.skill19.setText(_translate("Form", "格斗:斗殴"))
        self.skill22.setText(_translate("Form", "射击:手枪"))
        self.skill24.setText(_translate("Form", "射击:"))
        self.skill21.setText(_translate("Form", "格斗:"))
        self.skill26.setText(_translate("Form", "历史"))
        self.skill17.setText(_translate("Form", "电子学 Ω"))
        self.skill18.setText(_translate("Form", "话术"))
        self.skill20.setText(_translate("Form", "格斗:"))
        self.skill27.setText(_translate("Form", "恐吓"))
        self.skill16.setText(_translate("Form", "电气维修"))
        self.skill23.setText(_translate("Form", "射击:"))
        self.skill25.setText(_translate("Form", "急救"))
        self.skill43.setText(_translate("Form", "说服"))
        self.skill44.setText(_translate("Form", "驾驶:"))
        self.skill45.setText(_translate("Form", "精神分析"))
        self.skill34.setText(_translate("Form", "图书馆使用"))
        self.skill37.setText(_translate("Form", "机械维修"))
        self.skill39.setText(_translate("Form", "自然学"))
        self.skill36.setText(_translate("Form", "锁匠"))
        self.skill41.setText(_translate("Form", "神秘学"))
        self.skill32.setText(_translate("Form", "母语:"))
        self.skill33.setText(_translate("Form", "法律"))
        self.skill35.setText(_translate("Form", "聆听"))
        self.skill42.setText(_translate("Form", "操作重型机械"))
        self.skill31.setText(_translate("Form", "语言:"))
        self.skill38.setText(_translate("Form", "医学"))
        self.skill40.setText(_translate("Form", "导航"))
        self.skill59.setText(_translate("Form", "罕见:"))
        self.skill60.setText(_translate("Form", "学问:"))
        self.skill47.setText(_translate("Form", "骑术"))
        self.skill50.setText(_translate("Form", "科学:"))
        self.skill53.setText(_translate("Form", "潜行"))
        self.skill55.setText(_translate("Form", "生存:"))
        self.skill52.setText(_translate("Form", "侦察"))
        self.skill57.setText(_translate("Form", "投掷"))
        self.skill48.setText(_translate("Form", "科学:"))
        self.skill49.setText(_translate("Form", "科学:"))
        self.skill51.setText(_translate("Form", "妙手"))
        self.skill58.setText(_translate("Form", "追踪"))
        self.skill46.setText(_translate("Form", "心理学"))
        self.skill54.setText(_translate("Form", "生存:"))
        self.skill56.setText(_translate("Form", "游泳"))
        self.next_step.setText(_translate("Form", "下一步"))
        self.label.setText(_translate("Form", "请选择本职技能："))
