# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateCardInfo_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(266, 259)
        self.sex_0 = QtWidgets.QRadioButton(Form)
        self.sex_0.setGeometry(QtCore.QRect(50, 140, 31, 16))
        self.sex_0.setObjectName("sex_0")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 110, 31, 16))
        self.label.setObjectName("label")
        self.age = QtWidgets.QSpinBox(Form)
        self.age.setGeometry(QtCore.QRect(50, 170, 42, 22))
        self.age.setObjectName("age")
        self.next_step = QtWidgets.QPushButton(Form)
        self.next_step.setGeometry(QtCore.QRect(180, 230, 75, 23))
        self.next_step.setObjectName("next_step")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 31, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 170, 31, 16))
        self.label_3.setObjectName("label_3")
        self.homeland = QtWidgets.QLineEdit(Form)
        self.homeland.setGeometry(QtCore.QRect(50, 230, 113, 20))
        self.homeland.setObjectName("homeland")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 31, 16))
        self.label_4.setObjectName("label_4")
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setGeometry(QtCore.QRect(50, 110, 113, 20))
        self.name.setObjectName("name")
        self.sex_1 = QtWidgets.QRadioButton(Form)
        self.sex_1.setGeometry(QtCore.QRect(110, 140, 31, 16))
        self.sex_1.setObjectName("sex_1")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 31, 16))
        self.label_5.setObjectName("label_5")
        self.living_place = QtWidgets.QLineEdit(Form)
        self.living_place.setGeometry(QtCore.QRect(50, 200, 113, 20))
        self.living_place.setObjectName("living_place")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 111, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(140, 20, 61, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(140, 40, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(140, 60, 61, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(140, 80, 61, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(10, 60, 61, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.label_14.setObjectName("label_14")
        self.STR = QtWidgets.QLabel(Form)
        self.STR.setGeometry(QtCore.QRect(80, 20, 16, 16))
        self.STR.setObjectName("STR")
        self.CON = QtWidgets.QLabel(Form)
        self.CON.setGeometry(QtCore.QRect(80, 40, 16, 16))
        self.CON.setObjectName("CON")
        self.SIZ = QtWidgets.QLabel(Form)
        self.SIZ.setGeometry(QtCore.QRect(80, 60, 16, 16))
        self.SIZ.setObjectName("SIZ")
        self.DEX = QtWidgets.QLabel(Form)
        self.DEX.setGeometry(QtCore.QRect(80, 80, 16, 16))
        self.DEX.setObjectName("DEX")
        self.APP = QtWidgets.QLabel(Form)
        self.APP.setGeometry(QtCore.QRect(210, 20, 16, 16))
        self.APP.setObjectName("APP")
        self.INT = QtWidgets.QLabel(Form)
        self.INT.setGeometry(QtCore.QRect(210, 40, 16, 16))
        self.INT.setObjectName("INT")
        self.POW = QtWidgets.QLabel(Form)
        self.POW.setGeometry(QtCore.QRect(210, 60, 16, 16))
        self.POW.setObjectName("POW")
        self.EDU = QtWidgets.QLabel(Form)
        self.EDU.setGeometry(QtCore.QRect(210, 80, 16, 16))
        self.EDU.setObjectName("EDU")

        self.info_complete = 0

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sex_0.setText(_translate("Form", "男"))
        self.label.setText(_translate("Form", "姓名："))
        self.next_step.setText(_translate("Form", "下一步"))
        self.label_2.setText(_translate("Form", "性别："))
        self.label_3.setText(_translate("Form", "年龄："))
        self.label_4.setText(_translate("Form", "住地："))
        self.sex_1.setText(_translate("Form", "女"))
        self.label_5.setText(_translate("Form", "故乡："))
        self.label_6.setText(_translate("Form", "这是你的随机属性："))
        self.label_7.setText(_translate("Form", "力量(STR)："))
        self.label_8.setText(_translate("Form", "外貌(APP)："))
        self.label_9.setText(_translate("Form", "智力(INT)："))
        self.label_10.setText(_translate("Form", "意志(POW)："))
        self.label_11.setText(_translate("Form", "教育(EDU)："))
        self.label_12.setText(_translate("Form", "敏捷(DEX)："))
        self.label_13.setText(_translate("Form", "体型(SIZ)："))
        self.label_14.setText(_translate("Form", "体质(CON)："))
        self.STR.setText(_translate("Form", "##"))
        self.CON.setText(_translate("Form", "##"))
        self.SIZ.setText(_translate("Form", "##"))
        self.DEX.setText(_translate("Form", "##"))
        self.APP.setText(_translate("Form", "##"))
        self.INT.setText(_translate("Form", "##"))
        self.POW.setText(_translate("Form", "##"))
        self.EDU.setText(_translate("Form", "##"))
