# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlayerChooseCard_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(599, 417)
        self.new_card = QtWidgets.QPushButton(Form)
        self.new_card.setGeometry(QtCore.QRect(480, 390, 111, 23))
        self.new_card.setObjectName("new_card")
        self.card_list_widget = QtWidgets.QListWidget(Form)
        self.card_list_widget.setGeometry(QtCore.QRect(0, 0, 256, 421))
        self.card_list_widget.setObjectName("card_list_widget")
        self.show_card = QtWidgets.QPushButton(Form)
        self.show_card.setEnabled(False)
        self.show_card.setGeometry(QtCore.QRect(260, 390, 101, 23))
        self.show_card.setObjectName("show_card")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(270, 10, 31, 16))
        self.label.setObjectName("label")
        self.info1 = QtWidgets.QLineEdit(Form)
        self.info1.setGeometry(QtCore.QRect(300, 10, 113, 20))
        self.info1.setReadOnly(True)
        self.info1.setObjectName("info1")
        self.info2 = QtWidgets.QLineEdit(Form)
        self.info2.setGeometry(QtCore.QRect(300, 40, 113, 20))
        self.info2.setReadOnly(True)
        self.info2.setObjectName("info2")
        self.info3 = QtWidgets.QLineEdit(Form)
        self.info3.setGeometry(QtCore.QRect(300, 70, 113, 20))
        self.info3.setReadOnly(True)
        self.info3.setObjectName("info3")
        self.info4 = QtWidgets.QLineEdit(Form)
        self.info4.setGeometry(QtCore.QRect(300, 100, 113, 20))
        self.info4.setReadOnly(True)
        self.info4.setObjectName("info4")
        self.info5 = QtWidgets.QLineEdit(Form)
        self.info5.setGeometry(QtCore.QRect(300, 130, 113, 20))
        self.info5.setReadOnly(True)
        self.info5.setObjectName("info5")
        self.STR = QtWidgets.QLineEdit(Form)
        self.STR.setGeometry(QtCore.QRect(460, 30, 31, 20))
        self.STR.setReadOnly(True)
        self.STR.setObjectName("STR")
        self.CON = QtWidgets.QLineEdit(Form)
        self.CON.setGeometry(QtCore.QRect(540, 30, 31, 20))
        self.CON.setReadOnly(True)
        self.CON.setObjectName("CON")
        self.SIZ = QtWidgets.QLineEdit(Form)
        self.SIZ.setGeometry(QtCore.QRect(460, 60, 31, 20))
        self.SIZ.setReadOnly(True)
        self.SIZ.setObjectName("SIZ")
        self.DEX = QtWidgets.QLineEdit(Form)
        self.DEX.setGeometry(QtCore.QRect(540, 60, 31, 20))
        self.DEX.setReadOnly(True)
        self.DEX.setObjectName("DEX")
        self.APP = QtWidgets.QLineEdit(Form)
        self.APP.setGeometry(QtCore.QRect(460, 90, 31, 20))
        self.APP.setReadOnly(True)
        self.APP.setObjectName("APP")
        self.INT = QtWidgets.QLineEdit(Form)
        self.INT.setGeometry(QtCore.QRect(540, 90, 31, 20))
        self.INT.setReadOnly(True)
        self.INT.setObjectName("INT")
        self.POW = QtWidgets.QLineEdit(Form)
        self.POW.setGeometry(QtCore.QRect(460, 120, 31, 20))
        self.POW.setReadOnly(True)
        self.POW.setObjectName("POW")
        self.EDU = QtWidgets.QLineEdit(Form)
        self.EDU.setGeometry(QtCore.QRect(540, 120, 31, 20))
        self.EDU.setReadOnly(True)
        self.EDU.setObjectName("EDU")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(270, 40, 31, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(270, 70, 31, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(270, 100, 31, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(270, 130, 31, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(270, 160, 31, 16))
        self.label_6.setObjectName("label_6")
        self.info6 = QtWidgets.QLineEdit(Form)
        self.info6.setGeometry(QtCore.QRect(300, 160, 113, 20))
        self.info6.setReadOnly(True)
        self.info6.setObjectName("info6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(420, 30, 31, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(420, 60, 31, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(420, 90, 31, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(420, 120, 31, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(500, 30, 31, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(500, 60, 31, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(500, 90, 31, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(500, 120, 31, 16))
        self.label_14.setObjectName("label_14")
        self.HP = QtWidgets.QProgressBar(Form)
        self.HP.setGeometry(QtCore.QRect(300, 190, 100, 21))
        self.HP.setStyleSheet("QProgressBar {   border: 2px solid grey;   border-radius: 5px;   background-color: #FFFFFF;}QProgressBar::chunk {   background-color: \n"
"#FF0000;}QProgressBar {   border: 2px solid grey;   border-radius: 5px;   text-align: center;}")
        self.HP.setProperty("value", 0)
        self.HP.setTextVisible(False)
        self.HP.setObjectName("HP")
        self.SAN = QtWidgets.QProgressBar(Form)
        self.SAN.setGeometry(QtCore.QRect(300, 220, 100, 21))
        self.SAN.setStyleSheet("QProgressBar {   border: 2px solid grey;   border-radius: 5px;   background-color: #FFFFFF;}QProgressBar::chunk {   background-color: \n"
"#9900FF;}QProgressBar {   border: 2px solid grey;   border-radius: 5px;   text-align: center;}")
        self.SAN.setProperty("value", 0)
        self.SAN.setTextVisible(False)
        self.SAN.setObjectName("SAN")
        self.MP = QtWidgets.QProgressBar(Form)
        self.MP.setGeometry(QtCore.QRect(300, 250, 100, 21))
        self.MP.setStyleSheet("QProgressBar {   border: 2px solid grey;   border-radius: 5px;   background-color: #FFFFFF;}QProgressBar::chunk {   background-color: \n"
"#0099FF;}QProgressBar {   border: 2px solid grey;   border-radius: 5px;   text-align: center;}")
        self.MP.setProperty("value", 0)
        self.MP.setTextVisible(False)
        self.MP.setInvertedAppearance(False)
        self.MP.setObjectName("MP")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(270, 190, 31, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(270, 220, 31, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(270, 250, 31, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(430, 190, 16, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(430, 220, 16, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(430, 250, 16, 16))
        self.label_20.setObjectName("label_20")
        self.current_HP = QtWidgets.QLabel(Form)
        self.current_HP.setGeometry(QtCore.QRect(410, 190, 21, 16))
        self.current_HP.setObjectName("current_HP")
        self.max_HP = QtWidgets.QLabel(Form)
        self.max_HP.setGeometry(QtCore.QRect(440, 190, 31, 16))
        self.max_HP.setText("")
        self.max_HP.setObjectName("max_HP")
        self.current_SAN = QtWidgets.QLabel(Form)
        self.current_SAN.setGeometry(QtCore.QRect(410, 220, 21, 16))
        self.current_SAN.setText("")
        self.current_SAN.setObjectName("current_SAN")
        self.max_SAN = QtWidgets.QLabel(Form)
        self.max_SAN.setGeometry(QtCore.QRect(440, 220, 31, 16))
        self.max_SAN.setText("")
        self.max_SAN.setObjectName("max_SAN")
        self.current_MP = QtWidgets.QLabel(Form)
        self.current_MP.setGeometry(QtCore.QRect(410, 250, 21, 16))
        self.current_MP.setText("")
        self.current_MP.setObjectName("current_MP")
        self.max_MP = QtWidgets.QLabel(Form)
        self.max_MP.setGeometry(QtCore.QRect(440, 250, 31, 16))
        self.max_MP.setText("")
        self.max_MP.setObjectName("max_MP")
        self.HP_2 = QtWidgets.QProgressBar(Form)
        self.HP_2.setGeometry(QtCore.QRect(300, 190, 100, 21))
        self.HP_2.setStyleSheet("QProgressBar {   border: 2px solid grey;   border-radius: 5px;   background-color: #808080;}QProgressBar::chunk {   background-color: \n"
"#FF0000;}QProgressBar {   border: 2px solid grey;   border-radius: 5px;   text-align: center;}")
        self.HP_2.setProperty("value", 0)
        self.HP_2.setTextVisible(False)
        self.HP_2.setObjectName("HP_2")
        self.SAN_2 = QtWidgets.QProgressBar(Form)
        self.SAN_2.setGeometry(QtCore.QRect(300, 220, 100, 21))
        self.SAN_2.setStyleSheet("QProgressBar {   border: 2px solid grey;   border-radius: 5px;   background-color: #808080;}QProgressBar::chunk {   background-color: \n"
"#9900FF;}QProgressBar {   border: 2px solid grey;   border-radius: 5px;   text-align: center;}")
        self.SAN_2.setProperty("value", 0)
        self.SAN_2.setTextVisible(False)
        self.SAN_2.setObjectName("SAN_2")
        self.MP_2 = QtWidgets.QProgressBar(Form)
        self.MP_2.setGeometry(QtCore.QRect(300, 250, 100, 21))
        self.MP_2.setStyleSheet("QProgressBar {   border: 2px solid grey;   border-radius: 5px;   background-color: #808080;}QProgressBar::chunk {   background-color: \n"
"#0099FF;}QProgressBar {   border: 2px solid grey;   border-radius: 5px;   text-align: center;}")
        self.MP_2.setProperty("value", 0)
        self.MP_2.setTextVisible(False)
        self.MP_2.setInvertedAppearance(False)
        self.MP_2.setObjectName("MP_2")
        self.delete_card = QtWidgets.QPushButton(Form)
        self.delete_card.setEnabled(False)
        self.delete_card.setGeometry(QtCore.QRect(370, 390, 101, 23))
        self.delete_card.setObjectName("delete_card")
        self.MP_2.raise_()
        self.SAN_2.raise_()
        self.HP_2.raise_()
        self.new_card.raise_()
        self.card_list_widget.raise_()
        self.show_card.raise_()
        self.label.raise_()
        self.info1.raise_()
        self.info2.raise_()
        self.info3.raise_()
        self.info4.raise_()
        self.info5.raise_()
        self.STR.raise_()
        self.CON.raise_()
        self.SIZ.raise_()
        self.DEX.raise_()
        self.APP.raise_()
        self.INT.raise_()
        self.POW.raise_()
        self.EDU.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.info6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.HP.raise_()
        self.SAN.raise_()
        self.MP.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.current_HP.raise_()
        self.max_HP.raise_()
        self.current_SAN.raise_()
        self.max_SAN.raise_()
        self.current_MP.raise_()
        self.max_MP.raise_()
        self.delete_card.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.new_card.setText(_translate("Form", "新建人物卡……"))
        self.show_card.setText(_translate("Form", "查看该人物卡"))
        self.label.setText(_translate("Form", "姓名："))
        self.label_2.setText(_translate("Form", "性别："))
        self.label_3.setText(_translate("Form", "年龄："))
        self.label_4.setText(_translate("Form", "职业："))
        self.label_5.setText(_translate("Form", "住地："))
        self.label_6.setText(_translate("Form", "故乡："))
        self.label_7.setText(_translate("Form", "力量："))
        self.label_8.setText(_translate("Form", "体型："))
        self.label_9.setText(_translate("Form", "外貌："))
        self.label_10.setText(_translate("Form", "意志："))
        self.label_11.setText(_translate("Form", "体质："))
        self.label_12.setText(_translate("Form", "敏捷："))
        self.label_13.setText(_translate("Form", "智力："))
        self.label_14.setText(_translate("Form", "教育："))
        self.label_15.setText(_translate("Form", "HP："))
        self.label_16.setText(_translate("Form", "SAN："))
        self.label_17.setText(_translate("Form", "MP："))
        self.label_18.setText(_translate("Form", "/"))
        self.label_19.setText(_translate("Form", "/"))
        self.label_20.setText(_translate("Form", "/"))
        self.current_HP.setText(_translate("Form", " "))
        self.delete_card.setText(_translate("Form", "删除该人物卡"))
