# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SetBackground_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(780, 557)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 191, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 54, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(50, 140, 54, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(23, 190, 81, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(50, 240, 54, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(70, 290, 31, 16))
        self.label_7.setObjectName("label_7")
        self.bg1 = QtWidgets.QPlainTextEdit(Form)
        self.bg1.setGeometry(QtCore.QRect(110, 40, 261, 41))
        self.bg1.setObjectName("bg1")
        self.bg2 = QtWidgets.QPlainTextEdit(Form)
        self.bg2.setGeometry(QtCore.QRect(110, 90, 261, 41))
        self.bg2.setObjectName("bg2")
        self.bg3 = QtWidgets.QPlainTextEdit(Form)
        self.bg3.setGeometry(QtCore.QRect(110, 140, 261, 41))
        self.bg3.setObjectName("bg3")
        self.bg4 = QtWidgets.QPlainTextEdit(Form)
        self.bg4.setGeometry(QtCore.QRect(110, 190, 261, 41))
        self.bg4.setObjectName("bg4")
        self.bg5 = QtWidgets.QPlainTextEdit(Form)
        self.bg5.setGeometry(QtCore.QRect(110, 240, 261, 41))
        self.bg5.setObjectName("bg5")
        self.bg6 = QtWidgets.QPlainTextEdit(Form)
        self.bg6.setGeometry(QtCore.QRect(110, 290, 261, 41))
        self.bg6.setObjectName("bg6")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(30, 340, 71, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(10, 390, 91, 20))
        self.label_9.setObjectName("label_9")
        self.bg7 = QtWidgets.QPlainTextEdit(Form)
        self.bg7.setGeometry(QtCore.QRect(110, 340, 261, 41))
        self.bg7.setObjectName("bg7")
        self.bg8 = QtWidgets.QPlainTextEdit(Form)
        self.bg8.setGeometry(QtCore.QRect(110, 390, 261, 41))
        self.bg8.setObjectName("bg8")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(23, 440, 81, 20))
        self.label_10.setObjectName("label_10")
        self.bg9 = QtWidgets.QPlainTextEdit(Form)
        self.bg9.setGeometry(QtCore.QRect(110, 440, 261, 101))
        self.bg9.setObjectName("bg9")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(420, 10, 101, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(383, 190, 81, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(430, 290, 31, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(410, 40, 54, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(390, 90, 71, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(410, 240, 54, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(410, 140, 54, 16))
        self.label_17.setObjectName("label_17")
        self.rbg1 = QtWidgets.QTextBrowser(Form)
        self.rbg1.setGeometry(QtCore.QRect(470, 40, 301, 41))
        self.rbg1.setObjectName("rbg1")
        self.rbg2 = QtWidgets.QTextBrowser(Form)
        self.rbg2.setGeometry(QtCore.QRect(470, 90, 301, 41))
        self.rbg2.setObjectName("rbg2")
        self.rbg3 = QtWidgets.QTextBrowser(Form)
        self.rbg3.setGeometry(QtCore.QRect(470, 140, 301, 41))
        self.rbg3.setObjectName("rbg3")
        self.rbg4 = QtWidgets.QTextBrowser(Form)
        self.rbg4.setGeometry(QtCore.QRect(470, 190, 301, 41))
        self.rbg4.setObjectName("rbg4")
        self.rbg5 = QtWidgets.QTextBrowser(Form)
        self.rbg5.setGeometry(QtCore.QRect(470, 240, 301, 41))
        self.rbg5.setObjectName("rbg5")
        self.rbg6 = QtWidgets.QTextBrowser(Form)
        self.rbg6.setGeometry(QtCore.QRect(470, 290, 301, 41))
        self.rbg6.setObjectName("rbg6")
        self.renew = QtWidgets.QPushButton(Form)
        self.renew.setGeometry(QtCore.QRect(530, 10, 41, 23))
        self.renew.setObjectName("renew")
        self.finish = QtWidgets.QPushButton(Form)
        self.finish.setGeometry(QtCore.QRect(690, 520, 75, 23))
        self.finish.setObjectName("finish")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "请在此输入你的背景故事（可留空）"))
        self.label_2.setText(_translate("Form", "个人描述："))
        self.label_3.setText(_translate("Form", "思想与信念："))
        self.label_4.setText(_translate("Form", "重要之人："))
        self.label_5.setText(_translate("Form", "意义非凡之地："))
        self.label_6.setText(_translate("Form", "宝贵之物："))
        self.label_7.setText(_translate("Form", "特质："))
        self.label_8.setText(_translate("Form", "伤口和疤痕："))
        self.label_9.setText(_translate("Form", "恐惧症和狂躁症："))
        self.label_10.setText(_translate("Form", "其他可选描述："))
        self.label_11.setText(_translate("Form", "参考随机背景故事："))
        self.label_12.setText(_translate("Form", "意义非凡之地："))
        self.label_13.setText(_translate("Form", "特质："))
        self.label_14.setText(_translate("Form", "个人描述："))
        self.label_15.setText(_translate("Form", "思想与信念："))
        self.label_16.setText(_translate("Form", "宝贵之物："))
        self.label_17.setText(_translate("Form", "重要之人："))
        self.renew.setText(_translate("Form", "刷新"))
        self.finish.setText(_translate("Form", "完成"))
